# Study 1 Data Processing

## SETUP

```{r preferences-clean, eval = TRUE}
set.seed(42) # Seed for random number generation
knitr::opts_chunk$set(cache.extra = knitr::rand_seed
                      , echo = FALSE
                      , message = FALSE
                      , warning = FALSE
                      , eval = TRUE # TRUE if re-running code from scratch; FALSE if output only
#                      , fig.show = 'hold'
#                      , fig.align = 'center'
                      )

options(
  knitr.duplicate.label = "allow"
  # , knitr.graphics.auto_pdf = TRUE
  # , knitr.table.format = function() {
  # if (knitr::is_latex_output()) 'latex' else 'pandoc'
  #   }
  )
```

```{r libraries-clean, eval = TRUE}
#data readers ---------------------------
pacman::p_load(haven, readstata13, readxl, foreign) # others: read_excel, rtiffs

#basics ---------------------------
library(knitr)
library(magrittr)
library(dplyr)
library(janitor)

#labels ---------------------------
pacman::p_load(sjlabelled, labelled) #surveytoolbox, tinylabels) 

#summary/output ---------------------------
pacman::p_load(kableExtra, summarytools, table1) #papeR)

#publish ---------------------------
library(apastats)
library(papaja)

#plots ---------------------------
library(ggplot2)
library(corrgram)
library(psych)
```

```{r load-s1, eval = TRUE}
# 1-KEYS & FUNCTIONS ---------------------------
load(file = "/Users/cintiahinojosa/Box/Dissertation/data/dissertation-keys.RData")

# 2-CLEANED DATASETS ---------------------------
# load(file = "/Users/cintiahinojosa/Box/Dissertation-Proposal/Data/s1.RData")
# load(file = "/Users/cintiahinojosa/Box/Dissertation-Proposal/Data/s2.RData")
# load(file = "/Users/cintiahinojosa/Box/Dissertation-Proposal/Data/s3.RData")

# 3-CLEANED STUDY WORKSPACES ---------------------------
# load(file = "/Users/cintiahinojosa/Box/Dissertation/data/clean-s1.RData")
# load(file = "/Users/cintiahinojosa/Box/Dissertation/data/clean-s2.RData")
# load(file = "/Users/cintiahinojosa/Box/Dissertation/data/clean-s3.RData")

# 4-COMBINED CLEANED WORKSAPCE FOR ANALYSES & PLOTS ---------------------------
# load(file = "/Users/cintiahinojosa/Box/Dissertation/data/dissertation-starter.RData") # use to start chstudy1-si code
# load(file = "/Users/cintiahinojosa/Box/Dissertation/data/dissertation-workspace.RData")

# ROUND NUMERIC VARS
# s1 <- s1 %>% mutate_if(is.numeric, round, digits = 3)

# 5-CLEANED DATA SAVED AFTER ANALYSES & PLOTS ---------------------------
# load(file = "/Users/cintiahinojosa/Box/Dissertation/data/dissertation-workspace.RData")
```

```{r raw-s1}
# LIBRARIES ---------------------------
# library(qualtRics) #read_survey()
# library(dplyr) #names() as_tibble()

# LOAD RAW DATA ---------------------------
# export qualtrics data as numeric and as text to cross-check
# (do not check "Use internal IDs in header")
s1.num <- qualtRics::read_survey("/Users/cintiahinojosa/Box/Dissertation-Proposal/Data/Raw/Gun+Violence+Framing+V2-NUMERIC.csv") # N = 886

s1.txt <- qualtRics::read_survey("/Users/cintiahinojosa/Box/Dissertation-Proposal/Data/Raw/Gun+Violence+Framing+V2-TEXT.csv") # N = 886

# RAW CODEBOOK  ---------------------------
# sjPlot::view_df(s1.num, show.type = TRUE, show.values = TRUE, show.string.values = TRUE, show.labels = TRUE, wrap.labels = 40, show.frq = TRUE, show.prc = TRUE, use.viewer = FALSE)

# sjPlot::view_df(s1.txt, show.type = TRUE, show.values = TRUE, show.string.values = TRUE, show.labels = TRUE, wrap.labels = 40, show.frq = TRUE, show.prc = TRUE, use.viewer = FALSE)

# RENAME MAIN ---------------------------
# lowercase 
names(s1.num) <- tolower(names(s1.num))
names(s1.txt) <- tolower(names(s1.txt))

# META ---------------------------
names(s1.num)[names(s1.num) == "responseid"] <- "id"
names(s1.num)[names(s1.num) == "duration (in seconds)"] <- "duration"

names(s1.txt)[names(s1.txt) == "responseid"] <- "id"
names(s1.txt)[names(s1.txt) == "duration (in seconds)"] <- "duration"

# RACE ---------------------------
names(s1.num)[names(s1.num) == "ethnicity_1"] <- "white"
names(s1.num)[names(s1.num) == "ethnicity_2"] <- "latino"
names(s1.num)[names(s1.num) == "ethnicity_3"] <- "black"
names(s1.num)[names(s1.num) == "ethnicity_4"] <- "native"
names(s1.num)[names(s1.num) == "ethnicity_5"] <- "asian"
names(s1.num)[names(s1.num) == "ethnicity_6"] <- "mideastern"
names(s1.num)[names(s1.num) == "ethnicity_7"] <- "islander"
names(s1.num)[names(s1.num) == "ethnicity_8"] <- "race_other"
names(s1.num)[names(s1.num) == "ethnicity_8_text"] <- "race_other_text"

names(s1.txt)[names(s1.txt) == "ethnicity_1"] <- "white"
names(s1.txt)[names(s1.txt) == "ethnicity_2"] <- "latino"
names(s1.txt)[names(s1.txt) == "ethnicity_3"] <- "black"
names(s1.txt)[names(s1.txt) == "ethnicity_4"] <- "native"
names(s1.txt)[names(s1.txt) == "ethnicity_5"] <- "asian"
names(s1.txt)[names(s1.txt) == "ethnicity_6"] <- "mideastern"
names(s1.txt)[names(s1.txt) == "ethnicity_7"] <- "islander"
names(s1.txt)[names(s1.txt) == "ethnicity_8"] <- "race_other"
names(s1.txt)[names(s1.txt) == "ethnicity_8_text"] <- "race_other_text"

# IVS ---------------------------
names(s1.num)[names(s1.num) == "gender_4_text"] <- "gender_other_text"
names(s1.num)[names(s1.num) == "party_4_text"] <- "party_other_text"
names(s1.num)[names(s1.num) == "household_9_text"] <- "household_other_text"
names(s1.num)[names(s1.num) == "edu_10_text"] <- "edu_other_text"

names(s1.txt)[names(s1.txt) == "gender_4_text"] <- "gender_other_text"
names(s1.txt)[names(s1.txt) == "party_4_text"] <- "party_other_text"
names(s1.txt)[names(s1.txt) == "household_9_text"] <- "household_other_text"
names(s1.txt)[names(s1.txt) == "edu_10_text"] <- "edu_other_text"

# POLICIES ---------------------------
names(s1.num)[names(s1.num) == "proffstreet"] <- "gun_street"
names(s1.num)[names(s1.num) == "prwork"] <- "gun_work"
names(s1.num)[names(s1.num) == "prparent"] <- "gun_parent"
names(s1.num)[names(s1.num) == "prpunish"] <- "gun_punish"
names(s1.num)[names(s1.num) == "policy_r1"] <- "rest_youth"
names(s1.num)[names(s1.num) == "policy_r2"] <- "rest_jobs"
names(s1.num)[names(s1.num) == "policy_r3"] <- "rest_fedaid"
names(s1.num)[names(s1.num) == "policy_r4"] <- "rest_banbox"
names(s1.num)[names(s1.num) == "policy_p1"] <- "pun_cops"
names(s1.num)[names(s1.num) == "policy_p2"] <- "pun_jailtime"
names(s1.num)[names(s1.num) == "policy_p3"] <- "pun_prisons"

names(s1.txt)[names(s1.txt) == "proffstreet"] <- "gun_street"
names(s1.txt)[names(s1.txt) == "prwork"] <- "gun_work"
names(s1.txt)[names(s1.txt) == "prparent"] <- "gun_parent"
names(s1.txt)[names(s1.txt) == "prpunish"] <- "gun_punish"
names(s1.txt)[names(s1.txt) == "policy_r1"] <- "rest_youth"
names(s1.txt)[names(s1.txt) == "policy_r2"] <- "rest_jobs"
names(s1.txt)[names(s1.txt) == "policy_r3"] <- "rest_fedaid"
names(s1.txt)[names(s1.txt) == "policy_r4"] <- "rest_banbox"
names(s1.txt)[names(s1.txt) == "policy_p1"] <- "pun_cops"
names(s1.txt)[names(s1.txt) == "policy_p2"] <- "pun_jailtime"
names(s1.txt)[names(s1.txt) == "policy_p3"] <- "pun_prisons"
names(s1.txt)[names(s1.txt) == "policy_p4"] <- "pun_penalty"

# MODERN RACISM ---------------------------
names(s1.num)[names(s1.num) == "srhard"] <- "sr_hard"
names(s1.num)[names(s1.num) == "srminorities"] <- "sr_minorities"
names(s1.num)[names(s1.num) == "srdemand"] <- "sr_demand"
names(s1.num)[names(s1.num) == "srtension"] <- "sr_tension"
names(s1.num)[names(s1.num) == "srcomplain_r"] <- "sr_complain_r"
names(s1.num)[names(s1.num) == "srdiscrim_r"] <- "sr_discrim_r"
names(s1.num)[names(s1.num) == "srslavery_r"] <- "sr_slavery_r"
names(s1.num)[names(s1.num) == "srchange"] <- "sr_change"
names(s1.num)[names(s1.num) == "srdeserve_r"] <- "sr_deserve_r"
names(s1.num)[names(s1.num) == "srecon"] <- "sr_econ"

names(s1.txt)[names(s1.txt) == "srhard"] <- "sr_hard"
names(s1.txt)[names(s1.txt) == "srminorities"] <- "sr_minorities"
names(s1.txt)[names(s1.txt) == "srdemand"] <- "sr_demand"
names(s1.txt)[names(s1.txt) == "srtension"] <- "sr_tension"
names(s1.txt)[names(s1.txt) == "srcomplain_r"] <- "sr_complain_r"
names(s1.txt)[names(s1.txt) == "srdiscrim_r"] <- "sr_discrim_r"
names(s1.txt)[names(s1.txt) == "srslavery_r"] <- "sr_slavery_r"
names(s1.txt)[names(s1.txt) == "srchange"] <- "sr_change"
names(s1.txt)[names(s1.txt) == "srdeserve_r"] <- "sr_deserve_r"
names(s1.txt)[names(s1.txt) == "srecon"] <- "sr_econ"

# check reversed vars (higher number/disagreement = more racist)
freq(s1.txt$sr_discrim_r)
table(s1.num$sr_discrim_r, s1.txt$sr_discrim_r) # None at all (5) = 33; a great deal (1) = 154
table(s1.num$sr_complain_r, s1.txt$sr_complain_r) # strongly disagree (7) = 84; strongly agree (1) = 59 
table(s1.num$sr_slavery_r, s1.txt$sr_slavery_r) # strongly disagree (7) = 64; strongly agree (1) = 175 
table(s1.num$sr_deserve_r, s1.txt$sr_deserve_r) # strongly disagree (7) = 53; strongly agree (1) = 129

# STEREOTYPES ---------------------------
names(s1.num)[names(s1.num) == "viol_hisp"] <- "viol_hispanic"
names(s1.txt)[names(s1.txt) == "viol_hisp"] <- "viol_hispanic"

# Alternative varnames
# s1$isr1.hard <- s1$sr_hard.c
# s1$isr2.minorities <- s1$sr_minorities.c
# s1$isr3.demand <- s1$sr_demand.c
# s1$isr4.tension <- s1$sr_tension.c
# s1$isr5.complain <- s1$sr_complain_r.c
# s1$esr6.discrim <- s1$sr_discrim_r.c
# s1$esr7.slavery <- s1$sr_slavery_r.c
# s1$esr8.change <- s1$sr_change.c
# s1$esr9.deserve <- s1$sr_deserve_r.c
# s1$esr10.econ <- s1$sr_econ.c

# RENAME S1 COMPREHENSION CHECKS ---------------------------
names(s1.num)[names(s1.num) == "ind1_cc1"] <- "individual1_cc1"
names(s1.num)[names(s1.num) == "ind1_cc2"] <- "individual1_cc2"
names(s1.num)[names(s1.num) == "ind1_cc3_1"] <- "individual1_cc3_1"
names(s1.num)[names(s1.num) == "ind1_cc3_4"] <- "individual1_cc3_4"
names(s1.num)[names(s1.num) == "ind1_cc3_2"] <- "individual1_cc3_2"
names(s1.num)[names(s1.num) == "ind1_cc3_3"] <- "individual1_cc3_3"
names(s1.num)[names(s1.num) == "ind2_cc1"] <- "individual2_cc1"
names(s1.num)[names(s1.num) == "ind2_cc2"] <- "individual2_cc2"
names(s1.num)[names(s1.num) == "ind2_cc3_1"] <- "individual2_cc3_1"
names(s1.num)[names(s1.num) == "ind2_cc3_4"] <- "individual2_cc3_4"
names(s1.num)[names(s1.num) == "ind2_cc3_2"] <- "individual2_cc3_2"
names(s1.num)[names(s1.num) == "ind2_cc3_3"] <- "individual2_cc3_3"
names(s1.num)[names(s1.num) == "ind3_cc1"] <- "individual3_cc1"
names(s1.num)[names(s1.num) == "ind3_cc2"] <- "individual3_cc2"
names(s1.num)[names(s1.num) == "ind3_cc3_1"] <- "individual3_cc3_1"
names(s1.num)[names(s1.num) == "ind3_cc3_4"] <- "individual3_cc3_4"
names(s1.num)[names(s1.num) == "ind3_cc3_2"] <- "individual3_cc3_2"
names(s1.num)[names(s1.num) == "ind3_cc3_3"] <- "individual3_cc3_3"
names(s1.num)[names(s1.num) == "sit_cc1"] <- "critical_cc1"
names(s1.num)[names(s1.num) == "sit1_cc2"] <- "critical1_cc2"
names(s1.num)[names(s1.num) == "sit1_cc3_1"] <- "critical1_cc3_1"
names(s1.num)[names(s1.num) == "sit1_cc3_2"] <- "critical1_cc3_2"
names(s1.num)[names(s1.num) == "sit1_cc3_3"] <- "critical1_cc3_3"
names(s1.num)[names(s1.num) == "sit1_cc3_4"] <- "critical1_cc3_4"
names(s1.num)[names(s1.num) == "sit2_cc1"] <- "critical2_cc1"
names(s1.num)[names(s1.num) == "sit2_cc2"] <- "critical2_cc2"
names(s1.num)[names(s1.num) == "sit2_cc3_1"] <- "critical2_cc3_1"
names(s1.num)[names(s1.num) == "sit2_cc3_2"] <- "critical2_cc3_2"
names(s1.num)[names(s1.num) == "sit2_cc3_3"] <- "critical2_cc3_3"
names(s1.num)[names(s1.num) == "sit2_cc3_4"] <- "critical2_cc3_4"
names(s1.num)[names(s1.num) == "sit3_cc1"] <- "critical3_cc1"
names(s1.num)[names(s1.num) == "sit3_cc2"] <- "critical3_cc2"
names(s1.num)[names(s1.num) == "sit3_cc3_1"] <- "critical3_cc3_1"
names(s1.num)[names(s1.num) == "sit3_cc3_2"] <- "critical3_cc3_2"
names(s1.num)[names(s1.num) == "sit3_cc3_3"] <- "critical3_cc3_3"
names(s1.num)[names(s1.num) == "sit3_cc3_4"] <- "critical3_cc3_4"
names(s1.num)[names(s1.num) == "neut1_cc1"] <- "control1_cc1"
names(s1.num)[names(s1.num) == "neut1_cc2"] <- "control1_cc2"
names(s1.num)[names(s1.num) == "neut1_cc3"] <- "control1_cc3"
names(s1.num)[names(s1.num) == "neut2_cc1"] <- "control2_cc1"
names(s1.num)[names(s1.num) == "neut2_cc2"] <- "control2_cc2"
names(s1.num)[names(s1.num) == "neut2_cc3"] <- "control2_cc3"
names(s1.num)[names(s1.num) == "neut3_cc1"] <- "control3_cc1"
names(s1.num)[names(s1.num) == "neut3_cc2"] <- "control3_cc2"
names(s1.num)[names(s1.num) == "neut3_cc3"] <- "control3_cc3"

names(s1.txt)[names(s1.txt) == "ind1_cc1"] <- "individual1_cc1"
names(s1.txt)[names(s1.txt) == "ind1_cc2"] <- "individual1_cc2"
names(s1.txt)[names(s1.txt) == "ind1_cc3_1"] <- "individual1_cc3_1"
names(s1.txt)[names(s1.txt) == "ind1_cc3_4"] <- "individual1_cc3_4"
names(s1.txt)[names(s1.txt) == "ind1_cc3_2"] <- "individual1_cc3_2"
names(s1.txt)[names(s1.txt) == "ind1_cc3_3"] <- "individual1_cc3_3"
names(s1.txt)[names(s1.txt) == "ind2_cc1"] <- "individual2_cc1"
names(s1.txt)[names(s1.txt) == "ind2_cc2"] <- "individual2_cc2"
names(s1.txt)[names(s1.txt) == "ind2_cc3_1"] <- "individual2_cc3_1"
names(s1.txt)[names(s1.txt) == "ind2_cc3_4"] <- "individual2_cc3_4"
names(s1.txt)[names(s1.txt) == "ind2_cc3_2"] <- "individual2_cc3_2"
names(s1.txt)[names(s1.txt) == "ind2_cc3_3"] <- "individual2_cc3_3"
names(s1.txt)[names(s1.txt) == "ind3_cc1"] <- "individual3_cc1"
names(s1.txt)[names(s1.txt) == "ind3_cc2"] <- "individual3_cc2"
names(s1.txt)[names(s1.txt) == "ind3_cc3_1"] <- "individual3_cc3_1"
names(s1.txt)[names(s1.txt) == "ind3_cc3_4"] <- "individual3_cc3_4"
names(s1.txt)[names(s1.txt) == "ind3_cc3_2"] <- "individual3_cc3_2"
names(s1.txt)[names(s1.txt) == "ind3_cc3_3"] <- "individual3_cc3_3"
names(s1.txt)[names(s1.txt) == "sit_cc1"] <- "critical_cc1"
names(s1.txt)[names(s1.txt) == "sit1_cc2"] <- "critical1_cc2"
names(s1.txt)[names(s1.txt) == "sit1_cc3_1"] <- "critical1_cc3_1"
names(s1.txt)[names(s1.txt) == "sit1_cc3_2"] <- "critical1_cc3_2"
names(s1.txt)[names(s1.txt) == "sit1_cc3_3"] <- "critical1_cc3_3"
names(s1.txt)[names(s1.txt) == "sit1_cc3_4"] <- "critical1_cc3_4"
names(s1.txt)[names(s1.txt) == "sit2_cc1"] <- "critical2_cc1"
names(s1.txt)[names(s1.txt) == "sit2_cc2"] <- "critical2_cc2"
names(s1.txt)[names(s1.txt) == "sit2_cc3_1"] <- "critical2_cc3_1"
names(s1.txt)[names(s1.txt) == "sit2_cc3_2"] <- "critical2_cc3_2"
names(s1.txt)[names(s1.txt) == "sit2_cc3_3"] <- "critical2_cc3_3"
names(s1.txt)[names(s1.txt) == "sit2_cc3_4"] <- "critical2_cc3_4"
names(s1.txt)[names(s1.txt) == "sit3_cc1"] <- "critical3_cc1"
names(s1.txt)[names(s1.txt) == "sit3_cc2"] <- "critical3_cc2"
names(s1.txt)[names(s1.txt) == "sit3_cc3_1"] <- "critical3_cc3_1"
names(s1.txt)[names(s1.txt) == "sit3_cc3_2"] <- "critical3_cc3_2"
names(s1.txt)[names(s1.txt) == "sit3_cc3_3"] <- "critical3_cc3_3"
names(s1.txt)[names(s1.txt) == "sit3_cc3_4"] <- "critical3_cc3_4"
names(s1.txt)[names(s1.txt) == "neut1_cc1"] <- "control1_cc1"
names(s1.txt)[names(s1.txt) == "neut1_cc2"] <- "control1_cc2"
names(s1.txt)[names(s1.txt) == "neut1_cc3"] <- "control1_cc3"
names(s1.txt)[names(s1.txt) == "neut2_cc1"] <- "control2_cc1"
names(s1.txt)[names(s1.txt) == "neut2_cc2"] <- "control2_cc2"
names(s1.txt)[names(s1.txt) == "neut2_cc3"] <- "control2_cc3"
names(s1.txt)[names(s1.txt) == "neut3_cc1"] <- "control3_cc1"
names(s1.txt)[names(s1.txt) == "neut3_cc2"] <- "control3_cc2"
names(s1.txt)[names(s1.txt) == "neut3_cc3"] <- "control3_cc3"

# DROP NON-USABLE DATA ---------------------------
# drop survey previews, tests, and spam # N = 886
table(s1.txt$status, s1.num$status)
s1.num <- subset(s1.num, status == 0)
s1.txt <- subset(s1.txt, status == "IP Address")

# drop non-finished # N = 742
table(s1.txt$finished, s1.num$finished)
s1.num <- subset(s1.num, s1.num$finished == 1)
s1.txt <- subset(s1.txt, s1.txt$finished == "TRUE")

# SAVE PARTICIPANT DATA W/RENAMED COLUMNS ---------------------------
write.csv(s1.num, file = "/Users/cintiahinojosa/Box/Dissertation/data/raw/s1-raw-num.csv")
save(s1.num, file = "/Users/cintiahinojosa/Box/Dissertation/data/raw/s1-raw-num.RData")

write.csv(s1.txt, file = "/Users/cintiahinojosa/Box/Dissertation/data/raw/s1-raw-txt.csv")
save(s1.txt, file = "/Users/cintiahinojosa/Box/Dissertation/data/raw/s1-raw-txt.RData")

# SET UP WORKING DATASETS ---------------------------
# save numeric as working data file # N = 742
s1 <- as_tibble(s1.num)
s1.num <- as_tibble(s1.num)
s1.txt <- as_tibble(s1.txt)

# save names of comprehension check variables # 176 vars
names_cc_s1 <- s1 %>% dplyr::select(contains('_cc')) %>% names()

# save names of order variables # 176 vars
names_do_s1 <- s1 %>% dplyr::select(contains('_do_')) %>% names()

# save names of time variables # 40 vars
names_time_s1 <- s1 %>% dplyr::select(contains('t_')) %>%  
  dplyr::select(!starts_with('rest_')) %>%
  dplyr::select(!contains('_do_')) %>%  dplyr::select(!contains('sit_cc1')) %>% names()

# save names of main variables # 123 vars
names_s1  <- names(s1[,!(names(s1) %in% c(names_do_s1, names_time_s1))])

# save working data with main variables only # 123 vars
s1  <- s1[,!(names(s1) %in% c(names_do_s1, names_cc_s1, names_time_s1))]

# SAVE WORKING DATASET ---------------------------
# repeat this command after finishing recode chunk
save(s1, file = "/Users/cintiahinojosa/Box/Dissertation/data/s1.RData")
write.csv(s1, file = "/Users/cintiahinojosa/Box/Dissertation/data/s1.csv")
```

```{r codebook-s1}
# WORKING DATASET CODEBOOK ---------------------------
sjPlot::view_df(s1.num, show.type = TRUE, show.values = TRUE, show.string.values = TRUE, show.labels = TRUE, wrap.labels = 60, show.frq = TRUE, show.prc = TRUE, use.viewer = FALSE)
```

## CLEAN {-}

### Main 

```{r ivs-clean-s1}
# DURATION  ---------------------------
# transform seconds to minutes
s1$duration <- (s1$duration/60)
summary(s1$duration)

# mark duration quantiles for outliers
duration_q1_s1 <- quantile(s1$duration, .25) 
duration_q3_s1 <- quantile(s1$duration, .75) 
duration_iqr_s1 <- IQR(s1$duration) 

# duration_out_s1 <- boxplot.stats(s1$duration)$out
# duration_out_s1 <- which(s1$duration < duration_q1_s1 | s1$duration > duration_q3_s1)

s1$duration_under <- 0
s1$duration_under[s1$duration < 5] <- 1
s1$duration_under[s1$duration == 5] <- 0
s1$duration_under[s1$duration > 5] <- 0

freq(s1$duration_under)
# CONDITION  ---------------------------
# check and recode if needed
freq(s1$condition)
s1$condition[s1$condition == "neutral"] <- "control"
s1$condition[s1$condition == "structural"] <- "critical"

# create factor variable 
s1$condition.f <- factor(s1$condition, levels = c("critical", "control", "individual"), labels = c("Critical", "Control", "Individual"), ordered = FALSE) 
freq(s1$condition.f)

# create numeric variable
s1$condition.n <- as.numeric(s1$condition.f) 
freq(s1$condition.n)

# create binary variables
s1$critical = NA
s1$critical[s1$condition == "critical"] <- 1
s1$critical[s1$condition == "control"] <- 0
s1$critical[s1$condition == "individual"] <- 0
freq(s1$critical)
s1$critical.f <- factor(s1$critical, levels = 0:1, labels = c("non-critical", "critical"), ordered = FALSE)
freq(s1$critical.f)

s1$control = NA
s1$control[s1$condition == "critical"] <- 0
s1$control[s1$condition == "control"] <- 1
s1$control[s1$condition == "individual"] <- 0
freq(s1$control)
s1$control.f <- factor(s1$control, levels = 0:1, labels = c("non-control", "control"), ordered = FALSE)
freq(s1$control.f)

s1$individual = NA
s1$individual[s1$condition == "critical"] <- 0
s1$individual[s1$condition == "control"] <- 0
s1$individual[s1$condition == "individual"] <- 1
freq(s1$individual)
s1$individual.f <- factor(s1$individual, levels = 0:1, labels = c("non-individual", "individual"), ordered = FALSE)
freq(s1$individual.f)

# AGE  ---------------------------
freq(s1$age)
s1$age[s1$age == "4q1"] <- 41 # correct participant typo
s1$age <- as.numeric(s1$age)

# CENTER
s1 <- s1 %>%
  mutate(age.c = scale(age, center = TRUE, scale = TRUE))

# POLITICAL ---------------------------
freq(s1$political)
s1$political.f <- factor(s1$political, levels = 1:7, labels = political7.labels, ordered = TRUE) 
freq(s1$political.f)

# POLITICAL3 ---------------------------
s1$political3 = NA 
s1$political3[s1$political.f == "extremely liberal"] <- 1 # liberal
s1$political3[s1$political.f == "moderately liberal"] <- 1 # liberal
s1$political3[s1$political.f == "slightly liberal"] <- 1 # liberal
s1$political3[s1$political.f == "moderate"] <- 2 # moderate
s1$political3[s1$political.f == "slightly conservative"] <- 3 # conservative
s1$political3[s1$political.f == "moderately conservative"] <- 3 # conservative
s1$political3[s1$political.f == "extremely conservative"] <- 3 # conservative
freq(s1$political3)

s1$political3.f <- factor(s1$political3, levels = 1:3, labels = political3.labels, ordered = TRUE)
freq(s1$political3.f)

# create binary variables 
freq(s1$political3)

s1$liberal = NA
s1$liberal[s1$political3.f == "liberal"] <- 1
s1$liberal[s1$political3.f == "moderate"] <- 0
s1$liberal[s1$political3.f == "conservative"] <- 0
freq(s1$liberal)
s1$liberal.f <- factor(s1$liberal, levels = 0:1, labels = c("non-liberal", "liberal"), ordered = FALSE)
freq(s1$liberal.f)

s1$moderate = NA
s1$moderate[s1$political3.f == "liberal"] <- 0
s1$moderate[s1$political3.f == "moderate"] <- 1
s1$moderate[s1$political3.f == "conservative"] <- 0
freq(s1$moderate)
s1$moderate.f <- factor(s1$moderate, levels = 0:1, labels = c("non-moderate", "moderate"), ordered = FALSE)
freq(s1$moderate.f)

s1$conservative = NA
s1$conservative[s1$political3.f == "liberal"] <- 0
s1$conservative[s1$political3 == "moderate"] <- 0
s1$conservative[s1$political3 == "conservative"] <- 1
freq(s1$conservative)
s1$conservative.f <- factor(s1$conservative, levels = 0:1, labels = c("non-conservative", "conservative"), ordered = FALSE)
freq(s1$conservative.f)

# PARTY ---------------------------
freq(s1$party)
freq(s1.txt$party)
freq(s1.txt$party_other_text)
s1$party.f <- factor(s1$party, levels = 1:5, labels = c("democrat", "republican", "independent", "other", "none"), ordered = FALSE)
freq(s1$party.f)

s1$democrat = NA 
s1$democrat[s1$party.f == "democrat"] <- 1
s1$democrat[s1$party.f !=  "democrat"] <- 0
freq(s1$democrat)
s1$democrat.f <- factor(s1$democrat, levels = 0:1, labels = c("non-democrat", "democrat"), ordered = FALSE) 
freq(s1$democrat.f)

s1$republican = NA 
s1$republican[s1$party.f == "republican"] <- 1
s1$republican[s1$party.f !=  "republican"] <- 0
freq(s1$republican)
s1$republican.f <- factor(s1$republican, levels = 0:1, labels = c("non-republican", "republican"), ordered = FALSE) 
freq(s1$republican.f)

s1$independent = NA
s1$independent[s1$party.f == "independent"] <- 1
s1$independent[s1$party.f !=  "independent"] <- 0
freq(s1$independent)
s1$independent.f <- factor(s1$independent, levels = 0:1, labels = c("non-independent", "independent"), ordered = FALSE) 
freq(s1$independent.f)

# GENDER ---------------------------
freq(s1$gender)
freq(s1.txt$gender) 
s1$gender.f <- factor(s1$gender, levels = 1:5, labels = gender5.labels, ordered = FALSE)
freq(s1$gender.f) 

# create binary variables
s1$female = NA 
s1$female[s1$gender.f == "female"] <- 1
s1$female[s1$gender.f != "female"] <- 0
freq(s1$female) 
s1$female.f <- factor(s1$female, levels = 0:1, labels = c("non-female", "female"), ordered = FALSE) 
freq(s1$female.f) 

s1$male = NA 
s1$male[s1$gender.f == "male"] <- 1
s1$male[s1$gender.f != "male"] <- 0
freq(s1$male) 
s1$male.f <- factor(s1$male, levels = 0:1, labels = c("non-male", "male"), ordered = FALSE)
freq(s1$male.f) 

# EDU ---------------------------
freq(s1.txt$edu) 
freq(s1$edu) 
unique(s1$edu_other_text)
s1$edu[s1$edu_other_text == "Currently in college"] <- 2 # recode to 2 = high school graduate

s1$edu.f <- factor(s1$edu, levels = 1:10, labels = edu10.labels, ordered = TRUE) 
freq(s1$edu.f)

# EDU3 --------------------------- 
freq(s1$edu)
s1$edu3 = s1$edu 
s1$edu3[s1$edu == 1] <- 1 # no college degree
s1$edu3[s1$edu == 2] <- 1 # no college degree
s1$edu3[s1$edu == 3] <- 1 # no college degree
s1$edu3[s1$edu == 4] <- 2 # college
s1$edu3[s1$edu == 5] <- 2 # college
s1$edu3[s1$edu == 6] <- 3 # grad
s1$edu3[s1$edu == 7] <- 3 # grad
s1$edu3[s1$edu == 8] <- 3 # grad
s1$edu3[s1$edu == 9] <- 2 # college
freq(s1$edu3)

s1$edu3.f <- factor(s1$edu3, levels = 1:3, labels = edu3.labels, ordered = TRUE) 
freq(s1$edu3.f)

# create binary variables
s1$nocollege = NA
s1$nocollege[s1$edu3 == 1] <- 1
s1$nocollege[s1$edu3 == 2] <- 0
s1$nocollege[s1$edu3 == 3] <- 0
freq(s1$nocollege) 
s1$nocollege.f <- factor(s1$nocollege, levels = 0:1, labels = c("college degree or higher", "no college degree"), ordered = FALSE)
freq(s1$nocollege.f)

s1$college = NA
s1$college[s1$edu3 == 1] <- 0
s1$college[s1$edu3 == 2] <- 1
s1$college[s1$edu3 == 3] <- 1
freq(s1$college)
s1$college.f <- factor(s1$college, levels = 0:1, labels = c("no college degree", "college degree or higher"), ordered = FALSE)
freq(s1$college.f)

s1$grad = NA
s1$grad[s1$edu3 == 1] <- 0
s1$grad[s1$edu3 == 2] <- 0
s1$grad[s1$edu3 == 3] <- 1
freq(s1$grad)
s1$grad.f <- factor(s1$grad, levels = 0:1, labels = c("no graduate degree", "graduate degree"), ordered = FALSE)
freq(s1$grad.f)

# INCOME ---------------------------
s1$income.f <- s1$income
freq(s1$income)
s1$income.f <- factor(s1$income, levels = 1:12, labels = income12.labels, ordered = TRUE)
freq(s1$income.f)

# ADJ_INCOME ---------------------------
# median of income bin besides min/max; only use to calculate adjusted income
s1$income.med <- NA
s1$income.med[s1$income == 1] <- 10000
s1$income.med[s1$income == 2] <- 15000
s1$income.med[s1$income == 3] <- 25000
s1$income.med[s1$income == 4] <- 35000
s1$income.med[s1$income == 5] <- 45000 
s1$income.med[s1$income == 6] <- 55000
s1$income.med[s1$income == 7] <- 65000 
s1$income.med[s1$income == 8] <- 75000 
s1$income.med[s1$income == 9] <- 85000 
s1$income.med[s1$income == 10] <- 95000 
s1$income.med[s1$income == 11] <- 125000 
s1$income.med[s1$income == 12] <- 150000

# transform income to adjust for household size
s1$adj_income <- (s1$income.med/sqrt(s1$household))
s1$adj_income <- formattable::currency(s1$adj_income, digits = 2L) 
summary(s1$adj_income)

# CENTER
s1 <- s1 %>%
  mutate(adj_income.c = scale(adj_income, center = TRUE, scale = TRUE))

# RACE STEP 1: RACE_OTHER ---------------------------
# check race_other to recode accordingly # 
unique(s1$race_other_text)
# NOT recoding: 
# "Caribbean"
# "Jewish"
# "West Indian"

# recoding:
# will recode race_other to multiracial: "afro latinx", "mixed black/white", "mixed"
s1$race_other[s1$race_other_text == "afro latinx"] <- 0
s1$race_other[s1$race_other_text == "mixed black/white"] <- 0
s1$race_other[s1$race_other_text == "mixed"] <- 0

# RACE STEP 2: MULTIRACIAL ---------------------------
s1$multiracial <- NA
s1$multiracial <- rowSums(s1[, c("white", "black", "latino", "native", "asian", "mideastern", "islander", "race_other")])
freq(s1$multiracial)
s1$multiracial.f <- NA
s1$multiracial.f[s1$multiracial == 1] <- 0
s1$multiracial.f[s1$multiracial >= 2] <- 1
freq(s1$multiracial.f)
s1$multiracial <- s1$multiracial.f

# recode race_others 
freq(s1$multiracial)
s1$multiracial[s1$race_other_text == "afro latinx"] <- 1
s1$multiracial[s1$race_other_text == "mixed black/white"] <- 1
s1$multiracial[s1$race_other_text == "mixed"] <- 1 

s1$multiracial.f <- factor(s1$multiracial, levels = 0:1, labels = c("monoracial", "multiracial"), ordered = FALSE)
freq(s1$multiracial.f)

# RACE STEP 4: RACE ---------------------------
# create race variable 
freq(s1.txt$race_other_text)
s1$race = NA
s1$race[s1$race_other == 1] <- "other"
s1$race[s1$islander == 1] <- "pacific islander"
s1$race[s1$mideastern == 1] <- "middle eastern"
s1$race[s1$asian == 1] <- "asian"
s1$race[s1$native == 1] <- "native american"
s1$race[s1$black == 1] <- "black"
s1$race[s1$latino == 1] <- "latino"
s1$race[s1$white == 1] <- "white"
s1$race[s1$multiracial == 1] <- "multiracial"
freq(s1$race)

s1$race.n = NA
s1$race.n[s1$race_other == 1] <- 8
s1$race.n[s1$islander == 1] <- 7
s1$race.n[s1$mideastern == 1] <- 6
s1$race.n[s1$asian == 1] <- 5
s1$race.n[s1$native == 1] <- 4
s1$race.n[s1$black == 1] <- 3
s1$race.n[s1$latino == 1] <- 2
s1$race.n[s1$white == 1] <- 1
s1$race.n[s1$multiracial == 1] <- 9
freq(s1$race.n)

s1$race.f <- NA
s1$race.f <- factor(s1$race.n, levels = 1:9, labels = race9.labels, ordered = FALSE) 
freq(s1$race.f) 

# COMPREHENSION CHECK ---------------------------
freq(s1$fail3)
s1$pass <- 1
s1$pass[s1$fail3 == 1] <- 0
freq(s1$pass)
s1$pass.f <- factor(s1$pass, levels = 0:1, labels = c("Failed", "Passed"), ordered = FALSE)
freq(s1$pass.f)

s1$fail <- 0
s1$fail[s1$fail3 == 1] <- 1
freq(s1$fail)
s1$fail.f <- factor(s1$fail, levels = 0:1, labels = c("Passed", "Failed"), ordered = FALSE)
freq(s1$fail.f)

```

```{r subset-s1, eval = TRUE}
# COMPREHENSION CHECK ---------------------------
s1.all <- s1 # save all cases
s1.pass <- subset(s1, pass == 1)
s1.fail <- subset(s1, fail == 1)

# CONDITIONS ---------------------------
s1.control <- subset(s1, condition == "control")
s1.individual <- subset(s1, condition == "individual")
s1.critical <- subset(s1, condition == "critical")

# RACE ---------------------------
s1.black <- subset(s1, black == 1)
s1.latino <- subset(s1, latino == 1)
s1.white <- subset(s1, white == 1)
```

```{r pun-clean-s1}
# PUNITIVE
# GROUP ITEMS ---------------------------
punitive_vars_s1 <- dplyr::select(s1, pun_cops, pun_jailtime, pun_penalty, pun_prisons)
punitive_vars.names_s1 <- names(punitive_vars_s1)

# passed
punitive_vars_s1.pass <- dplyr::select(s1.pass, pun_cops, pun_jailtime, pun_penalty, pun_prisons)
punitive_vars.names_s1.pass <- names(punitive_vars_s1.pass)

# with exclusions
punitive_vars_s1.all <- dplyr::select(s1.all, pun_cops, pun_jailtime, pun_penalty, pun_prisons)
punitive_vars.names_s1.all <- names(punitive_vars_s1.all)

# CORRELATIONS ---------------------------
# correlation matrix
punitive_cormat_s1 <- cor(punitive_vars_s1, use = "complete.obs") punitive_cormat_s1 <- round(punitive_cormat_s1, 3)

# passed
punitive_cormat_s1.pass <- cor(punitive_vars_s1.pass, use = "complete.obs") 
punitive_cormat_s1.pass <- round(punitive_cormat_s1.pass, 3)

# with exclusions
punitive_cormat_s1.all <- cor(punitive_vars_s1.all, use = "complete.obs") 
punitive_cormat_s1.all <- round(punitive_cormat_s1.all, 3)

# CREATE COMPOSITE ---------------------------
summary(s1$pun_cops)
s1$punitive <- rowMeans(subset(s1, select = punitive_vars.names_s1), na.rm = TRUE)
summary(s1$punitive)
punitive_alpha_s1 <- ltm::cronbach.alpha(punitive_vars_s1)
papaja::printnum(punitive_alpha_s1$alpha) # .80

# passed
summary(s1.pass$pun_cops)
s1.pass$punitive <- rowMeans(subset(s1.pass, select = punitive_vars.names_s1.pass), na.rm = TRUE)
summary(s1.pass$punitive)
punitive_alpha_s1.pass <- ltm::cronbach.alpha(punitive_vars_s1.pass)
papaja::printnum(punitive_alpha_s1.pass$alpha) # .81

# with exclusions
summary(s1.all$pun_cops)
s1.all$punitive <- rowMeans(subset(s1.all, select = punitive_vars.names_s1.all), na.rm = TRUE)
summary(s1.all$punitive)
punitive_alpha_s1.all <- ltm::cronbach.alpha(punitive_vars_s1.all)
papaja::printnum(punitive_alpha_s1.all$alpha) # .80

# GRAND-MEAN CENTER & STANDARDIZE ---------------------------
s1 <- s1 %>%
  mutate(punitive.c = scale(punitive, center = TRUE, scale = TRUE)
         , pun_cops.c = scale(pun_cops, center = TRUE, scale = TRUE)
         , pun_jailtime.c = scale(pun_jailtime, center = TRUE, scale = TRUE)
         , pun_penalty.c = scale(pun_penalty, center = TRUE, scale = TRUE)
         , pun_prisons.c = scale(pun_prisons, center = TRUE, scale = TRUE)
         )
summary(s1$punitive.c)
summary(s1$pun_prisons.c)

# passed
s1.pass <- s1.pass %>%
  mutate(punitive.c = scale(punitive, center = TRUE, scale = TRUE)
         , pun_cops.c = scale(pun_cops, center = TRUE, scale = TRUE)
         , pun_jailtime.c = scale(pun_jailtime, center = TRUE, scale = TRUE)
         , pun_penalty.c = scale(pun_penalty, center = TRUE, scale = TRUE)
         , pun_prisons.c = scale(pun_prisons, center = TRUE, scale = TRUE)
         )
summary(s1.pass$punitive.c)
summary(s1.pass$pun_prisons.c)

# with exclusions
s1.all <- s1.all %>%
  mutate(punitive.c = scale(punitive, center = TRUE, scale = TRUE)
         , pun_cops.c = scale(pun_cops, center = TRUE, scale = TRUE)
         , pun_jailtime.c = scale(pun_jailtime, center = TRUE, scale = TRUE)
         , pun_penalty.c = scale(pun_penalty, center = TRUE, scale = TRUE)
         , pun_prisons.c = scale(pun_prisons, center = TRUE, scale = TRUE)
         )
summary(s1.all$punitive.c)
summary(s1.all$pun_prisons.c)

# GROUP STANDARDIZED ITEMS ---------------------------
punitive.c_vars_s1 <- dplyr::select(s1, pun_cops.c, pun_jailtime.c, pun_penalty.c, pun_prisons.c)
punitive.c_vars.names_s1 <- names(punitive.c_vars_s1)
punitive.c_alpha_s1 <- ltm::cronbach.alpha(punitive.c_vars_s1)
papaja::printnum(punitive.c_alpha_s1$alpha) # .80

# passed
punitive.c_vars_s1.pass <- dplyr::select(s1.pass, pun_cops.c, pun_jailtime.c, pun_penalty.c, pun_prisons.c)
punitive.c_vars.names_s1.pass <- names(punitive.c_vars_s1.pass)
punitive.c_alpha_s1.pass <- ltm::cronbach.alpha(punitive.c_vars_s1.pass)
papaja::printnum(punitive.c_alpha_s1.pass$alpha) # .81

# with exclusions
punitive.c_vars_s1.all <- dplyr::select(s1.all, pun_cops.c, pun_jailtime.c, pun_penalty.c, pun_prisons.c)
punitive.c_vars.names_s1.all <- names(punitive.c_vars_s1.all)
punitive.c_alpha_s1.all <- ltm::cronbach.alpha(punitive.c_vars_s1.all)
papaja::printnum(punitive.c_alpha_s1.all$alpha) # .80

# FACTOR VARS ---------------------------
s1$pun_cops.f <- factor(s1$pun_cops, levels = 1:4, labels = favor4.labels, ordered = TRUE)
s1$pun_jailtime.f <- factor(s1$pun_jailtime, levels = 1:4, labels = favor4.labels, ordered = TRUE)
s1$pun_penalty.f <- factor(s1$pun_penalty, levels = 1:4, labels = favor4.labels, ordered = TRUE)
s1$pun_prisons.f <- factor(s1$pun_prisons, levels = 1:4, labels = favor4.labels, ordered = TRUE)
punitive.f_vars_s1 <- dplyr::select(s1, pun_cops.f, pun_jailtime.f, pun_penalty.f, pun_prisons.f)
punitive.f_vars.names_s1 <- names(punitive.f_vars_s1)
```

```{r rest-clean-s1}
# RESTORATIVE

# FACTOR VARS ---------------------------
s1$rest_banbox.f <- factor(s1$rest_banbox, levels = 1:4, labels = favor4.labels, ordered = TRUE)
s1$rest_fedaid.f <- factor(s1$rest_fedaid, levels = 1:4, labels = favor4.labels, ordered = TRUE)
s1$rest_jobs.f <- factor(s1$rest_jobs, levels = 1:4, labels = favor4.labels, ordered = TRUE)
s1$rest_youth.f <- factor(s1$rest_youth, levels = 1:4, labels = favor4.labels, ordered = TRUE)
restorative.f_vars_s1 <- dplyr::select(s1, rest_banbox.f, rest_fedaid.f, rest_jobs.f, rest_youth.f)
restorative.f_vars.names_s1 <- names(restorative.f_vars_s1)

# GROUP ITEMS ---------------------------
restorative_vars_s1 <- dplyr::select(s1, rest_banbox, rest_fedaid, rest_jobs, rest_youth)
restorative_vars.names_s1 <- names(restorative_vars_s1)

# passed
restorative_vars_s1.pass <- dplyr::select(s1.pass, rest_banbox, rest_fedaid, rest_jobs, rest_youth)
restorative_vars.names_s1.pass <- names(restorative_vars_s1.pass)

# with exclusions
restorative_vars_s1.all <- dplyr::select(s1.all, rest_banbox, rest_fedaid, rest_jobs, rest_youth)
restorative_vars.names_s1.all <- names(restorative_vars_s1.all)

# CORRELATIONS (FULL) ---------------------------
# correlation matrix
restorative_cormat_s1 <- cor(restorative_vars_s1, use = "complete.obs") 
restorative_cormat_s1 <- round(restorative_cormat_s1, 3)

# passed
restorative_cormat_s1.pass <- cor(restorative_vars_s1.pass, use = "complete.obs") 
restorative_cormat_s1.pass <- round(restorative_cormat_s1.pass, 3)

# with exclusions
restorative_cormat_s1.all <- cor(restorative_vars_s1.all, use = "complete.obs") 
restorative_cormat_s1.all <- round(restorative_cormat_s1.all, 3)

# CREATE COMPOSITE ---------------------------
freq(s1$rest_banbox)
s1$restorative <- rowMeans(subset(s1, select = restorative_vars.names_s1), na.rm = TRUE) 
summary(s1$restorative)
restorative_alpha_s1 <- ltm::cronbach.alpha(restorative_vars_s1)
papaja::printnum(restorative_alpha_s1$alpha) # .62

# passed
freq(s1.pass$rest_banbox)
s1.pass$restorative <- rowMeans(subset(s1.pass, select = restorative_vars.names_s1.pass), na.rm = TRUE) 
summary(s1.pass$restorative)
restorative_alpha_s1.pass <- ltm::cronbach.alpha(restorative_vars_s1.pass)
papaja::printnum(restorative_alpha_s1.pass$alpha) # .66

# with exclusions
freq(s1.all$rest_banbox)
s1.all$restorative <- rowMeans(subset(s1.all, select = restorative_vars.names_s1.all), na.rm = TRUE) 
summary(s1.all$restorative)
restorative_alpha_s1.all <- ltm::cronbach.alpha(restorative_vars_s1.all)
papaja::printnum(restorative_alpha_s1.all$alpha) # .62

# GRAND-MEAN CENTER & STANDARDIZE ---------------------------
s1 <- s1 %>%
  mutate(restorative.c = scale(restorative, center = TRUE, scale = TRUE)
         , rest_banbox.c = scale(rest_banbox, center = TRUE, scale = TRUE)
         , rest_fedaid.c = scale(rest_fedaid, center = TRUE, scale = TRUE)
         , rest_jobs.c = scale(rest_jobs, center = TRUE, scale = TRUE)
         , rest_youth.c = scale(rest_youth, center = TRUE, scale = TRUE)
         ) 
summary(s1$restorative.c) 
summary(s1$rest_youth.c)

# passed
s1.pass <- s1.pass %>%
  mutate(restorative.c = scale(restorative, center = TRUE, scale = TRUE)
         , rest_banbox.c = scale(rest_banbox, center = TRUE, scale = TRUE)
         , rest_fedaid.c = scale(rest_fedaid, center = TRUE, scale = TRUE)
         , rest_jobs.c = scale(rest_jobs, center = TRUE, scale = TRUE)
         , rest_youth.c = scale(rest_youth, center = TRUE, scale = TRUE)
         ) 
summary(s1.pass$restorative.c) 
summary(s1.pass$rest_youth.c)

# with exclusions
s1.all <- s1.all %>%
  mutate(restorative.c = scale(restorative, center = TRUE, scale = TRUE)
         , rest_banbox.c = scale(rest_banbox, center = TRUE, scale = TRUE)
         , rest_fedaid.c = scale(rest_fedaid, center = TRUE, scale = TRUE)
         , rest_jobs.c = scale(rest_jobs, center = TRUE, scale = TRUE)
         , rest_youth.c = scale(rest_youth, center = TRUE, scale = TRUE)
         ) 
summary(s1.all$restorative.c) 
summary(s1.all$rest_youth.c)

# GROUP STANDARDIZED ITEMS ---------------------------
restorative.c_vars_s1 <- dplyr::select(s1, rest_banbox.c, rest_fedaid.c, rest_jobs.c, rest_youth.c)
restorative.c_vars.names_s1 <- names(restorative.c_vars_s1)
restorative.c_alpha_s1 <- ltm::cronbach.alpha(restorative.c_vars_s1) 
papaja::printnum(restorative.c_alpha_s1$alpha) # .64

# passed
restorative.c_vars_s1.pass <- dplyr::select(s1.pass, rest_banbox.c, rest_fedaid.c, rest_jobs.c, rest_youth.c)
restorative.c_vars.names_s1.pass <- names(restorative.c_vars_s1.pass)
restorative.c_alpha_s1.pass <- ltm::cronbach.alpha(restorative.c_vars_s1.pass) 
papaja::printnum(restorative.c_alpha_s1.pass$alpha) # .69

# with exclusions
restorative.c_vars_s1.all <- dplyr::select(s1.all, rest_banbox.c, rest_fedaid.c, rest_jobs.c, rest_youth.c)
restorative.c_vars.names_s1.all <- names(restorative.c_vars_s1.all)
restorative.c_alpha_s1.all <- ltm::cronbach.alpha(restorative.c_vars_s1.all) 
papaja::printnum(restorative.c_alpha_s1.all$alpha) # .64
```

```{r sr-clean-s1}
# MODERN RACISM
# GROUP ITEMS ---------------------------
sr_vars_s1 <- dplyr::select(s1, sr_hard, sr_minorities, sr_demand, sr_tension, sr_complain_r, sr_discrim_r, sr_slavery_r, sr_deserve_r, sr_change, sr_deserve_r, sr_econ)
sr_vars.names_s1 <- names(sr_vars_s1)

# passed
sr_vars_s1.pass <- dplyr::select(s1.pass, sr_hard, sr_minorities, sr_demand, sr_tension, sr_complain_r, sr_discrim_r, sr_slavery_r, sr_deserve_r, sr_change, sr_deserve_r, sr_econ)
sr_vars.names_s1.pass <- names(sr_vars_s1.pass)

# with exclusions
sr_vars_s1.all <- dplyr::select(s1.all, sr_hard, sr_minorities, sr_demand, sr_tension, sr_complain_r, sr_discrim_r, sr_slavery_r, sr_deserve_r, sr_change, sr_deserve_r, sr_econ)
sr_vars.names_s1.all <- names(sr_vars_s1.all)

# CORRELATIONS ---------------------------
# correlation matrix
sr_cormat_s1 <- cor(sr_vars_s1, use = "complete.obs") 
sr_cormat_s1 <- round(sr_cormat_s1, 3)

# passed
sr_cormat_s1.pass <- cor(sr_vars_s1.pass, use = "complete.obs") 
sr_cormat_s1.pass <- round(sr_cormat_s1.pass, 3)

# with exclusions
sr_cormat_s1.all <- cor(sr_vars_s1.all, use = "complete.obs") 
sr_cormat_s1.all <- round(sr_cormat_s1.all, 3)

# CREATE COMPOSITE BY MEAN ---------------------------
freq(s1$sr_discrim_r)
s1$sr <- rowMeans(subset(s1, select = sr_vars.names_s1), na.rm = TRUE)
summary(s1$sr)
sr_alpha_s1 <- ltm::cronbach.alpha(sr_vars_s1)
papaja::printnum(sr_alpha_s1$alpha) # .90

# passed
freq(s1.pass$sr_discrim_r)
s1.pass$sr <- rowMeans(subset(s1.pass, select = sr_vars.names_s1.pass), na.rm = TRUE)
summary(s1.pass$sr)
sr_alpha_s1.pass <- ltm::cronbach.alpha(sr_vars_s1.pass)
papaja::printnum(sr_alpha_s1.pass$alpha) # .93

# passed
freq(s1.all$sr_discrim_r)
s1.all$sr <- rowMeans(subset(s1.all, select = sr_vars.names_s1.all), na.rm = TRUE)
summary(s1.all$sr)
sr_alpha_s1.all <- ltm::cronbach.alpha(sr_vars_s1.all)
papaja::printnum(sr_alpha_s1.all$alpha) # .90

# CREATE COMPOSITE BY SUMMARY ---------------------------
s1$sr.s <- rowSums(subset(s1, select = sr_vars.names_s1), na.rm = TRUE)

# GRAND-MEAN CENTER & STANDARDIZE ---------------------------
s1 <- s1 %>%
  mutate(sr.c = scale(sr, center = TRUE, scale = TRUE)
         , sr.sc = scale(sr.s, center = TRUE, scale = TRUE)
         , sr_hard.c = scale(sr_hard, center = TRUE, scale = TRUE)
         , sr_minorities.c = scale(sr_minorities, center = TRUE, scale = TRUE)
         , sr_demand.c = scale(sr_demand, center = TRUE, scale = TRUE)
         , sr_tension.c = scale(sr_tension, center = TRUE, scale = TRUE)
         , sr_complain_r.c = scale(sr_complain_r, center = TRUE, scale = TRUE)
         , sr_discrim_r.c = scale(sr_discrim_r, center = TRUE, scale = TRUE)
         , sr_slavery_r.c = scale(sr_slavery_r, center = TRUE, scale = TRUE)
         , sr_change.c = scale(sr_change, center = TRUE, scale = TRUE)
         , sr_deserve_r.c = scale(sr_deserve_r, center = TRUE, scale = TRUE)
         , sr_econ.c = scale(sr_econ, center = TRUE, scale = TRUE)
         )
summary(s1$sr.c)
summary(s1$pun_prisons.c)

# passed
s1.pass <- s1.pass %>%
  mutate(sr.c = scale(sr, center = TRUE, scale = TRUE)
         , sr.sc = scale(sr.s, center = TRUE, scale = TRUE)
         , sr_hard.c = scale(sr_hard, center = TRUE, scale = TRUE)
         , sr_minorities.c = scale(sr_minorities, center = TRUE, scale = TRUE)
         , sr_demand.c = scale(sr_demand, center = TRUE, scale = TRUE)
         , sr_tension.c = scale(sr_tension, center = TRUE, scale = TRUE)
         , sr_complain_r.c = scale(sr_complain_r, center = TRUE, scale = TRUE)
         , sr_discrim_r.c = scale(sr_discrim_r, center = TRUE, scale = TRUE)
         , sr_slavery_r.c = scale(sr_slavery_r, center = TRUE, scale = TRUE)
         , sr_change.c = scale(sr_change, center = TRUE, scale = TRUE)
         , sr_deserve_r.c = scale(sr_deserve_r, center = TRUE, scale = TRUE)
         , sr_econ.c = scale(sr_econ, center = TRUE, scale = TRUE)
         )
summary(s1.pass$sr.c)
summary(s1.pass$pun_prisons.c)

# with exclusions
s1.all <- s1.all %>%
  mutate(sr.c = scale(sr, center = TRUE, scale = TRUE)
         , sr.sc = scale(sr.s, center = TRUE, scale = TRUE)
         , sr_hard.c = scale(sr_hard, center = TRUE, scale = TRUE)
         , sr_minorities.c = scale(sr_minorities, center = TRUE, scale = TRUE)
         , sr_demand.c = scale(sr_demand, center = TRUE, scale = TRUE)
         , sr_tension.c = scale(sr_tension, center = TRUE, scale = TRUE)
         , sr_complain_r.c = scale(sr_complain_r, center = TRUE, scale = TRUE)
         , sr_discrim_r.c = scale(sr_discrim_r, center = TRUE, scale = TRUE)
         , sr_slavery_r.c = scale(sr_slavery_r, center = TRUE, scale = TRUE)
         , sr_change.c = scale(sr_change, center = TRUE, scale = TRUE)
         , sr_deserve_r.c = scale(sr_deserve_r, center = TRUE, scale = TRUE)
         , sr_econ.c = scale(sr_econ, center = TRUE, scale = TRUE)
         )
summary(s1.all$sr.c)
summary(s1.all$pun_prisons.c)

# GROUP STANDARDIZED ITEMS ---------------------------
sr.c_vars_s1 <- dplyr::select(s1, sr_hard.c, sr_minorities.c, sr_demand.c, sr_complain_r.c, sr_slavery_r.c, sr_deserve_r.c, sr_econ.c, sr_tension.c, sr_discrim_r.c, sr_change.c)
sr.c_vars.names_s1 <- names(sr.c_vars_s1)
sr.c_alpha_s1 <- ltm::cronbach.alpha(sr.c_vars_s1)
papaja::printnum(sr.c_alpha_s1$alpha) # .90 

# passed
sr.c_vars_s1.pass <- dplyr::select(s1.pass, sr_hard.c, sr_minorities.c, sr_demand.c, sr_complain_r.c, sr_slavery_r.c, sr_deserve_r.c, sr_econ.c, sr_tension.c, sr_discrim_r.c, sr_change.c)
sr.c_vars.names_s1.pass <- names(sr.c_vars_s1.pass)
sr.c_alpha_s1.pass <- ltm::cronbach.alpha(sr.c_vars_s1.pass)
papaja::printnum(sr.c_alpha_s1.pass$alpha) # .93 

# with exclusions
sr.c_vars_s1.all <- dplyr::select(s1.all, sr_hard.c, sr_minorities.c, sr_demand.c, sr_complain_r.c, sr_slavery_r.c, sr_deserve_r.c, sr_econ.c, sr_tension.c, sr_discrim_r.c, sr_change.c)
sr.c_vars.names_s1.all <- names(sr.c_vars_s1.all)
sr.c_alpha_s1.all <- ltm::cronbach.alpha(sr.c_vars_s1.all)
papaja::printnum(sr.c_alpha_s1.all$alpha) # .90

# FACTOR VARS ---------------------------
s1$sr_slavery_r.f <- factor(s1$sr_slavery_r, levels = c(1:7), labels = agree7.labels, ordered = TRUE)
s1$sr_change.f <- factor(s1$sr_change, levels = c(1:5), labels = amount5.labels, ordered = TRUE)
s1$sr_discrim_r.f <- factor(s1$sr_discrim_r, levels = c(1:5), labels = amount5.labels, ordered = TRUE)
s1$sr_deserve_r.f <- factor(s1$sr_deserve_r, levels = c(1:7), labels = agree7.labels, ordered = TRUE)
s1$sr_econ.f <- factor(s1$sr_econ, levels = c(1:7), labels = agree7.labels, ordered = TRUE)
s1$sr_hard.f <- factor(s1$sr_hard, levels = c(1:7), labels = agree7.labels, ordered = TRUE)
s1$sr_minorities.f <- factor(s1$sr_minorities, levels = c(1:7), labels = agree7.labels, ordered = TRUE)
s1$sr_demand.f <- factor(s1$sr_demand, levels = c(1:7), labels = agree7.labels, ordered = TRUE)
s1$sr_complain_r.f <- factor(s1$sr_complain_r, levels = c(1:7), labels = agree7.labels, ordered = TRUE)
s1$sr_tension.f <- factor(s1$sr_tension, levels = c(1:5), labels = amount5.labels, ordered = TRUE)

# RENAMED VARS (not run) ---------------------------
# RIGHT ORDER
# sr_hard + sr_minorities + sr_demand + sr_tension + sr_complain_r + sr_discrim_r + sr_slavery_r + sr_deserve_r + sr_change + sr_deserve_r + sr_econ
# sr_hard, sr_minorities, sr_demand, sr_tension, sr_complain_r, sr_discrim_r, sr_slavery_r, sr_deserve_r, sr_change, sr_deserve_r, sr_econ

# s1$isr1.hard <- s1$sr_hard
# s1$isr2.minorities <- s1$sr_minorities
# s1$isr3.demand <- s1$sr_demand
# s1$isr4.tension <- s1$sr_tension
# s1$isr5.complain <- s1$sr_complain_r
# s1$esr6.discrim <- s1$sr_discrim_r
# s1$esr7.slavery <- s1$sr_slavery_r
# s1$esr8.change <- s1$sr_change
# s1$esr9.deserve <- s1$sr_deserve_r
# s1$esr10.econ <- s1$sr_econ
# 
# s1$isr1.hard.c <- s1$sr_hard.c
# s1$isr2.minorities.c <- s1$sr_minorities.c
# s1$isr3.demand.c <- s1$sr_demand.c
# s1$isr4.tension.c <- s1$sr_tension.c
# s1$isr5.complain.c <- s1$sr_complain_r.c
# s1$esr6.discrim.c <- s1$sr_discrim_r.c
# s1$esr7.slavery.c <- s1$sr_slavery_r.c
# s1$esr8.change.c <- s1$sr_change.c
# s1$esr9.deserve.c <- s1$sr_deserve_r.c
# s1$esr10.econ.c <- s1$sr_econ.c
```

```{r sre-clean-s1}
# EXTERNAL MODERN RACISM
# GROUP ITEMS ---------------------------
sre_vars_s1 <- dplyr::select(s1, c(sr_slavery_r, sr_change, sr_discrim_r, sr_deserve_r, sr_econ))
sre_vars.names_s1 <- names(sre_vars_s1)

sre_vars_s1.pass <- dplyr::select(s1.pass, c(sr_slavery_r, sr_change, sr_discrim_r, sr_deserve_r, sr_econ))
sre_vars.names_s1.pass <- names(sre_vars_s1.pass)

# CORRELATIONS ---------------------------
# correlation matrix
sre_cormat_s1 <- cor(sre_vars_s1, use = "complete.obs") 
sre_cormat_s1 <- round(sre_cormat_s1, 3)

# correlation plot with psych package
png(filename="/Users/cintiahinojosa/Box/Dissertation/images/sre_corplot_s1.png", height = 700, width = 1000)
psych::corPlot(sre_vars_s1 # labels = sre_vars.labels_s1
               , scale = TRUE, upper = FALSE, alpha = 0.5
               , main = "Correlation Matrix of External Modern Racism Items in Study 1") #stars = FALSE, 
dev.off()

# correlation plot with corrgram package
png(filename="/Users/cintiahinojosa/Box/Dissertation/images/sre_corrgram_s1.png", height = 700, width = 1000)
corrgram::corrgram(sre_vars_s1
         , main = "Correlation Matrix of External Modern Racism Items in Study 1 (Ordered)"
         , lower.panel = panel.cor #panel.cor, panel.pts, panel.conf
#         , upper.panel =  NULL #panel.conf #panel.shade #NULL
#         , diag.panel = panel.txt #panel.density, panel.minmax
         , text.panel = panel.txt
         , order = TRUE # "PCA" = TRUE
         , col.regions = colorRampPalette(c("red4", "grey", "darkgreen"))
           )
dev.off()

# CREATE MEAN COMPOSITE ---------------------------
freq(s1$sr_discrim_r)
s1$sre <- rowMeans(subset(s1, select = sre_vars.names_s1), na.rm = TRUE)
summary(s1$sre)
sre_alpha_s1 <- ltm::cronbach.alpha(sre_vars_s1)
papaja::printnum(sre_alpha_s1$alpha) # .788

# CREATE SUMMARY COMPOSITE ---------------------------
s1$sre.s <- rowSums(subset(s1, select = sre_vars.names_s1), na.rm = TRUE)
summary(s1$sre.s)

# GRAND-MEAN CENTER & STANDARDIZE ---------------------------
s1 <- s1 %>%
  mutate(sre.c = scale(sre, center = TRUE, scale = TRUE)
         , sre.sc = scale(sre.s, center = TRUE, scale = TRUE)
         )
summary(s1$sre.c)
summary(s1$sre.sc)

# GROUP STANDARDIZED ITEMS ---------------------------
sre.c_vars_s1 <- dplyr::select(s1, sr_slavery_r.c, sr_change.c, sr_discrim_r.c, sr_deserve_r.c, sr_econ.c)
sre.c_vars.names_s1 <- names(sre.c_vars_s1)
sre.c_alpha_s1 <- ltm::cronbach.alpha(sre.c_vars_s1)
papaja::printnum(sre.c_alpha_s1$alpha) # .791
```

```{r sri-clean-s1}
# INTERNAL MODERN RACISM
# GROUP ITEMS ---------------------------
sri_vars_s1 <- dplyr::select(s1, c(sr_hard, sr_minorities, sr_demand, sr_complain_r, sr_tension))
sri_vars.names_s1 <- names(sri_vars_s1)

# CORRELATIONS
# correlation matrix
sri_cormat_s1 <- cor(sri_vars_s1, use = "complete.obs") 
sri_cormat_s1 <- round(sri_cormat_s1, 3)

# correlation plot with psych package
png(filename="/Users/cintiahinojosa/Box/Dissertation/images/sri_corplot_s1.png", height = 700, width = 1000)
psych::corPlot(sri_vars_s1 # labels = sri_vars.labels_s1
               , scale = TRUE, upper = FALSE, alpha = 0.5
               , main = "Correlation Matrix of Internal Modern Racism Items in Study 1") #stars = FALSE, 
dev.off()

# correlation plot with corrgram package
png(filename="/Users/cintiahinojosa/Box/Dissertation/images/sri_corrgram_s1.png", height = 700, width = 1000)
corrgram::corrgram(sri_vars_s1
         , main = "Correlation Matrix of Internal Modern Racism Items in Study 1 (Ordered)"
         , lower.panel = panel.cor #panel.cor, panel.pts, panel.conf
#         , upper.panel =  NULL #panel.conf #panel.shade #NULL
#         , diag.panel = panel.txt #panel.density, panel.minmax
         , text.panel = panel.txt
         , order = TRUE # "PCA" = TRUE
         , col.regions = colorRampPalette(c("red4", "grey", "darkgreen"))
           )
dev.off()

# CREATE MEAN COMPOSITE ---------------------------
freq(s1$sr_discrim_r)
s1$sri <- rowMeans(subset(s1, select = sri_vars.names_s1), na.rm = TRUE)
summary(s1$sri)
sri_alpha_s1 <- ltm::cronbach.alpha(sri_vars_s1) 
papaja::printnum(sri_alpha_s1$alpha) # 

# CREATE SUMMARY COMPOSITE ---------------------------
s1$sri.s <- rowSums(subset(s1, select = sri_vars.names_s1), na.rm = TRUE)
summary(s1$sri.s)

# GRAND-MEAN CENTER & STANDARDIZE ---------------------------
s1 <- s1 %>%
  mutate(
    sri.c = scale(sri, center = TRUE, scale = TRUE)
    , sri.sc = scale(sri.s, center = TRUE, scale = TRUE)
    )
summary(s1$sri.sc)

# GROUP STANDARDIZED ITEMS ---------------------------
sri.c_vars_s1 <- dplyr::select(s1, sr_hard.c, sr_minorities.c, sr_demand.c, sr_complain_r.c, sr_tension.c)
sri.c_vars.names_s1 <- names(sri.c_vars_s1)
sri.c_alpha_s1 <- ltm::cronbach.alpha(sri.c_vars_s1)
papaja::printnum(sri.c_alpha_s1$alpha) #
```

```{r gun4-clean-s1}
# URBAN GUN VIOLENCE STEREOTYPES
# GROUP ITEMS ---------------------------
gunbeliefs4_vars_s1 <- dplyr::select(s1, c(gun_street, gun_parent, gun_punish, gun_work))
gunbeliefs4_vars.names_s1 <- names(gunbeliefs4_vars_s1)

# CORRELATIONS
# correlation matrix
gunbeliefs4_cormat_s1 <- cor(gunbeliefs4_vars_s1, use = "complete.obs") 
gunbeliefs4_cormat_s1 <- round(gunbeliefs4_cormat_s1, 3)

# correlation plot with psych package
png(filename="/Users/cintiahinojosa/Box/Dissertation/images/gunbeliefs4_corplot_s1.png", height = 700, width = 1000)
psych::corPlot(gunbeliefs4_vars_s1 # labels = gunbeliefs4_vars.labels_s1
               , scale = TRUE, upper = FALSE, alpha = 0.5
               , main = "Correlation Matrix of Urban Gun Violence Attitudes in Study 1") #stars = FALSE, 
dev.off()

# correlation plot with corrgram package
png(filename="/Users/cintiahinojosa/Box/Dissertation/images/gunbeliefs4_corrgram_s1.png", height = 700, width = 1000)
corrgram::corrgram(gunbeliefs4_vars_s1
         , main = "Correlation Matrix of Urban Gun Violence Attitudes in Study 1 (Ordered)"
         , lower.panel = panel.cor #panel.cor, panel.pts, panel.conf
#         , upper.panel =  NULL #panel.conf #panel.shade #NULL
#         , diag.panel = panel.txt #panel.density, panel.minmax
         , text.panel = panel.txt
         , order = TRUE # "PCA" = TRUE
         , col.regions = colorRampPalette(c("red4", "grey", "darkgreen"))
           )
dev.off()

# CREATE COMPOSITE ---------------------------
freq(s1$gun_street)
s1$gunbeliefs4 <- rowMeans(subset(s1, select = gunbeliefs4_vars.names_s1), na.rm = TRUE)
summary(s1$gunbeliefs4)
gunbeliefs4_alpha_s1 <- ltm::cronbach.alpha(gunbeliefs4_vars_s1) 
papaja::printnum(gunbeliefs4_alpha_s1$alpha) # 

# GRAND-MEAN CENTER & STANDARDIZE ---------------------------
s1 <- s1 %>%
  mutate(gunbeliefs4.c = scale(gunbeliefs4, center = TRUE, scale = TRUE)
         , gun_street.c = scale(gun_street, center = TRUE, scale = TRUE)
         , gun_parent.c = scale(gun_parent, center = TRUE, scale = TRUE)
         , gun_punish.c = scale(gun_punish, center = TRUE, scale = TRUE)
         , gun_work.c = scale(gun_work, center = TRUE, scale = TRUE)
         )
summary(s1$gunbeliefs4.c)
summary(s1$gun_street.c)

# GROUP STANDARDIZED ITEMS ---------------------------
gunbeliefs4.c_vars_s1 <- dplyr::select(s1, gun_street.c, gun_parent.c, gun_punish.c, gun_work.c)
gunbeliefs4.c_vars.names_s1 <- names(gunbeliefs4.c_vars_s1)
gunbeliefs4.c_alpha_s1 <- ltm::cronbach.alpha(gunbeliefs4.c_vars_s1)
papaja::printnum(gunbeliefs4.c_alpha_s1$alpha) #
```

```{r gun-clean-s1}
# URBAN GUN VIOLENCE STEREOTYPES
# GROUP ITEMS ---------------------------
gunbeliefs_vars_s1 <- dplyr::select(s1, c(gun_street, gun_parent, gun_punish))
gunbeliefs_vars.names_s1 <- names(gunbeliefs_vars_s1)

# CORRELATIONS
# correlation matrix
gunbeliefs_cormat_s1 <- cor(gunbeliefs_vars_s1, use = "complete.obs") 
gunbeliefs_cormat_s1 <- round(gunbeliefs_cormat_s1, 3)

# correlation plot with psych package
png(filename="/Users/cintiahinojosa/Box/Dissertation/images/gunbeliefs_corplot_s1.png", height = 700, width = 1000)
psych::corPlot(gunbeliefs_vars_s1 # labels = gunbeliefs_vars.labels_s1
               , scale = TRUE, upper = FALSE, alpha = 0.5
               , main = "Correlation Matrix of Urban Gun Violence Attitudes in Study 1") #stars = FALSE, 
dev.off()

# correlation plot with corrgram package
png(filename="/Users/cintiahinojosa/Box/Dissertation/images/gunbeliefs_corrgram_s1.png", height = 700, width = 1000)
corrgram::corrgram(gunbeliefs_vars_s1
         , main = "Correlation Matrix of Urban Gun Violence Attitudes in Study 1 (Ordered)"
         , lower.panel = panel.cor #panel.cor, panel.pts, panel.conf
#         , upper.panel =  NULL #panel.conf #panel.shade #NULL
#         , diag.panel = panel.txt #panel.density, panel.minmax
         , text.panel = panel.txt
         , order = TRUE # "PCA" = TRUE
         , col.regions = colorRampPalette(c("red4", "grey", "darkgreen"))
           )
dev.off()

# CREATE COMPOSITE ---------------------------
freq(s1$gun_street)
s1$gunbeliefs <- rowMeans(subset(s1, select = gunbeliefs_vars.names_s1), na.rm = TRUE)
summary(s1$gunbeliefs)
gunbeliefs_alpha_s1 <- ltm::cronbach.alpha(gunbeliefs_vars_s1) 
papaja::printnum(gunbeliefs_alpha_s1$alpha) # 

# GRAND-MEAN CENTER & STANDARDIZE ---------------------------
s1 <- s1 %>%
  mutate(gunbeliefs.c = scale(gunbeliefs, center = TRUE, scale = TRUE))
summary(s1$gunbeliefs.c)

# GROUP STANDARDIZED ITEMS ---------------------------
gunbeliefs.c_vars_s1 <- dplyr::select(s1, gun_street.c, gun_parent.c, gun_punish.c)
gunbeliefs.c_vars.names_s1 <- names(gunbeliefs.c_vars_s1)
gunbeliefs.c_alpha_s1 <- ltm::cronbach.alpha(gunbeliefs.c_vars_s1)
papaja::printnum(gunbeliefs.c_alpha_s1$alpha) #
```

### Exploratory {-}

```{r antiblack-clean-s1}
# ANTI-BLACK ATTITUDES
# GROUP ITEMS ---------------------------
antiblack_vars_s1 <- dplyr::select(s1, c(lazy_black, viol_black))
antiblack_vars.names_s1 <- names(antiblack_vars_s1)

# CORRELATIONS ---------------------------
# correlation matrix
antiblack_cormat_s1 <- cor(antiblack_vars_s1, use = "complete.obs") 
antiblack_cormat_s1 <- round(antiblack_cormat_s1, 3)

# correlation plot with psych package
png(filename="/Users/cintiahinojosa/Box/Dissertation/images/antiblack_corplot_s1.png", height = 700, width = 1000)
psych::corPlot(antiblack_vars_s1 # labels = antiblack_vars.labels_s1
               , scale = TRUE, upper = FALSE, alpha = 0.5
               , main = "Correlation Matrix of Anti-Black Attitudes in Study 1") #stars = FALSE, 
dev.off()

# correlation plot with corrgram package
png(filename="/Users/cintiahinojosa/Box/Dissertation/images/antiblack_corrgram_s1.png", height = 700, width = 1000)
corrgram::corrgram(antiblack_vars_s1
         , main = "Correlation Matrix of Anti-Black Attitudes in Study 1 (Ordered)"
         , lower.panel = panel.cor #panel.cor, panel.pts, panel.conf
#         , upper.panel =  NULL #panel.conf #panel.shade #NULL
#         , diag.panel = panel.txt #panel.density, panel.minmax
         , text.panel = panel.txt
         , order = TRUE # "PCA" = TRUE
         , col.regions = colorRampPalette(c("red4", "grey", "darkgreen"))
           )
dev.off()

# CREATE COMPOSITE ---------------------------
freq(s1$lazy_black)
s1$antiblack <- rowMeans(subset(s1, select = antiblack_vars.names_s1), na.rm = TRUE)
summary(s1$antiblack)
antiblack_alpha_s1 <- ltm::cronbach.alpha(antiblack_vars_s1) 
papaja::printnum(antiblack_alpha_s1$alpha) # 

# GRAND-MEAN CENTER & STANDARDIZE ---------------------------
s1 <- s1 %>%
  mutate(antiblack.c = scale(antiblack, center = TRUE, scale = TRUE)
         , lazy_black.c = scale(lazy_black, center = TRUE, scale = TRUE)
         , viol_black.c = scale(viol_black, center = TRUE, scale = TRUE)
         )
summary(s1$antiblack.c)

# GROUP STANDARDIZED ITEMS ---------------------------
antiblack.c_vars_s1 <- dplyr::select(s1, lazy_black.c, viol_black.c)
antiblack.c_vars.names_s1 <- names(antiblack.c_vars_s1)
antiblack.c_alpha_s1 <- ltm::cronbach.alpha(antiblack.c_vars_s1)
papaja::printnum(antiblack.c_alpha_s1$alpha) #
```

```{r antihispanic-clean-s1}
# ANTI-LATINO ATTITUDES
# GROUP ITEMS ---------------------------
antihispanic_vars_s1 <- dplyr::select(s1, c(lazy_hispanic, viol_hispanic))
antihispanic_vars.names_s1 <- names(antihispanic_vars_s1)

# CORRELATIONS ---------------------------
# correlation matrix
antihispanic_cormat_s1 <- cor(antihispanic_vars_s1, use = "complete.obs") 
antihispanic_cormat_s1 <- round(antihispanic_cormat_s1, 3)

# correlation plot with psych package
png(filename="/Users/cintiahinojosa/Box/Dissertation/images/antihispanic_corplot_s1.png", height = 700, width = 1000)
psych::corPlot(antihispanic_vars_s1 # labels = antihispanic_vars.labels_s1
               , scale = TRUE, upper = FALSE, alpha = 0.5
               , main = "Correlation Matrix of Anti-Hispanic Attitudes in Study 1") #stars = FALSE, 
dev.off()

# correlation plot with corrgram package
png(filename="/Users/cintiahinojosa/Box/Dissertation/images/antihispanic_corrgram_s1.png", height = 700, width = 1000)
corrgram::corrgram(antihispanic_vars_s1
         , main = "Correlation Matrix of Anti-Hispanic Attitudes in Study 1 (Ordered)"
         , lower.panel = panel.cor #panel.cor, panel.pts, panel.conf
#         , upper.panel =  NULL #panel.conf #panel.shade #NULL
#         , diag.panel = panel.txt #panel.density, panel.minmax
         , text.panel = panel.txt
         , order = TRUE # "PCA" = TRUE
         , col.regions = colorRampPalette(c("red4", "grey", "darkgreen"))
           )
dev.off()

# CREATE COMPOSITE ---------------------------
freq(s1$lazy_hispanic)
s1$antihispanic <- rowMeans(subset(s1, select = antihispanic_vars.names_s1), na.rm = TRUE)
summary(s1$antihispanic)
antihispanic_alpha_s1 <- ltm::cronbach.alpha(antihispanic_vars_s1) 
papaja::printnum(antihispanic_alpha_s1$alpha) # 

# GRAND-MEAN CENTER & STANDARDIZE ---------------------------
s1 <- s1 %>%
  mutate(antihispanic.c = scale(antihispanic, center = TRUE, scale = TRUE)
         , lazy_hispanic.c = scale(lazy_hispanic, center = TRUE, scale = TRUE)
         , viol_hispanic.c = scale(viol_hispanic, center = TRUE, scale = TRUE)
                  )
summary(s1$antihispanic.c)

# GROUP STANDARDIZED ITEMS ---------------------------
antihispanic.c_vars_s1 <- dplyr::select(s1, lazy_hispanic.c, viol_hispanic.c)
antihispanic.c_vars.names_s1 <- names(antihispanic.c_vars_s1)
antihispanic.c_alpha_s1 <- ltm::cronbach.alpha(antihispanic.c_vars_s1)
papaja::printnum(antihispanic.c_alpha_s1$alpha) #
```

```{r antiwhite-clean-s1}
# ANTI-WHITE ATTITUDES
# GROUP ITEMS ---------------------------
antiwhite_vars_s1 <- dplyr::select(s1, c(lazy_white, viol_white))
antiwhite_vars.names_s1 <- names(antiwhite_vars_s1)

# CORRELATIONS ---------------------------
# correlation matrix
antiwhite_cormat_s1 <- cor(antiwhite_vars_s1, use = "complete.obs") 
antiwhite_cormat_s1 <- round(antiwhite_cormat_s1, 3)

# correlation plot with psych package
png(filename="/Users/cintiahinojosa/Box/Dissertation/images/antiwhite_corplot_s1.png", height = 700, width = 1000)
psych::corPlot(antiwhite_vars_s1 # labels = antiwhite_vars.labels_s1
               , scale = TRUE, upper = FALSE, alpha = 0.5
               , main = "Correlation Matrix of Anti-White Attitudes in Study 1") #stars = FALSE, 
dev.off()

# correlation plot with corrgram package
png(filename="/Users/cintiahinojosa/Box/Dissertation/images/antiwhite_corrgram_s1.png", height = 700, width = 1000)
corrgram::corrgram(antiwhite_vars_s1
         , main = "Correlation Matrix of Anti-White Attitudes in Study 1 (Ordered)"
         , lower.panel = panel.cor #panel.cor, panel.pts, panel.conf
#         , upper.panel =  NULL #panel.conf #panel.shade #NULL
#         , diag.panel = panel.txt #panel.density, panel.minmax
         , text.panel = panel.txt
         , order = TRUE # "PCA" = TRUE
         , col.regions = colorRampPalette(c("red4", "grey", "darkgreen"))
           )
dev.off()

# CREATE COMPOSITE ---------------------------
freq(s1$lazy_white)
s1$antiwhite <- rowMeans(subset(s1, select = antiwhite_vars.names_s1), na.rm = TRUE)
summary(s1$antiwhite)
antiwhite_alpha_s1 <- ltm::cronbach.alpha(antiwhite_vars_s1) 
papaja::printnum(antiwhite_alpha_s1$alpha) # 

# GRAND-MEAN CENTER & STANDARDIZE ---------------------------
s1 <- s1 %>%
  mutate(antiwhite.c = scale(antiwhite, center = TRUE, scale = TRUE)
         , lazy_white.c = scale(lazy_white, center = TRUE, scale = TRUE)
         , viol_white.c = scale(viol_white, center = TRUE, scale = TRUE)
         )
summary(s1$antiwhite.c)

# GROUP STANDARDIZED ITEMS ---------------------------
antiwhite.c_vars_s1 <- dplyr::select(s1, lazy_white.c, viol_white.c)
antiwhite.c_vars.names_s1 <- names(antiwhite.c_vars_s1)
antiwhite.c_alpha_s1 <- ltm::cronbach.alpha(antiwhite.c_vars_s1)
papaja::printnum(antiwhite.c_alpha_s1$alpha) #
```

```{r antiasian-clean-s1}
# ANTI-ASIAN ATTITUDES
# GROUP ITEMS ---------------------------
antiasian_vars_s1 <- dplyr::select(s1, c(lazy_asian, viol_asian))
antiasian_vars.names_s1 <- names(antiasian_vars_s1)

# CORRELATIONS ---------------------------
# correlation matrix
antiasian_cormat_s1 <- cor(antiasian_vars_s1, use = "complete.obs") 
antiasian_cormat_s1 <- round(antiasian_cormat_s1, 3)

# correlation plot with psych package
png(filename="/Users/cintiahinojosa/Box/Dissertation/images/antiasian_corplot_s1.png", height = 700, width = 1000)
psych::corPlot(antiasian_vars_s1 # labels = antiasian_vars.labels_s1
               , scale = TRUE, upper = FALSE, alpha = 0.5
               , main = "Correlation Matrix of Anti-Asian Attitudes in Study 1") #stars = FALSE, 
dev.off()

# correlation plot with corrgram package
png(filename="/Users/cintiahinojosa/Box/Dissertation/images/antiasian_corrgram_s1.png", height = 700, width = 1000)
corrgram::corrgram(antiasian_vars_s1
         , main = "Correlation Matrix of Anti-Asian Attitudes in Study 1 (Ordered)"
         , lower.panel = panel.cor #panel.cor, panel.pts, panel.conf
#         , upper.panel =  NULL #panel.conf #panel.shade #NULL
#         , diag.panel = panel.txt #panel.density, panel.minmax
         , text.panel = panel.txt
         , order = TRUE # "PCA" = TRUE
         , col.regions = colorRampPalette(c("red4", "grey", "darkgreen"))
           )
dev.off()

# CREATE COMPOSITE ---------------------------
freq(s1$lazy_asian)
s1$antiasian <- rowMeans(subset(s1, select = antiasian_vars.names_s1), na.rm = TRUE)
summary(s1$antiasian)
antiasian_alpha_s1 <- ltm::cronbach.alpha(antiasian_vars_s1) 
papaja::printnum(antiasian_alpha_s1$alpha) # 

# GRAND-MEAN CENTER & STANDARDIZE ---------------------------
s1 <- s1 %>%
  mutate(antiasian.c = scale(antiasian, center = TRUE, scale = TRUE)
         , lazy_asian.c = scale(lazy_asian, center = TRUE, scale = TRUE)
         , viol_asian.c = scale(viol_asian, center = TRUE, scale = TRUE)
         )
summary(s1$antiasian.c)

# GROUP STANDARDIZED ITEMS ---------------------------
antiasian.c_vars_s1 <- dplyr::select(s1, lazy_asian.c, viol_asian.c)
antiasian.c_vars.names_s1 <- names(antiasian.c_vars_s1)
antiasian.c_alpha_s1 <- ltm::cronbach.alpha(antiasian.c_vars_s1)
papaja::printnum(antiasian.c_alpha_s1$alpha) #
```


```{r lazy-clean-s1}
# NEGATIVE RACIAL ATTITUDES (LAZY)
# GROUP ITEMS ---------------------------
lazy_vars_s1 <- dplyr::select(s1, c(lazy_black, lazy_hispanic, lazy_asian, lazy_white))
lazy_vars.names_s1 <- names(lazy_vars_s1)

# CORRELATIONS ---------------------------
# correlation matrix
lazy_cormat_s1 <- cor(lazy_vars_s1, use = "complete.obs") 
lazy_cormat_s1 <- round(lazy_cormat_s1, 3)

# correlation plot with psych package
png(filename="/Users/cintiahinojosa/Box/Dissertation/images/lazy_corplot_s1.png", height = 700, width = 1000)
psych::corPlot(lazy_vars_s1 # labels = lazy_vars.labels_s1
               , scale = TRUE, upper = FALSE, alpha = 0.5
               , main = "Correlation Matrix of Negative Racial Attitudes (Lazy) in Study 1") #stars = FALSE, 
dev.off()

# correlation plot with corrgram package
png(filename="/Users/cintiahinojosa/Box/Dissertation/images/lazy_corrgram_s1.png", height = 700, width = 1000)
corrgram::corrgram(lazy_vars_s1
         , main = "Correlation Matrix of Negative Racial Attitudes (Lazy) in Study 1 (Ordered)"
         , lower.panel = panel.cor #panel.cor, panel.pts, panel.conf
#         , upper.panel =  NULL #panel.conf #panel.shade #NULL
#         , diag.panel = panel.txt #panel.density, panel.minmax
         , text.panel = panel.txt
         , order = TRUE # "PCA" = TRUE
         , col.regions = colorRampPalette(c("red4", "grey", "darkgreen"))
           )
dev.off()

# CREATE COMPOSITE ---------------------------
freq(s1$lazy_black)
s1$lazy <- rowMeans(subset(s1, select = lazy_vars.names_s1), na.rm = TRUE)
summary(s1$lazy)
lazy_alpha_s1 <- ltm::cronbach.alpha(lazy_vars_s1) 
papaja::printnum(lazy_alpha_s1$alpha) # 

# GRAND-MEAN CENTER & STANDARDIZE ---------------------------
s1 <- s1 %>%
  mutate(lazy.c = scale(lazy, center = TRUE, scale = TRUE))
summary(s1$lazy.c)

# GROUP STANDARDIZED ITEMS ---------------------------
lazy.c_vars_s1 <- dplyr::select(s1,lazy_black.c, lazy_hispanic.c, lazy_asian.c, lazy_white.c)
lazy.c_vars.names_s1 <- names(lazy.c_vars_s1)
lazy.c_alpha_s1 <- ltm::cronbach.alpha(lazy.c_vars_s1)
papaja::printnum(lazy.c_alpha_s1$alpha) #
```


```{r viol-clean-s1}
# NEGATIVE RACIAL ATTITUDES (VIOLENT)
# GROUP ITEMS ---------------------------
viol_vars_s1 <- dplyr::select(s1, c(viol_black, viol_hispanic, viol_asian, viol_white))
viol_vars.names_s1 <- names(viol_vars_s1)

# CORRELATIONS ---------------------------
# correlation matrix
viol_cormat_s1 <- cor(viol_vars_s1, use = "complete.obs") 
viol_cormat_s1 <- round(viol_cormat_s1, 3)

# correlation plot with psych package
png(filename="/Users/cintiahinojosa/Box/Dissertation/images/viol_corplot_s1.png", height = 700, width = 1000)
psych::corPlot(viol_vars_s1 # labels = viol_vars.labels_s1
               , scale = TRUE, upper = FALSE, alpha = 0.5
               , main = "Correlation Matrix of Negative Racial Attitudes (Violent) in Study 1") #stars = FALSE, 
dev.off()

# correlation plot with corrgram package
png(filename="/Users/cintiahinojosa/Box/Dissertation/images/viol_corrgram_s1.png", height = 700, width = 1000)
corrgram::corrgram(viol_vars_s1
         , main = "Correlation Matrix of Negative Racial Attitudes (Violent) in Study 1 (Ordered)"
         , lower.panel = panel.cor #panel.cor, panel.pts, panel.conf
#         , upper.panel =  NULL #panel.conf #panel.shade #NULL
#         , diag.panel = panel.txt #panel.density, panel.minmax
         , text.panel = panel.txt
         , order = TRUE # "PCA" = TRUE
         , col.regions = colorRampPalette(c("red4", "grey", "darkgreen"))
           )
dev.off()

# CREATE COMPOSITE ---------------------------
freq(s1$viol_black)
s1$viol <- rowMeans(subset(s1, select = viol_vars.names_s1), na.rm = TRUE)
summary(s1$viol)
viol_alpha_s1 <- ltm::cronbach.alpha(viol_vars_s1) 
papaja::printnum(viol_alpha_s1$alpha) # 

# GRAND-MEAN CENTER & STANDARDIZE ---------------------------
s1 <- s1 %>%
  mutate(viol.c = scale(viol, center = TRUE, scale = TRUE))
summary(s1$viol.c)

# GROUP STANDARDIZED ITEMS ---------------------------
viol.c_vars_s1 <- dplyr::select(s1,viol_black.c, viol_hispanic.c, viol_asian.c, viol_white.c)
viol.c_vars.names_s1 <- names(viol.c_vars_s1)
viol.c_alpha_s1 <- ltm::cronbach.alpha(viol.c_vars_s1)
papaja::printnum(viol.c_alpha_s1$alpha) #
```

```{r anti-clean-s1}
# NEGATIVE RACIAL ATTITUDES
# GROUP ITEMS ---------------------------
anti_vars_s1 <- dplyr::select(s1, c(lazy_black, viol_black, lazy_hispanic, viol_hispanic, lazy_asian, viol_asian, lazy_white, viol_white))
anti_vars.names_s1 <- names(anti_vars_s1)

# CORRELATIONS ---------------------------
# correlation matrix
anti_cormat_s1 <- cor(anti_vars_s1, use = "complete.obs") 
anti_cormat_s1 <- round(anti_cormat_s1, 3)

# correlation plot with psych package
png(filename="/Users/cintiahinojosa/Box/Dissertation/images/anti_corplot_s1.png", height = 700, width = 1000)
psych::corPlot(anti_vars_s1 # labels = anti_vars.labels_s1
               , scale = TRUE, upper = FALSE, alpha = 0.5
               , main = "Correlation Matrix of Negative Racial Attitudes in Study 1") #stars = FALSE, 
dev.off()

# correlation plot with corrgram package
png(filename="/Users/cintiahinojosa/Box/Dissertation/images/anti_corrgram_s1.png", height = 700, width = 1000)
corrgram::corrgram(anti_vars_s1
         , main = "Correlation Matrix of Negative Racial Attitudes in Study 1 (Ordered)"
         , lower.panel = panel.cor #panel.cor, panel.pts, panel.conf
#         , upper.panel =  NULL #panel.conf #panel.shade #NULL
#         , diag.panel = panel.txt #panel.density, panel.minmax
         , text.panel = panel.txt
         , order = TRUE # "PCA" = TRUE
         , col.regions = colorRampPalette(c("red4", "grey", "darkgreen"))
           )
dev.off()

# CREATE COMPOSITE ---------------------------
freq(s1$lazy_black)
s1$anti <- rowMeans(subset(s1, select = anti_vars.names_s1), na.rm = TRUE)
summary(s1$anti)
anti_alpha_s1 <- ltm::cronbach.alpha(anti_vars_s1) 
papaja::printnum(anti_alpha_s1$alpha) # 

# GRAND-MEAN CENTER & STANDARDIZE ---------------------------
s1 <- s1 %>%
  mutate(anti.c = scale(anti, center = TRUE, scale = TRUE))
summary(s1$anti.c)

# GROUP STANDARDIZED ITEMS ---------------------------
anti.c_vars_s1 <- dplyr::select(s1,lazy_black.c, viol_black.c, lazy_hispanic.c, viol_hispanic.c, lazy_asian.c, viol_asian.c, lazy_white.c, viol_white.c)
anti.c_vars.names_s1 <- names(anti.c_vars_s1)
anti.c_alpha_s1 <- ltm::cronbach.alpha(anti.c_vars_s1)
papaja::printnum(anti.c_alpha_s1$alpha) #.84
```

```{r fed-clean-s1, eval = FALSE}
# ATTITUDES TOWARDS FEDERAL AID  

# fed_reg: "1=""Government regulation is necessary to protect the public interest"" 
# fed_reg: 0=""Government regulation usually does more harm than good"""

# fed_probs: "The government should do more to solve problems"
# fed_probs: (1), "The government is doing too many things. It's better left to individuals."  (0) 

# fed_aid: "Government aid to the poor does more harm than good by making people too dependent on government assistance"  (0)
# fed_aid: "Government aid to the poor does more good than harm because people can't get out of poverty until their needs are met"  (1)

# fed_needy: "The government should do more to help needy Americans, even if it means going deeper into debt"  (1)
# fed_needy: "The government today can't afford to do much more to help the needy"  (0) 

# FACTOR VARS ---------------------------
s1$fed_reg.f <- factor(s1$fed_reg, levels = 0:1, labels = c("Gov reg does more harm", "Gov reg is necessary"), ordered = TRUE)
s1$fed_probs.f <- factor(s1$fed_probs, levels = 0:1, labels = c("Better left to individuals","Gov should do more"), ordered = TRUE)
s1$fed_aid.f <- factor(s1$fed_aid, levels = 0:1, labels = c("Gov aid does more harm","Gov aid does more good"), ordered = TRUE)
s1$fed_needy.f <- factor(s1$fed_needy, levels = 0:1, labels = c("Gov can't afford to help more", "Gov should help the needy more"), ordered = TRUE)

# GROUP ITEMS ---------------------------
fed_vars_s1 <- dplyr::select(s1, c(fed_reg, fed_probs, fed_aid, fed_needy))
fed_vars.names_s1 <- names(fed_vars_s1)

fed.f_vars_s1 <- dplyr::select(s1, fed_reg.f, fed_probs.f, fed_aid.f, fed_needy.f)
fed.f_vars.names_s1 <- names(fed.f_vars_s1)

# CORRELATIONS ---------------------------
# correlation matrix
fed_cormat_s1 <- cor(fed_vars_s1, use = "complete.obs") 
fed_cormat_s1 <- round(fed_cormat_s1, 3)

# correlation plot with psych package
png(filename="/Users/cintiahinojosa/Box/Booth PhD/Gun Violence Dissertation/dissertation-book/images/fed_corplot_s1.png", height = 700, width = 1000)
psych::corPlot(fed_vars_s1 # labels = fed_vars.labels_s1
               , scale = TRUE, upper = FALSE, alpha = 0.5
               , main = "Correlation Matrix of Restorative Federal Policy Attitudes in Study 1") #stars = FALSE, 
dev.off()

# correlation plot with corrgram package
png(filename="/Users/cintiahinojosa/Box/Booth PhD/Gun Violence Dissertation/dissertation-book/images/fed_corrgram_s1.png", height = 700, width = 1000)
corrgram::corrgram(fed_vars_s1
         , main = "Correlation Matrix of Restorative Federal Policy Attitudes in Study 1 (Ordered)"
         , lower.panel = panel.cor #panel.cor, panel.pts, panel.conf
#         , upper.panel =  NULL #panel.conf #panel.shade #NULL
#         , diag.panel = panel.txt #panel.density, panel.minmax
         , text.panel = panel.txt
         , order = TRUE # "PCA" = TRUE
         , col.regions = colorRampPalette(c("red4", "grey", "darkgreen"))
           )
dev.off()

# CREATE COMPOSITE ---------------------------
freq(s1$fed_reg)
s1$fed <- rowMeans(subset(s1, select = fed_vars.names_s1), na.rm = TRUE)
summary(s1$fed)
fed_alpha_s1 <- ltm::cronbach.alpha(fed_vars_s1) 
papaja::printnum(fed_alpha_s1$alpha) # .70
```

```{r drug-clean-s1}
# PUNITIVE DRUG POLICY ATTITUDES

# prison: Some states have moved away from mandatory prison sentences for non-violent drug crimes. Is this a good or a bad thing? (1=good; 2=bad) 
  # prison: 1 = stopping is a good thing N=580 (restorative)
  # prison: 2 = stopping is a bad thing N=162 (punitive)

# drug_prison: Mandatory prison sentences for non-violent drug crimes (1=bad; 2=good) 
# drug_prison = "Mandatory prison for non-violent drug crimes"
  # drug_prison: 1 = stopping is a bad thing N=162 (punitive)
  # drug_prison: 2 = stopping is a good thing N=580 (restorative)

# drug_policy: On drug policies, the government should focus more on 
  # drug_policy: 1 = prosecuting (punitive)
  # drug_policy: 2 = treating (restorative)

# drug_prosecute = "Drug policies should focus more on prosecuting" (1=yes;0=no)
# drug_treat = "Drug policies should focus more on treating" (1=yes;0=no)

# RECODE ---------------------------
# 1 = punitive towards drugs; 2 = restorative towards drugs
# note: recoding prison to drug_prison with swapped answers to remove double negative

# drug_prison = "Mandatory prison for non-violent drug crimes"
s1$drug_prison = s1$prison # rename to match drug_policy format (if not in raw-s1 chunk)
s1$drug_prison[s1$prison == 1] <- 2 # change to bad (restorative)
s1$drug_prison[s1$prison == 2] <- 1 # change to good (punitive)
freq(s1$drug_prison)

# create binary variables
s1$drug_prisongood = s1$drug_prison
s1$drug_prisongood[s1$drug_prison == 1] <- 1 # (punitive)
s1$drug_prisongood[s1$drug_prison == 2] <- 0 # (restorative)
freq(s1$drug_prisongood)

s1$drug_prisonbad = s1$drug_prison
s1$drug_prisonbad[s1$drug_prison == 1] <- 0 # (restorative)
s1$drug_prisonbad[s1$drug_prison == 2] <- 1 # (punitive)
freq(s1$drug_prisonbad)

# drug_policy: On drug policies, the government should focus more on 
s1$drug_policy.f <- factor(s1$drug_policy, levels = 1:2, labels = c("Prosecuting drug users", "Treating drug users"), ordered = FALSE)
freq(s1$drug_policy.f)

# create binary variables
s1$drug_prosecute = s1$drug_policy
s1$drug_prosecute[s1$drug_policy == 1] <- 1 # keep as prosecuting (punitive)
s1$drug_prosecute[s1$drug_policy == 2] <- 0 # keep as treating (restorative)
freq(s1$drug_prosecute)

s1$drug_treat = s1$drug_policy
s1$drug_treat[s1$drug_policy == 1] <- 0 # prosecuting 
s1$drug_treat[s1$drug_policy == 2] <- 1 # treating 
freq(s1$drug_treat)

# FACTOR VARS ---------------------------
s1$drug_prison.f <- factor(s1$drug_prison, levels = 1:2, labels = c("Good", "Bad"), ordered = FALSE) 
freq(s1$drug_prison.f)

s1$drug_prisongood.f <- factor(s1$drug_prisongood, levels = 0:1, labels = c("No", "Yes"), ordered = FALSE)
freq(s1$drug_prisongood.f)

s1$drug_prisonbad.f <- factor(s1$drug_prisonbad, levels = 0:1, labels = c("No", "Yes"), ordered = FALSE)
freq(s1$drug_prisonbad.f)

s1$drug_prosecute.f <- factor(s1$drug_prosecute, levels = 0:1, labels = c("Treating drug users", "Prosecuting drug users"), ordered = FALSE)
freq(s1$drug_prosecute.f)

s1$drug_treat.f <- factor(s1$drug_treat, levels = 0:1, labels = c("Prosecuting drug users", "Treating drug users"), ordered = FALSE)
freq(s1$drug_treat.f)

# GROUP ITEMS ---------------------------
drug_vars_s1 <- dplyr::select(s1, c(drug_prisonbad, drug_prosecute)) #drug_prison, drug_prisongood, drug_policy, drug_treat
drug_vars.names_s1 <- names(drug_vars_s1)

drug.f_vars_s1 <- dplyr::select(s1, c(drug_prisonbad.f, drug_prosecute.f)) #drug_prison.f, drug_prisongood.f, drug_policy.f, drug_treat.f
drug.f_vars.names_s1 <- names(drug.f_vars_s1)

# CORRELATIONS ---------------------------
# correlation matrix # -.37
drug_cormat_s1 <- cor(drug_vars_s1, use = "complete.obs") 
drug_cormat_s1 <- round(drug_cormat_s1, 3)

# correlation plot with psych package
png(filename="/Users/cintiahinojosa/Box/Booth PhD/Gun Violence Dissertation/dissertation-book/images/drug_corplot_s1.png", height = 700, width = 1000)
psych::corPlot(drug_vars_s1 # labels = drug_vars.labels_s1
               , scale = TRUE, upper = FALSE, alpha = 0.5
               , main = "Correlation Matrix of Punitive Drug Policy Attitudes in Study 1") #stars = FALSE, 
dev.off()

# correlation plot with corrgram package
png(filename="/Users/cintiahinojosa/Box/Booth PhD/Gun Violence Dissertation/dissertation-book/images/drug_corrgram_s1.png", height = 700, width = 1000)
corrgram::corrgram(drug_vars_s1
         , main = "Correlation Matrix of Punitive Drug Policy Attitudes in Study 1 (Ordered)"
         , lower.panel = panel.cor #panel.cor, panel.pts, panel.conf
#         , upper.panel =  NULL #panel.conf #panel.shade #NULL
#         , diag.panel = panel.txt #panel.density, panel.minmax
         , text.panel = panel.txt
         , order = TRUE # "PCA" = TRUE
         , col.regions = colorRampPalette(c("red4", "grey", "darkgreen"))
           )
dev.off()

# CREATE COMPOSITE ---------------------------
freq(s1$drug_prisonbad)
s1$drug <- rowMeans(subset(s1, select = drug_vars.names_s1), na.rm = TRUE)
summary(s1$drug)
drug_alpha_s1 <- ltm::cronbach.alpha(drug_vars_s1) 
papaja::printnum(drug_alpha_s1$alpha) # -1.18
```



## SAVE VALUES {-}


```{r labels-s1, eval = TRUE}
# IV LABELS ---------------------------
s1 = expss::apply_labels(s1
     , condition = "Condition"
     , condition.n = "Condition"
     , condition.f = "Condition"
     , critical = "Critical"
     , naive = "Naive"
     , condition.f = "Condition"
     , race = "Racial/ethnic Identity"
     , race.n = "Racial/ethnic identity"
     , race.f = "Racial/ethnic identity"
     , race_multi = "Racial/ethnic identity"
     , race_multi.n = "Multi racial/ethnic"
     , race_multi.f = "Multi racial/ethnic"
     , age = "Age"
     , race.f = "Racial/ethnic Identity"
     , gender = "Gender"
     , female = "Female"
     , male = "Male"
     , nonbinary = "Non-binary"
     , gender.n = "Gender"
     , gender.f = "Gender"
     , nonbinary.f = "Non-binary"
     , edu.f = "Education"
     , edu.n = "Education"
     , edu3 = "Education"
     , edu3.n = "Education"
     , edu3.f = "Education"
     , edu_other = "Education"
     , nocollege = "No college degree"
     , nocollege.f = "No college degree"
     , college = "College degree"
     , college.f = "College degree"
     , grad = "Graduate degree"
     , grad.f = "Graduate degree"
     , political = "Political orientation"
     , political.n = "Political orientation"
     , political.f = "Political orientation"
     , political3 = "Political orientation"
     , political3.n = "Political orientation"
     , political3.f = "Political orientation"
     , party = "Political party"
     , party.f = "Political party"
     , party_other_text = "Political party (other)"
     , edu = "Education"
     , edu3 = "Education"
     , edu3.f = "Education"
     , edu_other_text = "Education (Other)"
     , duration = "Study duration (mins)"
     , income.f = "Income"
     , adj_income = "Adj. Income"
     , adj_income.c = "Adj. Income"
)

# DV LABELS ---------------------------
s1 = expss::apply_labels(s1
     , punitive = "Punitive Policy Support"
     , pun_cops = "More police on the streets"
     , pun_jailtime = "Longer jail terms for those convicted of violent crimes"
     , pun_prisons = "More prisons and fewer opportunities for parole"
     , pun_penalty = "Increase criminal penalties for non-violent crimes"
     , punitive.c = "Punitive Policy Support"
     , pun_cops.c = "More police on the streets"
     , pun_jailtime.c = "Longer jail terms for those convicted of violent crimes"
     , pun_penalty.c = "Increase criminal penalties for non-violent crimes"
     , pun_jailtime.f = "Longer jail terms for those convicted of violent crimes"
     , pun_prisons.c = "More prisons and fewer opportunities for parole"
     , pun_cops.f = "More police on the streets"
     , pun_prisons.f = "More prisons and fewer opportunities for parole"
     , pun_penalty.f = "Increase criminal penalties for non-violent crimes"
     , restorative = "Restorative Policy Support"
     , rest_youth = "More community programs for young people"
     , rest_jobs = "Job programs for people in the inner-cities"
     , rest_banbox = "Remove criminal-history questions from employment applications"
     , rest_fedaid = "More federal assistance to the poor"
     , restorative.c = "Restorative Policy Support"
     , rest_youth.c = "More community programs for young people"
     , rest_jobs.c = "Job programs for people in the inner-cities"
     , rest_banbox.c = "Remove criminal-history questions from employment applications"
     , rest_fedaid.c = "More federal assistance to the poor"
     , rest_youth.f = "More community programs for young people"
     , rest_jobs.f = "Job programs for people in the inner-cities"
     , rest_banbox.f = "Remove criminal-history questions from employment applications"
     , rest_fedaid.f = "More federal assistance to the poor"
     , sr = "Symbolic Racism"
     , sr.s = "Symbolic Racism"
     , sr.c = "Symbolic Racism"
     , sr.sc = "Symbolic Racism"
     , sri = "Internal Symbolic Racism"
     , sri.s = "Internal Symbolic Racism"
     , sri.c = "Internal Symbolic Racism"
     , sri.sc = "Internal Symbolic Racism"
     , sre = "External Symbolic Racism"
     , sre.s = "External Symbolic Racism"
     , sre.c = "External Symbolic Racism"
     , sre.sc = "External Symbolic Racism"
     , sr_hard = "It's really a matter of some people not trying hard enough; if Black people would only try harder, they could be just as well off as whites."
     , sr_minorities = "Irish, Italian, Jewish, and many other minorities overcame
    prejudice and worked their way up. Black people should do the same."
     , sr_demand = "Black people are demanding too much from the rest of society."
     , sr_complain_r = "Black people generally do not complain as much as they should about their situation in society. (R)"
     , sr_slavery_r = "Generations of slavery and discrimination have created conditions that make it difficult for Black people to work their way out of the lower class. (R)"
     , sr_deserve_r = "Over the past few years, Black people have gotten less than they deserve. (R)"
     , sr_econ = "Over the past few years, Black people have gotten more economically than they deserve."
     , sr_tension = "How much of the racial tension that exists in the United States today do you think Black people are responsible for creating?"
     , sr_discrim_r = "How much discrimination against Black people do you feel there is in the United States today, limiting their chances to get ahead? (R)"
     , sr_change = "Has there been a lot of real change in the position of Black people in the past few years?"
     , sr_hard.c = "It's really a matter of some people not trying hard enough; if Black people would only try harder, they could be just as well off as whites."
     , sr_minorities.c = "Irish, Italian, Jewish, and many other minorities overcame
    prejudice and worked their way up. Black people should do the same."
     , sr_demand.c = "Black people are demanding too much from the rest of society."
     , sr_complain_r.c = "Black people generally do not complain as much as they should about their situation in society. (R)"
     , sr_slavery_r.c = "Generations of slavery and discrimination have created conditions that make it difficult for Black people to work their way out of the lower class. (R)"
     , sr_deserve_r.c = "Over the past few years, Black people have gotten less than they deserve. (R)"
     , sr_econ.c = "Over the past few years, Black people have gotten more economically than they deserve."
     , sr_tension.c = "How much of the racial tension that exists in the United States today do you think Black people are responsible for creating?"
     , sr_discrim_r.c = "How much discrimination against Black people do you feel there is in the United States today, limiting their chances to get ahead? (R)"
     , sr_change.c = "Has there been a lot of real change in the position of Black people in the past few years?"
     , sr_hard.f = "It's really a matter of some people not trying hard enough; if Black people would only try harder, they could be just as well off as whites."
     , sr_minorities.f = "Irish, Italian, Jewish, and many other minorities overcame
    prejudice and worked their way up. Black people should do the same."
     , sr_demand.f = "Black people are demanding too much from the rest of society."
     , sr_complain_r.f = "Black people generally do not complain as much as they should about their situation in society. (R)"
     , sr_slavery_r.f = "Generations of slavery and discrimination have created conditions that make it difficult for Black people to work their way out of the lower class. (R)"
     , sr_deserve_r.f = "Over the past few years, Black people have gotten less than they deserve. (R)"
     , sr_econ.f = "Over the past few years, Black people have gotten more economically than they deserve."
     , sr_tension.f = "How much of the racial tension that exists in the United States today do you think Black people are responsible for creating?"
     , sr_discrim_r.f = "How much discrimination against Black people do you feel there is in the United States today, limiting their chances to get ahead? (R)"
     , sr_change.f = "Has there been a lot of real change in the position of Black people in the past few years?"
     , gunbeliefs4 = "Stereotypes about Urban Gun Violence"
     , gunbeliefs = "Stereotypes about Urban Gun Violence"
     , gunbeliefs4.c = "Stereotypes about Urban Gun Violence"
     , gunbeliefs.c = "Stereotypes about Urban Gun Violence"
     , gun_parent = "We wouldn’t have so much gun violence in poor inner-city neighborhoods if the kids doing the shooting had parents who took responsibility for raising them"
     , gun_street = "Gun violence in poor inner-city neighborhoods won’t improve unless we get the criminals who are doing the shooting off the streets for good"
     , gun_work = "If we could get violent criminals off the streets of poor inner-city neighborhoods, the decent, hard-working people in those neighborhoods could lift themselves out of poverty"
     , gun_punish = "If the people doing the shooting in poor inner-city neighborhoods knew they would be caught and severely punished, we’d see a lot less gun violence in those neighborhoods"
     , gun_parent.c = "Lack of parent responsibility"
     , gun_street.c = "Get criminals off the streets for good"
     , gun_work.c = "Decent people can lift themselves out of poverty \n if criminals were off the streets"
     , gun_punish.c = "Criminals need to know they would be caught \n and severely punished"
     , viol = "Perceptions of Black, Latino, Asian, and White people as violent"
     , viol.c = "Perceptions of Black, Latino, Asian, and White people as violent"
     , lazy = "Perceptions of Black, Latino, Asian, and White people as lazy"
     , lazy.c = "Perceptions of Black, Latino, Asian, and White people as lazy"
     , anti = "Perceptions of Black, Latino, Asian, and White people as violent and lazy"
     , anti.c = "Perceptions of Black, Latino, Asian, and White people as violent and lazy"
     , antiblack = "Perceptions of Black people as violent and lazy"
     , antiblack.c = "Perceptions of Black people as violent and lazy"
     , antilatino = "Perceptions of Latino people as violent and lazy"
     , antilatino.c = "Perceptions of Latino people as violent and lazy"
     , antiasian = "Perceptions of Asian people as violent and lazy"
     , antiasian.c = "Perceptions of Asian people as violent and lazy"
     , antiwhite = "Perceptions of White people as violent and lazy"
     , antiwhite.c = "Perceptions of White people as violent and lazy"
     , lazy_black = "Perceptions of Black people as lazy"
     , lazy_black.c = "Perceptions of Black people as lazy"
     , viol_black = "Perceptions of Black people as violent"
     , viol_black.c = "Perceptions of Black people as violent"
     , lazy_latino = "Perceptions of Latino people as lazy"
     , lazy_latino.c = "Perceptions of Latino people as lazy"
     , viol_latino = "Perceptions of Latino people as violent"
     , viol_latino.c = "Perceptions of Latino people as violent"
     , lazy_asian = "Perceptions of Asian people as lazy"
     , lazy_asian.c = "Perceptions of Asian people as lazy"
     , viol_asian = "Perceptions of Asian people as violent"
     , viol_asian.c = "Perceptions of Asian people as violent"
     , lazy_white = "Perceptions of White people as lazy"
     , lazy_white.c = "Perceptions of White people as lazy"
     , viol_white = "Perceptions of White people as violent"
     , viol_white.c = "Perceptions of White people as violent"
     , fed = "Restorative Federal Policy Attitudes"
     , fed_reg = "Gov regulation necessary to protect public"
     , fed_probs = "Gov should do more to solve problems"
     , fed_aid = "Gov aid to poor does more good than harm"
     , fed_needy = "Gov should do more to help the needy"
     , fed_reg.f = "Gov regulation necessary to protect public"
     , fed_probs.f = "Gov should do more to solve problems"
     , fed_aid.f = "Gov aid to poor does more good than harm"
     , fed_needy.f = "Gov should do more to help the needy"
     , prison = "Some states have moved away from mandatory prison sentences for non-violent drug crimes. Is this a good or a bad thing?"
     , drug = "Punitive Drug Policy Attitudes"
     , drug_prison = "Mandatory prison for non-violent drug crimes"
     , drug_prison.f = "Mandatory prison for non-violent drug crimes"
     , drug_prisongood = "Favor mandatory prison for non-violent drug crimes"
     , drug_prisongood.f = "Favor mandatory prison for non-violent drug crimes"
     , drug_prisonbad = "Oppose mandatory prison for non-violent drug crimes"
     , drug_prisonbad.f = "Oppose mandatory prison for non-violent drug crimes"
     , drug_policy = "On drug policies, the government should focus more on..."
     , drug_policy.f = "On drug policies, the government should focus more on..."
     , drug_prosecute = "Drug policies should focus more on prosecuting"
     , drug_prosecute.f = "Drug policies should focus more on prosecuting"
     , drug_treat = "Drug policies should focus more on treating"
     , drug_treat.f = "Drug policies should focus more on treating"
    ) 
     # lazy, viol, lazy_RACE, viol_RACE
     # , isr1.hard = "(Int1) not trying hard enough"
     # , isr2.minorities = "(Int2) other minorities got over it" 
     # , isr3.demand = "(Int3) too demanding"
     # , isr4.tension = "(Int4) to blame for tension"
     # , isr5.complain = "(Int5) don't complain enough (R)"
     # , esr6.discrim = "(Ext6) discrimination today (R)"
     # , esr7.slavery = "(Ext7) slavery impacts today (R)"
     # , esr8.change = "(Ext8) recent change in position"
     # , esr9.deserve = "(Ext9) gotten less than deserved (R)"
     # , esr10.econ = "(Ext10) gotten more than deserved"
```

```{r fun-group-s1, eval = TRUE}
# GROUPED TABLE WITH P-VALUES
##################################
# create condition variable that has empty stratum
s1$group = NA
s1$group <- factor(s1$condition.n, levels = c(1,2,3), labels = c("Critical", "Control", "P-value"))

# function
rndr <- function(x, name, ...) {
    if (length(x) == 0) {
        y <- s1[[name]]
        s <- rep("", length(render.default(x = y, name = name, ...)))
        if (is.numeric(y)) {
            p <- t.test(y ~ s1$group)$p.value
        } else {
            p <- chisq.test(table(y, droplevels(s1$group)))$p.value
        }
        s[2] <- sub("<", "&lt;", format.pval(p, digits = 3, eps = 0.001))
        s
    } else {
        render.default(x = x, name = name, ...)
    }
}

rndr.strat <- function(label, n, ...) {
    ifelse(n == 0, label, render.strat.default(label, n, ...))
}

# individual & critical #
# create 2 level condition variable for each comparison
s1$condition.icrit = NA
s1$condition.icrit[s1$condition == "Individual"] <- "Individual"
s1$condition.icrit[s1$condition == "Critical"] <- "Critical"
s1$condition.icrit <- factor(s1$condition.icrit, exclude = NA)

# create condition variable that has empty stratum
s1$group.icrit    <- factor(as.numeric(s1$condition.icrit), levels = c(1,2,3), labels = c("Critical", "Individual", "P-value"))
##freq(s1$group)

# function
rndr.icrit <- function(x, name, ...) {
    if (length(x) == 0) {
        y <- s1[[name]]
        s <- rep("", length(render.default(x = y, name = name, ...)))
        if (is.numeric(y)) {
            p <- t.test(y ~ s1$group.icrit)$p.value
        } else {
            p <- chisq.test(table(y, droplevels(s1$group.icrit)))$p.value
        }
        s[2] <- sub("<", "&lt;", format.pval(p, digits = 3, eps = 0.001))
        s
    } else {
        render.default(x = x, name = name, ...)
    }
}


rndr.icrit.strat <- function(label, n, ...) {
    ifelse(n == 0, label, render.strat.default(label, n, ...))
}

# control & individual #
s1$condition.ci = NA
s1$condition.ci[s1$condition == "Control"] <- "Control"
s1$condition.ci[s1$condition == "Individual"] <- "Individual"
s1$condition.ci <- factor(s1$condition.ci, exclude = NA)

s1$group.ci    <- factor(as.numeric(s1$condition.ci), levels = c(1,2,3), labels = c("Control", "Individual", "P-value"))

rndr.ci <- function(x, name, ...) {
    if (length(x) == 0) {
        y <- s1[[name]]
        s <- rep("", length(render.default(x = y, name = name, ...)))
        if (is.numeric(y)) {
            p <- t.test(y ~ s1$group.ci)$p.value
        } else {
            p <- chisq.test(table(y, droplevels(s1$group.ci)))$p.value
        }
        s[2] <- sub("<", "&lt;", format.pval(p, digits = 3, eps = 0.001))
        s
    } else {
        render.default(x = x, name = name, ...)
    }
}

rndr.ci.strat <- function(label, n, ...) {
    ifelse(n == 0, label, render.strat.default(label, n, ...))
}


# control & critical #
s1$condition.ccrit = NA
s1$condition.ccrit[s1$condition == "Control"] <- "Control"
s1$condition.ccrit[s1$condition == "Critical"] <- "Critical"
s1$condition.ccrit <- as.factor(s1$condition.ccrit)

s1$group.ccrit    <- factor(as.numeric(s1$condition.ccrit), levels = c(1,2,3), labels = c("Critical", "Control", "P-value"))

rndr.ccrit <- function(x, name, ...) {
    if (length(x) == 0) {
        y <- s1[[name]]
        s <- rep("", length(render.default(x = y, name = name, ...)))
        if (is.numeric(y)) {
            p <- t.test(y ~ s1$group.ccrit)$p.value
        } else {
            p <- chisq.test(table(y, droplevels(s1$group.ccrit)))$p.value
        }
        s[2] <- sub("<", "&lt;", format.pval(p, digits = 3, eps = 0.001))
        s
    } else {
        render.default(x = x, name = name, ...)
    }
}

rndr.ccrit.strat <- function(label, n, ...) {
    ifelse(n == 0, label, render.strat.default(label, n, ...))
}
```

```{r groups-s1}
# SAVE VARIABLE GROUPS & NAMES ----
# vars = groups are self-contained for analyses
# vars.names = names of vars for calling into commands

# DEMOGRAPHICS ----
demo_vars_s1 <- dplyr::select(s1, gender, race.f, political.f,age, edu3.f, adj_income, duration)
demo_vars.names_s1 <- names(demo_vars_s1)

# demo_vars_s1.wide <- dplyr::select(s1.wide, gender, race, political, age, edu3, adj_income, duration)
# demo_vars.names_s1.wide <- names(demo_vars_s1.wide)

race_vars_s1 <- dplyr::select(s1, c(white, black, latino, native, asian, mideastern, islander, race_other))

# MAIN ----
main_vars_s1 <- dplyr::select(s1, punitive, restorative, sr.s)
main_vars.names_s1 <- names(main_vars_s1)

main.c_vars_s1 <- dplyr::select(s1, punitive.c, restorative.c, sr.c)
main.c_vars.names_s1 <- names(main.c_vars_s1)

# EXPLORATORY ----
expl_vars_s1 <- dplyr::select(s1, gunbeliefs, gunbeliefs4, anti, viol, antiblack, antihispanic, antiasian, antiwhite)

expl.c_vars_s1 <- dplyr::select(s1, gunbeliefs, gunbeliefs4, anti.c, viol.c, antiblack.c, antihispanic.c, antiasian.c, antiwhite.c)
```

```{r values-s1}
# save values for in-line reporting #
# IVs  ---------------------------
male_perc_s1 = papaja::printnum(100*(sum(s1$male)/nrow(s1)), digits = 0)
female_perc_s1 = papaja::printnum(100*(sum(s1$female)/nrow(s1)), digits = 0)

white_perc_s1 = papaja::printnum(100*(sum(s1$white)/nrow(s1)), digits = 0)
black_perc_s1 = papaja::printnum(100*(sum(s1$black)/nrow(s1)), digits = 0)
latino_perc_s1 = papaja::printnum(100*(sum(s1$latino)/nrow(s1)), digits = 0)
asian_perc_s1 = papaja::printnum(100*(sum(s1$asian)/nrow(s1)), digits = 0)
native_perc_s1 = papaja::printnum(100*(sum(s1$native)/nrow(s1)), digits = 0)
mideastern_perc_s1 = papaja::printnum(100*(sum(s1$mideastern)/nrow(s1)), digits = 0)

income_med_s1 <- papaja::printnum(median(s1$adj_income))
income_m_s1 <- papaja::printnum(mean(s1$adj_income))
income_sd_s1 <- papaja::printnum(psych::SD(s1$adj_income))

# DURATION ---------------------------
duration_m_s1 <- papaja::printnum(mean(s1$duration))
duration_sd_s1 <- papaja::printnum(psych::SD(s1$duration))

duration_m_s1.individual <- papaja::printnum(mean(s1[s1$condition == "individual", "duration"]))
duration_sd_s1.individual <- papaja::printnum(psych::SD(s1[s1$condition == "individual", "duration"]))

duration_m_s1.critical <- papaja::printnum(mean(s1[s1$condition == "critical", "duration"]))
duration_sd_s1.critical <- papaja::printnum(psych::SD(s1[s1$condition == "critical", "duration"]))

duration_m_s1.control <- papaja::printnum(mean(s1[s1$condition == "control", "duration"]))
duration_sd_s1.control <- papaja::printnum(psych::SD(s1[s1$condition == "control", "duration"]))

# PUNITIVE ---------------------------
pun_m_s1 <- papaja::printnum(mean(s1$punitive))
pun_sd_s1 <- papaja::printnum(psych::SD(s1$punitive))

pun_m_s1.individual <- papaja::printnum(mean(s1[s1$condition == "individual", "punitive"]))
pun_sd_s1.individual <- papaja::printnum(psych::SD(s1[s1$condition == "individual", "punitive"]))

pun_m_s1.critical <- papaja::printnum(mean(s1[s1$condition == "critical", "punitive"]))
pun_sd_s1.critical <- papaja::printnum(psych::SD(s1[s1$condition == "critical", "punitive"]))

pun_m_s1.control <- papaja::printnum(mean(s1[s1$condition == "control", "punitive"]))
pun_sd_s1.control <- papaja::printnum(psych::SD(s1[s1$condition == "control", "punitive"]))
pun_skew_s1 <- papaja::printnum(moments::skewness(s1$punitive, na.rm = TRUE))
pun_skew_s1 <- papaja::printnum(moments::skewness(s1$punitive, na.rm = TRUE))

# RESTORATIVE ---------------------------
rest_m_s1 <- papaja::printnum(mean(s1$restorative))
rest_sd_s1 <- papaja::printnum(psych::SD(s1$restorative))

rest_m_s1.individual <- papaja::printnum(mean(s1[s1$condition == "individual", "restorative"]))
rest_sd_s1.individual <- papaja::printnum(psych::SD(s1[s1$condition == "individual", "restorative"]))

rest_m_s1.critical <- papaja::printnum(mean(s1[s1$condition == "critical", "restorative"]))
rest_sd_s1.critical <- papaja::printnum(psych::SD(s1[s1$condition == "critical", "restorative"]))

rest_m_s1.control <- papaja::printnum(mean(s1[s1$condition == "control", "restorative"]))
rest_sd_s1.control <- papaja::printnum(psych::SD(s1[s1$condition == "control", "restorative"]))
rest_skew_s1 <- papaja::printnum(moments::skewness(s1$restorative, na.rm = TRUE))

# SYMBOLIC RACISM ---------------------------
sr_m_s1 <- papaja::printnum(mean(s1$sr))
sr_sd_s1 <- papaja::printnum(psych::SD(s1$sr))

sr_m_s1.individual <- papaja::printnum(mean(s1[s1$condition == "individual", "sr"]))
sr_sd_s1.individual <- papaja::printnum(psych::SD(s1[s1$condition == "individual", "sr"]))

sr_m_s1.critical <- papaja::printnum(mean(s1[s1$condition == "critical", "sr"]))
sr_sd_s1.critical <- papaja::printnum(psych::SD(s1[s1$condition == "critical", "sr"]))

sr_m_s1.control <- papaja::printnum(mean(s1[s1$condition == "control", "sr"]))
sr_sd_s1.control <- papaja::printnum(psych::SD(s1[s1$condition == "control", "sr"]))

# ANTI ---------------------------
anti_m_s1 <- papaja::printnum(mean(s1$anti))
anti_sd_s1 <- papaja::printnum(psych::SD(s1$anti))

anti_m_s1.individual <- papaja::printnum(mean(s1[s1$condition == "individual", "anti"]))
anti_sd_s1.individual <- papaja::printnum(psych::SD(s1[s1$condition == "individual", "anti"]))

anti_m_s1.critical <- papaja::printnum(mean(s1[s1$condition == "critical", "anti"]))
anti_sd_s1.critical <- papaja::printnum(psych::SD(s1[s1$condition == "critical", "anti"]))

anti_m_s1.control <- papaja::printnum(mean(s1[s1$condition == "control", "anti"]))
anti_sd_s1.control <- papaja::printnum(psych::SD(s1[s1$condition == "control", "anti"]))

# VIOL ---------------------------
viol_m_s1 <- papaja::printnum(mean(s1$viol))
viol_sd_s1 <- papaja::printnum(psych::SD(s1$viol))

viol_m_s1.individual <- papaja::printnum(mean(s1[s1$condition == "individual", "viol"]))
viol_sd_s1.individual <- papaja::printnum(psych::SD(s1[s1$condition == "individual", "viol"]))

viol_m_s1.critical <- papaja::printnum(mean(s1[s1$condition == "critical", "viol"]))
viol_sd_s1.critical <- papaja::printnum(psych::SD(s1[s1$condition == "critical", "viol"]))

viol_m_s1.control <- papaja::printnum(mean(s1[s1$condition == "control", "viol"]))
viol_sd_s1.control <- papaja::printnum(psych::SD(s1[s1$condition == "control", "viol"]))

# LAZY ---------------------------
lazy_m_s1 <- papaja::printnum(mean(s1$lazy))
lazy_sd_s1 <- papaja::printnum(psych::SD(s1$lazy))

lazy_m_s1.individual <- papaja::printnum(mean(s1[s1$condition == "individual", "lazy"]))
lazy_sd_s1.individual <- papaja::printnum(psych::SD(s1[s1$condition == "individual", "lazy"]))

lazy_m_s1.critical <- papaja::printnum(mean(s1[s1$condition == "critical", "lazy"]))
lazy_sd_s1.critical <- papaja::printnum(psych::SD(s1[s1$condition == "critical", "lazy"]))

lazy_m_s1.control <- papaja::printnum(mean(s1[s1$condition == "control", "lazy"]))
lazy_sd_s1.control <- papaja::printnum(psych::SD(s1[s1$condition == "control", "lazy"]))

# ANTIBLACK ---------------------------
antiblack_m_s1 <- papaja::printnum(mean(s1$antiblack))
antiblack_sd_s1 <- papaja::printnum(psych::SD(s1$antiblack))

antiblack_m_s1.individual <- papaja::printnum(mean(s1[s1$condition == "individual", "antiblack"]))
antiblack_sd_s1.individual <- papaja::printnum(psych::SD(s1[s1$condition == "individual", "antiblack"]))

antiblack_m_s1.critical <- papaja::printnum(mean(s1[s1$condition == "critical", "antiblack"]))
antiblack_sd_s1.critical <- papaja::printnum(psych::SD(s1[s1$condition == "critical", "antiblack"]))

antiblack_m_s1.control <- papaja::printnum(mean(s1[s1$condition == "control", "antiblack"]))
antiblack_sd_s1.control <- papaja::printnum(psych::SD(s1[s1$condition == "control", "antiblack"]))

# ANTIHISPANIC ---------------------------
antihispanic_m_s1 <- papaja::printnum(mean(s1$antihispanic))
antihispanic_sd_s1 <- papaja::printnum(psych::SD(s1$antihispanic))

antihispanic_m_s1.individual <- papaja::printnum(mean(s1[s1$condition == "individual", "antihispanic"]))
antihispanic_sd_s1.individual <- papaja::printnum(psych::SD(s1[s1$condition == "individual", "antihispanic"]))

antihispanic_m_s1.critical <- papaja::printnum(mean(s1[s1$condition == "critical", "antihispanic"]))
antihispanic_sd_s1.critical <- papaja::printnum(psych::SD(s1[s1$condition == "critical", "antihispanic"]))

antihispanic_m_s1.control <- papaja::printnum(mean(s1[s1$condition == "control", "antihispanic"]))
antihispanic_sd_s1.control <- papaja::printnum(psych::SD(s1[s1$condition == "control", "antihispanic"]))

# ANTIASIAN ---------------------------
antiasian_m_s1 <- papaja::printnum(mean(s1$antiasian))
antiasian_sd_s1 <- papaja::printnum(psych::SD(s1$antiasian))

antiasian_m_s1.individual <- papaja::printnum(mean(s1[s1$condition == "individual", "antiasian"]))
antiasian_sd_s1.individual <- papaja::printnum(psych::SD(s1[s1$condition == "individual", "antiasian"]))

antiasian_m_s1.critical <- papaja::printnum(mean(s1[s1$condition == "critical", "antiasian"]))
antiasian_sd_s1.critical <- papaja::printnum(psych::SD(s1[s1$condition == "critical", "antiasian"]))

antiasian_m_s1.control <- papaja::printnum(mean(s1[s1$condition == "control", "antiasian"]))
antiasian_sd_s1.control <- papaja::printnum(psych::SD(s1[s1$condition == "control", "antiasian"]))

# ANTIWHITE ---------------------------
antiwhite_m_s1 <- papaja::printnum(mean(s1$antiwhite))
antiwhite_sd_s1 <- papaja::printnum(psych::SD(s1$antiwhite))

antiwhite_m_s1.individual <- papaja::printnum(mean(s1[s1$condition == "individual", "antiwhite"]))
antiwhite_sd_s1.individual <- papaja::printnum(psych::SD(s1[s1$condition == "individual", "antiwhite"]))

antiwhite_m_s1.critical <- papaja::printnum(mean(s1[s1$condition == "critical", "antiwhite"]))
antiwhite_sd_s1.critical <- papaja::printnum(psych::SD(s1[s1$condition == "critical", "antiwhite"]))

antiwhite_m_s1.control <- papaja::printnum(mean(s1[s1$condition == "control", "antiwhite"]))
antiwhite_sd_s1.control <- papaja::printnum(psych::SD(s1[s1$condition == "control", "antiwhite"]))
```

## WRANGLE {-}

```{r dvs-reshape-s1}
# DEPENDENT VARIABLES ---------------------------
# select id, dvs and condition
dvs_s1 <- dplyr::select(s1
, id #, startdate
, punitive, names(punitive_vars_s1), names(punitive.f_vars_s1)
, punitive.c, names(punitive.c_vars_s1)
, restorative, names(restorative_vars_s1), names(restorative.f_vars_s1)
, restorative.c, names(restorative.c_vars_s1)
, names(sre_vars_s1), names(sri_vars_s1), names(sr_vars_s1)
, sr.s, sre.s, sri.s # sum composite
, sr.c, sre.c, sri.c, names(sr.c_vars_s1) # mean centered composite
, sr, sre, sri # mean composite
, gunbeliefs4, gunbeliefs, names(gunbeliefs4_vars_s1)
, gunbeliefs4.c, gunbeliefs.c, names(gunbeliefs4.c_vars_s1)
, anti, viol, lazy, names(anti_vars_s1)
, anti.c, viol.c, lazy.c, names(anti.c_vars_s1)
, antiblack, names(antiblack_vars_s1)
, antiblack.c, names(antiblack.c_vars_s1)
, antihispanic, names(antihispanic_vars_s1)
, antihispanic.c, names(antihispanic.c_vars_s1)
, antiasian, names(antiasian_vars_s1)
, antiasian.c, names(antiasian.c_vars_s1)
, antiwhite, names(antiwhite_vars_s1)
, antiwhite.c, names(antiwhite.c_vars_s1)
, drug, drug_policy, drug_prison, names(drug.f_vars_s1)
, fed, names(fed_vars_s1), names(fed.f_vars_s1)
, duration
, comment
, condition #, condition.f, condition.n, critical, control, individual
)

# remove labels
dvs_s1 <-   sjlabelled::unlabel(dvs_s1)

# separate dv scores by condition
# names(dvs_s1)
dvs_s1.wide <- tidyr::pivot_wider(dvs_s1,
                            names_from = condition,
                            names_sep = "__",
                            values_from = punitive:comment)

# reshape to long
# names(dvs_s1.wide)
dvs_s1.long <- tidyr::pivot_longer(dvs_s1.wide,
                                   cols = punitive__critical:comment__individual,
                                   names_sep = "__",
                                   names_to = c("dv", "condition"),
                                   values_to = "score",
                                   values_transform = list(score = as.numeric)
                                   ) 

# order by start date
# dvs_s1.long <- dvs_s1.long[order(dvs_s1.long$startdate),] # commented out because I decided not to include startdate in main df

# reshape to wide
dvs_s1.wide <- tidyr::pivot_wider(dvs_s1.long, names_from = "dv", values_from = "score")

# PREVIEW ---------------------------
# codebook
#sjPlot::view_df(dvs_s1.wide, show.type = TRUE, show.values = TRUE, show.string.values = TRUE, show.labels = TRUE, wrap.labels = 40, show.frq = TRUE, show.prc = TRUE, use.viewer = FALSE) 

# preview
dvs_s1.wide %>% glimpse() %>% head(.,20)
dvs_s1.long %>% glimpse() %>% head(.,20)
```

```{r ivs-reshape-s1}
# INDEPENDENT VARIABLES ---------------------------
# select id, ivs and condition
ivs_s1 <-   dplyr::select(s1
, id, startdate
, duration
, pass, pass.f, fail1, fail2, fail3
, political, political3, liberal, moderate, conservative
, political.f, political3.f, liberal.f, moderate.f, conservative.f
, party, democrat, independent, republican
, party.f, democrat.f, independent.f, republican.f
, gender, female, male
, gender.f, female.f, male.f
, race, white:race_other, multiracial
, race.f, multiracial.f, race.n
, age, age.c
, edu, edu3, nocollege, college, grad
, edu.f, edu3.f, nocollege.f, college.f, grad.f
, adj_income, adj_income.c, income.f, income.med, household #, vote
, condition #, condition.f, condition.n, critical, control, individual
)

# remove labels
ivs_s1 <-   sjlabelled::unlabel(ivs_s1)

# separate iv scores by condition
ivs_s1.wide <- tidyr::pivot_wider(ivs_s1,
                            names_from = condition,
                            names_sep = "__",
                            values_from = duration:household)

# reshape to long
ivs_s1.long <- tidyr::pivot_longer(ivs_s1.wide,
                                   cols = duration__critical:household__individual,
                                   names_sep = "__",
                                   names_to = c("iv", "condition"),
                                   values_to = "score",
                                   values_transform = list(score = as.numeric)
                                   ) 

# order by start date
# ivs_s1.long <- ivs_s1.long[order(ivs_s1.long$startdate),]

# reshape to wide
ivs_s1.wide <- tidyr::pivot_wider(ivs_s1.long, names_from = "iv", values_from = "score")

# PREVIEW ---------------------------
# codebook
#sjPlot::view_df(ivs_s1.wide, show.type = TRUE, show.values = TRUE, show.string.values = TRUE, show.labels = TRUE, wrap.labels = 40, show.frq = TRUE, show.prc = TRUE, use.viewer = FALSE) 

# preview
ivs_s1.wide %>% glimpse() %>% head(.,20)
ivs_s1.long %>% glimpse() %>% head(.,20)

```

```{r reshape-s1}
# ALL MAIN VARS ---------------------------
# select id, ivs and condition
s1.wide <- dplyr::select(s1
, id, startdate
, punitive, names(punitive_vars_s1), names(punitive.f_vars_s1)
, punitive.c, names(punitive.c_vars_s1)
, restorative, names(restorative_vars_s1), names(restorative.f_vars_s1)
, restorative.c, names(restorative.c_vars_s1)
, names(sre_vars_s1), names(sri_vars_s1), names(sr_vars_s1)
, sr.s, sre.s, sri.s # sum composite
, sr.c, sre.c, sri.c, names(sr.c_vars_s1) # mean centered composite
, sr, sre, sri # mean composite
, gunbeliefs4, gunbeliefs, names(gunbeliefs4_vars_s1)
, gunbeliefs4.c, gunbeliefs.c, names(gunbeliefs4.c_vars_s1)
, anti, viol, lazy, names(anti_vars_s1)
, anti.c, viol.c, lazy.c, names(anti.c_vars_s1)
, antiblack, names(antiblack_vars_s1)
, antiblack.c, names(antiblack.c_vars_s1)
, antihispanic, names(antihispanic_vars_s1)
, antihispanic.c, names(antihispanic.c_vars_s1)
, antiasian, names(antiasian_vars_s1)
, antiasian.c, names(antiasian.c_vars_s1)
, antiwhite, names(antiwhite_vars_s1)
, antiwhite.c, names(antiwhite.c_vars_s1)
, drug, drug_policy, drug_prison, names(drug.f_vars_s1)
, fed, names(fed_vars_s1), names(fed.f_vars_s1)
, duration
, comment
, duration
, pass, pass.f, fail1, fail2, fail3
, political, political3, liberal, moderate, conservative
, political.f, political3.f, liberal.f, moderate.f, conservative.f
, party, democrat, independent, republican
, party.f, democrat.f, independent.f, republican.f
, gender, female, male
, gender.f, female.f, male.f
, race, white:race_other, multiracial
, race.f, multiracial.f, race.n
, age, age.c
, edu, edu3, nocollege, college, grad
, edu.f, edu3.f, nocollege.f, college.f, grad.f
, adj_income, adj_income.c, income.f, income.med, household#, vote
, condition#, condition.f condition.n, critical, control, individual
)

# remove labels
s1.wide <-   sjlabelled::unlabel(s1.wide)

# separate dv scores by condition
# names(s1.wide)
s1.wide <- tidyr::pivot_wider(s1.wide,
                            names_from = condition,
                            names_sep = "__",
                            values_from = punitive:household)

# reshape to long
# names(s1.wide)
s1.long <- tidyr::pivot_longer(s1.wide,
                                   cols = punitive__critical:household__individual,
                                   names_sep = "__",
                                   names_to = c("variable", "condition"),
                                   values_to = "score",
                                   values_transform = list(score = as.numeric)
                                   ) 

# order by start date
# s1.long <- s1.long[order(s1.long$startdate),] # commented out because I decided not to include startdate in main df

# reshape to wide
s1.wide <- tidyr::pivot_wider(s1.long, names_from = "variable", values_from = "score")

# PREVIEW ---------------------------
# codebook
#sjPlot::view_df(s1.wide, show.type = TRUE, show.values = TRUE, show.string.values = TRUE, show.labels = TRUE, wrap.labels = 40, show.frq = TRUE, show.prc = TRUE, use.viewer = FALSE) 

# preview
s1.wide %>% glimpse() %>% head(.,20)
s1.long %>% glimpse() %>% head(.,20)
```
```{r dvs-reshape-s1.pass}
# DEPENDENT VARIABLES ---------------------------
# select id, dvs and condition
dvs_s1.pass <- dplyr::select(s1.pass
, id #, startdate
, punitive, names(punitive_vars_s1), names(punitive.f_vars_s1)
, punitive.c, names(punitive.c_vars_s1)
, restorative, names(restorative_vars_s1), names(restorative.f_vars_s1)
, restorative.c, names(restorative.c_vars_s1)
, names(sre_vars_s1), names(sri_vars_s1), names(sr_vars_s1)
, sr.s, sre.s, sri.s # sum composite
, sr.c, sre.c, sri.c, names(sr.c_vars_s1) # mean centered composite
, sr, sre, sri # mean composite
, gunbeliefs4, gunbeliefs, names(gunbeliefs4_vars_s1)
, gunbeliefs4.c, gunbeliefs.c, names(gunbeliefs4.c_vars_s1)
, anti, viol, lazy, names(anti_vars_s1)
, anti.c, viol.c, lazy.c, names(anti.c_vars_s1)
, antiblack, names(antiblack_vars_s1)
, antiblack.c, names(antiblack.c_vars_s1)
, antihispanic, names(antihispanic_vars_s1)
, antihispanic.c, names(antihispanic.c_vars_s1)
, antiasian, names(antiasian_vars_s1)
, antiasian.c, names(antiasian.c_vars_s1)
, antiwhite, names(antiwhite_vars_s1)
, antiwhite.c, names(antiwhite.c_vars_s1)
, drug, drug_policy, drug_prison, names(drug.f_vars_s1)
, fed, names(fed_vars_s1), names(fed.f_vars_s1)
, duration
, comment
, condition #, condition.f, condition.n, critical, control, individual
)

# remove labels
dvs_s1.pass <-   sjlabelled::unlabel(dvs_s1.pass)

# separate dv scores by condition
# names(dvs_s1.pass)
dvs_s1.pass.wide <- tidyr::pivot_wider(dvs_s1.pass,
                            names_from = condition,
                            names_sep = "__",
                            values_from = punitive:comment)

# reshape to long
# names(dvs_s1.pass.wide)
dvs_s1.pass.long <- tidyr::pivot_longer(dvs_s1.pass.wide,
                                   cols = punitive__critical:comment__individual,
                                   names_sep = "__",
                                   names_to = c("dv", "condition"),
                                   values_to = "score",
                                   values_transform = list(score = as.numeric)
                                   ) 

# order by start date
# dvs_s1.pass.long <- dvs_s1.pass.long[order(dvs_s1.pass.long$startdate),] # commented out because I decided not to include startdate in main df

# reshape to wide
dvs_s1.pass.wide <- tidyr::pivot_wider(dvs_s1.pass.long, names_from = "dv", values_from = "score")

# PREVIEW ---------------------------
# codebook
#sjPlot::view_df(dvs_s1.pass.wide, show.type = TRUE, show.values = TRUE, show.string.values = TRUE, show.labels = TRUE, wrap.labels = 40, show.frq = TRUE, show.prc = TRUE, use.viewer = FALSE) 

# preview
dvs_s1.pass.wide %>% glimpse() %>% head(.,20)
dvs_s1.pass.long %>% glimpse() %>% head(.,20)
```

```{r ivs-reshape-s1.pass}
# INDEPENDENT VARIABLES ---------------------------
# select id, ivs and condition
ivs_s1.pass <-   dplyr::select(s1.pass
, id, startdate
, duration
, pass, pass.f, fail1, fail2, fail3
, political, political3, liberal, moderate, conservative
, political.f, political3.f, liberal.f, moderate.f, conservative.f
, party, democrat, independent, republican
, party.f, democrat.f, independent.f, republican.f
, gender, female, male
, gender.f, female.f, male.f
, race, white:race_other, multiracial
, race.f, multiracial.f, race.n
, age, age.c
, edu, edu3, nocollege, college, grad
, edu.f, edu3.f, nocollege.f, college.f, grad.f
, adj_income, adj_income.c, income.f, income.med, household #, vote
, condition #, condition.f, condition.n, critical, control, individual
)

# remove labels
ivs_s1.pass <-   sjlabelled::unlabel(ivs_s1.pass)

# separate iv scores by condition
ivs_s1.pass.wide <- tidyr::pivot_wider(ivs_s1.pass,
                            names_from = condition,
                            names_sep = "__",
                            values_from = duration:household)

# reshape to long
ivs_s1.pass.long <- tidyr::pivot_longer(ivs_s1.pass.wide,
                                   cols = duration__critical:household__individual,
                                   names_sep = "__",
                                   names_to = c("iv", "condition"),
                                   values_to = "score",
                                   values_transform = list(score = as.numeric)
                                   ) 

# order by start date
# ivs_s1.pass.long <- ivs_s1.pass.long[order(ivs_s1.pass.long$startdate),]

# reshape to wide
ivs_s1.pass.wide <- tidyr::pivot_wider(ivs_s1.pass.long, names_from = "iv", values_from = "score")

# PREVIEW ---------------------------
# codebook
#sjPlot::view_df(ivs_s1.pass.wide, show.type = TRUE, show.values = TRUE, show.string.values = TRUE, show.labels = TRUE, wrap.labels = 40, show.frq = TRUE, show.prc = TRUE, use.viewer = FALSE) 

# preview
ivs_s1.pass.wide %>% glimpse() %>% head(.,20)
ivs_s1.pass.long %>% glimpse() %>% head(.,20)

```

```{r reshape-s1.pass}
# ALL MAIN VARS ---------------------------
# select id, ivs and condition
s1.pass.wide <- dplyr::select(s1.pass
, id, startdate
, punitive, names(punitive_vars_s1), names(punitive.f_vars_s1)
, punitive.c, names(punitive.c_vars_s1)
, restorative, names(restorative_vars_s1), names(restorative.f_vars_s1)
, restorative.c, names(restorative.c_vars_s1)
, sr, sre, sri, names(sr_vars_s1)
, sr.c, sre.c, sri.c, names(sr.c_vars_s1)
, gunbeliefs4, gunbeliefs, names(gunbeliefs4_vars_s1)
, gunbeliefs4.c, gunbeliefs.c, names(gunbeliefs4.c_vars_s1)
, anti, viol, lazy, names(anti_vars_s1)
, anti.c, viol.c, lazy.c, names(anti.c_vars_s1)
, antiblack, names(antiblack_vars_s1)
, antiblack.c, names(antiblack.c_vars_s1)
, antihispanic, names(antihispanic_vars_s1)
, antihispanic.c, names(antihispanic.c_vars_s1)
, antiasian, names(antiasian_vars_s1)
, antiasian.c, names(antiasian.c_vars_s1)
, antiwhite, names(antiwhite_vars_s1)
, antiwhite.c, names(antiwhite.c_vars_s1)
, comment
, duration
, pass, pass.f, fail1, fail2, fail3
, political, political3, liberal, moderate, conservative
, political.f, political3.f, liberal.f, moderate.f, conservative.f
, party, democrat, independent, republican
, party.f, democrat.f, independent.f, republican.f
, gender, female, male
, gender.f, female.f, male.f
, race, white:race_other, multiracial
, race.f, multiracial.f, race.n
, age, age.c
, edu, edu3, nocollege, college, grad
, edu.f, edu3.f, nocollege.f, college.f, grad.f
, adj_income, adj_income.c, income.f, income.med, household#, vote
, condition#, condition.f condition.n, critical, control, individual
)

# remove labels
s1.pass.wide <-   sjlabelled::unlabel(s1.pass.wide)

# separate dv scores by condition
# names(s1.pass.wide)
s1.pass.wide <- tidyr::pivot_wider(s1.pass.wide,
                            names_from = condition,
                            names_sep = "__",
                            values_from = punitive:household)

# reshape to long
# names(s1.pass.wide)
s1.pass.long <- tidyr::pivot_longer(s1.pass.wide,
                                   cols = punitive__critical:household__individual,
                                   names_sep = "__",
                                   names_to = c("variable", "condition"),
                                   values_to = "score",
                                   values_transform = list(score = as.numeric)
                                   ) 

# order by start date
# s1.pass.long <- s1.pass.long[order(s1.pass.long$startdate),] # commented out because I decided not to include startdate in main df

# reshape to wide
s1.pass.wide <- tidyr::pivot_wider(s1.pass.long, names_from = "variable", values_from = "score")

# PREVIEW ---------------------------
# codebook
#sjPlot::view_df(s1.pass.wide, show.type = TRUE, show.values = TRUE, show.string.values = TRUE, show.labels = TRUE, wrap.labels = 40, show.frq = TRUE, show.prc = TRUE, use.viewer = FALSE) 

# preview
s1.pass.wide %>% glimpse() %>% head(.,20)
s1.pass.long %>% glimpse() %>% head(.,20)
```

```{r codebook-clean-s1, eval = TRUE}
# CODEBOOK ---------------------------
sjPlot::view_df(s1, show.type = TRUE, show.values = TRUE, show.string.values = TRUE, show.labels = TRUE, wrap.labels = 40, show.frq = TRUE, show.prc = TRUE, use.viewer = FALSE)

sjPlot::view_df(s1.wide, show.type = TRUE, show.values = TRUE, show.string.values = TRUE, show.labels = TRUE, wrap.labels = 40, show.frq = TRUE, show.prc = TRUE, use.viewer = FALSE)
```

## SAVE

```{r save-s1, eval = FALSE}
# SAVE WORKSPACE ---------------------------
# save.image(file = "/Users/cintiahinojosa/Box/Dissertation/data/dissertation-workspace.RData")
save.image(file = "/Users/cintiahinojosa/Box/Dissertation/data/clean-s1.RData")

# SAVE CLEANED DATA ---------------------------
save(s1, file = "/Users/cintiahinojosa/Box/Dissertation/data/s1.RData")
write.csv(s1, file = "/Users/cintiahinojosa/Box/Dissertation/data/s1.csv")
#foreign::write.dta(s1, "/Users/cintiahinojosa/Box/Dissertation/data/s1.dta")
#sjlabelled::write_spss(s1, "/Users/cintiahinojosa/Box/Dissertation/data/s1.sav")

# long
save(s1.long, file = "/Users/cintiahinojosa/Box/Dissertation/data/s1.long.RData")
write.csv(s1.long, file = "/Users/cintiahinojosa/Box/Dissertation/data/s1.long.csv")

# wide
save(s1.wide, file = "/Users/cintiahinojosa/Box/Dissertation/data/s1.wide.RData")
write.csv(s1.wide, file = "/Users/cintiahinojosa/Box/Dissertation/data/s1.wide.csv")
```

## Other

```{r outliers-s1, eval = FALSE}
# DURATION OUTLIERS ---------------------------
# save dataset with drops if duration < 5 mins
#s1.num.pass <- subset(s1.num, s1.num$duration > 5)
#s1.txt.pass <- subset(s1.txt, s1.txt$duration > 5)
```

```{r subset-s1}
# COMPREHENSION CHECK ---------------------------
s1.all <- s1 # save all cases
s1.pass <- subset(s1, pass == 1)
s1.fail <- subset(s1, pass != 1)

# CONDITIONS ---------------------------
s1.control <- subset(s1, condition == "control")
s1.individual <- subset(s1, condition == "individual")
s1.critical <- subset(s1, condition == "critical")

# RACE ---------------------------
s1.black <- subset(s1, black == 1)
s1.latino <- subset(s1, latino == 1)
s1.white <- subset(s1, white == 1)
```
