# General Discussion {#ch2-discussion}

### Limitations and challenges {-}

#### Researchers' disconnect from community networks {-}

I encountered various obstacles in trying to carry out community-based research. Apart from the COVID-19 pandemic, the most prominent challenge was the distrust of [outside/university] researchers due to a history of residential displacement and exploitative research practices with the South Side Chicago community.
Our team also lacked structural ties and social partnerships with specific violence-affected communities. There are many and community-based supports typically start from strengthening local relationships around a shared purpose. As folks who do not have direct experience with community gun violence or have ties to a given neighborhood, we were not positioned to fully commit in the way that is typical. Our research project has a variety of goals and standards that we must meet in order to yield impactful, publishable results that are within the scope of our funders' goals and limitations. 

<!---
Personal time: As a graduate student, [this mismatch/these pressures/shortcomings] were particularly salient because of the time I had to dedicate to classes and pushing forward writing and administrative milestones.--->

<!---
### Theoretical contributions {-}


### Implications {-}


### Future directions {-}
--->

\clearpage