# Study 2 Data Processing

```{r preferences-clean, eval = TRUE}
set.seed(42) # Seed for random number generation
knitr::opts_chunk$set(cache.extra = knitr::rand_seed
                      , echo = FALSE
                      , message = FALSE
                      , warning = FALSE
                      , eval = TRUE # TRUE if re-running code from scratch; FALSE if output only
#                      , fig.show = 'hold'
#                      , fig.align = 'center'
                      )

options(
  knitr.duplicate.label = "allow"
  # , knitr.graphics.auto_pdf = TRUE
  # , knitr.table.format = function() {
  # if (knitr::is_latex_output()) 'latex' else 'pandoc'
  #   }
  )
```

```{r libraries-clean, eval = TRUE}
#data readers ---------------------------
pacman::p_load(haven, readstata13, readxl, foreign) # others: read_excel, rtiffs

#basics ---------------------------
library(knitr)
library(magrittr)
library(dplyr)
library(janitor)

#labels ---------------------------
pacman::p_load(sjlabelled, labelled) #surveytoolbox, tinylabels) 

#summary/output ---------------------------
pacman::p_load(kableExtra, summarytools, table1) #papeR)

#publish ---------------------------
library(apastats)
library(papaja)

#plots ---------------------------
library(ggplot2)
library(corrgram)
library(psych)
```

```{r load-s2, eval = TRUE}
# 1-KEYS & FUNCTIONS ---------------------------
# load(file = "/Users/cintiahinojosa/Box/Dissertation/data/dissertation-keys.RData")

# 2-CLEANED DATASETS ---------------------------
# load(file = "/Users/cintiahinojosa/Box/Dissertation-Proposal/Data/s1.RData")
# load(file = "/Users/cintiahinojosa/Box/Dissertation-Proposal/Data/s2.RData")
# load(file = "/Users/cintiahinojosa/Box/Dissertation-Proposal/Data/s3.RData")

# 3-CLEANED STUDY WORKSPACES ---------------------------
load(file = "/Users/cintiahinojosa/Box/Dissertation/data/clean-s1.RData")
# load(file = "/Users/cintiahinojosa/Box/Dissertation/data/clean-s2.RData")
# load(file = "/Users/cintiahinojosa/Box/Dissertation/data/clean-s3.RData")

# 4-COMBINED CLEANED WORKSAPCE FOR ANALYSES & PLOTS ---------------------------
# load(file = "/Users/cintiahinojosa/Box/Dissertation/data/dissertation-starter.RData") # use to start chstudy1-si code
# load(file = "/Users/cintiahinojosa/Box/Dissertation/data/dissertation-workspace.RData")

# ROUND NUMERIC VARS
# s2 <- s2 %>% mutate_if(is.numeric, round, digits = 3)

# 5-CLEANED DATA SAVED AFTER ANALYSES & PLOTS ---------------------------
# load(file = "/Users/cintiahinojosa/Box/Dissertation/data/dissertation-workspace.RData")
```

```{r raw-s2}
# LIBRARIES ---------------------------
# library(qualtRics) #read_survey()
# library(dplyr) #names() as_tibble()

# LOAD RAW DATA ---------------------------
# export qualtrics data as numeric and as text to cross-check
# (do not check "Use internal IDs in header")
s2.num <- qualtRics::read_survey("/Users/cintiahinojosa/Box/Dissertation-Proposal/Data/Raw/Gun+Violence+Framing+V5-NUMERIC.csv") # N = 2183

s2.txt <- qualtRics::read_survey("/Users/cintiahinojosa/Box/Dissertation-Proposal/Data/Raw/Gun+Violence+Framing+V5-TEXT.csv") # N = 2183

# RAW CODEBOOK ---------------------------
# sjPlot::view_df(s2.num, show.type = TRUE, show.values = TRUE, show.string.values = TRUE, show.labels = TRUE, wrap.labels = 60, show.frq = TRUE, show.prc = TRUE, use.viewer = FALSE)

# sjPlot::view_df(s2.txt, show.type = TRUE, show.values = TRUE, show.string.values = TRUE, show.labels = TRUE, wrap.labels = 60, show.frq = TRUE, show.prc = TRUE, use.viewer = FALSE)

# RENAME MAIN ---------------------------
# lowercase 
names(s2.num) <- tolower(names(s2.num))
names(s2.txt) <- tolower(names(s2.txt))

# META ---------------------------
names(s2.num)[names(s2.num) == "responseid"] <- "id"
names(s2.txt)[names(s2.txt) == "responseid"] <- "id"

names(s2.num)[names(s2.num) == "duration (in seconds)"] <- "duration"
names(s2.txt)[names(s2.txt) == "duration (in seconds)"] <- "duration"

# REFLECTION ---------------------------
names(s2.num)[names(s2.num) == "refl_control"] <- "refl_naive"
names(s2.txt)[names(s2.txt) == "refl_control"] <- "refl_naive"

# IVs ---------------------------
names(s2.num)[names(s2.num) == "race_1"] <- "white"
names(s2.num)[names(s2.num) == "race_2"] <- "latino"
names(s2.num)[names(s2.num) == "race_3"] <- "black"
names(s2.num)[names(s2.num) == "race_4"] <- "native"
names(s2.num)[names(s2.num) == "race_5"] <- "asian"
names(s2.num)[names(s2.num) == "race_6"] <- "mideastern"
names(s2.num)[names(s2.num) == "race_7"] <- "islander"
names(s2.num)[names(s2.num) == "race_8"] <- "race_other"
names(s2.num)[names(s2.num) == "race_8_text"] <- "race_other_text"

names(s2.txt)[names(s2.txt) == "race_1"] <- "white"
names(s2.txt)[names(s2.txt) == "race_2"] <- "latino"
names(s2.txt)[names(s2.txt) == "race_3"] <- "black"
names(s2.txt)[names(s2.txt) == "race_4"] <- "native"
names(s2.txt)[names(s2.txt) == "race_5"] <- "asian"
names(s2.txt)[names(s2.txt) == "race_6"] <- "mideastern"
names(s2.txt)[names(s2.txt) == "race_7"] <- "islander"
names(s2.txt)[names(s2.txt) == "race_8"] <- "race_other"
names(s2.txt)[names(s2.txt) == "race_8_text"] <- "race_other_text"

names(s2.num)[names(s2.num) == "gender_4_text"] <- "gender_other_text"
names(s2.num)[names(s2.num) == "party_4_text"] <- "party_other_text"
names(s2.num)[names(s2.num) == "household_9_text"] <- "household_other_text"
names(s2.num)[names(s2.num) == "edu_10_text"] <- "edu_other_text"

names(s2.txt)[names(s2.txt) == "gender_4_text"] <- "gender_other_text"
names(s2.txt)[names(s2.txt) == "party_4_text"] <- "party_other_text"
names(s2.txt)[names(s2.txt) == "household_9_text"] <- "household_other_text"
names(s2.txt)[names(s2.txt) == "edu_10_text"] <- "edu_other_text"

# MODERN RACISM ---------------------------
# check reversed vars (higher number/disagreement = more racist)
table(s2.num$sr_discrim_r, s2.txt$sr_discrim_r) # None at all (5) = 210; a great deal (1) = 54
table(s2.num$sr_complain_r, s2.txt$sr_complain_r) # strongly disagree (7) = 178; strongly agree (1) = 78 
table(s2.num$sr_slavery_r, s2.txt$sr_slavery_r) # strongly disagree (7) = 151; strongly agree (1) = 172 
table(s2.num$sr_deserve_r, s2.txt$sr_deserve_r) # strongly disagree (7) = 96; strongly agree (1) = 167

# reverse sr_discrim because it wasn't reversed recoded in qualtrics like the other reversed vars
table(s2.num$sr_discrim_r, s2.txt$sr_discrim_r) # None at all (1) = 54; a great deal (5) = 210
s2.num$sr_discrim_r = car::recode(s2.num$sr_discrim_r, '1=5; 2=4; 4=2; 5=1')

s2.txt$sr_discrim_r = car::recode(s2.txt$sr_discrim_r, c("'None at all'='A great deal'; 'A little'='A lot'; 'A lot'='A little'; 'A great deal'='None at all'"))
table(s2.num$sr_discrim_r, s2.txt$sr_discrim_r) # none at all (1) = 210, a great deal (5) = 54

# Alternative varnames
# s2$isr1.hard <- s2$sr_hard.c
# s2$isr2.minorities <- s2$sr_minorities.c
# s2$isr3.demand <- s2$sr_demand.c
# s2$isr4.tension <- s2$sr_tension.c
# s2$isr5.complain <- s2$sr_complain_r.c
# s2$esr6.discrim <- s2$sr_discrim_r.c
# s2$esr7.slavery <- s2$sr_slavery_r.c
# s2$esr8.change <- s2$sr_change.c
# s2$esr9.deserve <- s2$sr_deserve_r.c
# s2$esr10.econ <- s2$sr_econ.c

# INEQUALITY ---------------------------
# mislabelled in qualtrics
names(s2.num)[names(s2.num) == "ineq_chancepoor...81"] <- "ineq_chancepoor"
names(s2.txt)[names(s2.txt) == "ineq_chancepoor...81"] <- "ineq_chancepoor"

names(s2.num)[names(s2.num) == "ineq_chancepoor...69"] <- "ineq_edufem"
names(s2.txt)[names(s2.txt) == "ineq_chancepoor...69"] <- "ineq_edufem"

# EGALITARIAN ---------------------------
table(s2.num$`egal_good_r"`, s2.txt$`egal_good_r"`) # strongly disagree (1) with egal_r = 380; strongly agree (7) with egal_r = 58

# rename/create new var to fix import typo and to avoid confusion with egal_good
s2.num$egal_hierarchy_r <- s2.num$`egal_good_r"` # freq(s2.num$egal_hierarchy_r)
s2.txt$egal_hierarchy_r <- s2.txt$`egal_good_r"` # freq(s2.txt$egal_hierarchy_r)

# fix reversing on egal_hierarchy because it wasn't reversed recoded in qualtrics like the other reversed vars
s2.num$egal_hierarchy = car::recode(s2.num$egal_hierarchy_r, '1=7; 2=6; 3=5; 5=3; 6=2; 7=1')
table(s2.num$egal_hierarchy_r, s2.num$egal_hierarchy)

s2.txt$egal_hierarchy = car::recode(s2.txt$egal_hierarchy_r, c("'Strongly disagree'='Strongly agree'; 'Disagree'='Agree'; 'Somewhat disagree'='Somewhat agree'; 'Somewhat agree'='Somewhat disagree'; 'Agree'='Disagree'; 'Strongly agree'='Strongly disagree'"))
table(s2.num$egal_hierarchy, s2.txt$egal_hierarchy) # strongly disagree (1) with egal = 58; strongly agree (7) with egal = 380

# NFC ---------------------------
# check reversed vars
table(s2.num$nfc_notfun, s2.txt$nfc_notfun) # Not at all (1) = 446; almost completely (5) = 68
table(s2.num$nfc_nochallenge, s2.txt$nfc_nochallenge) # Not at all (1) = 372; almost completely (5) = 88
table(s2.num$nfc_avoid, s2.txt$nfc_avoid) # Not at all (1) = 383; almost completely (5) = 81
table(s2.num$nfc_only, s2.txt$nfc_only) # Not at all (1) = 342; almost completely (5) = 92
table(s2.num$nfc_daily, s2.txt$nfc_daily) # Not at all (1) = 183; almost completely (5) = 84
table(s2.num$nfc_little, s2.txt$nfc_little) # Not at all (1) = 195; almost completely (5) = 108
table(s2.num$nfc_unexcite, s2.txt$nfc_unexcite) # Not at all (1) = 423; almost completely (5) = 71
table(s2.num$nfc_done, s2.txt$nfc_done) # Not at all (1) = 273; almost completely (5) = 87

# reverse code
s2.num$nfc_notfun_r = car::recode(s2.num$nfc_notfun, '1=5; 2=4; 4=2; 5=1')
s2.num$nfc_nochallenge_r = car::recode(s2.num$nfc_nochallenge, '1=5; 2=4; 4=2; 5=1')
s2.num$nfc_avoid_r = car::recode(s2.num$nfc_avoid, '1=5; 2=4; 4=2; 5=1')
s2.num$nfc_only_r = car::recode(s2.num$nfc_only, '1=5; 2=4; 4=2; 5=1')
s2.num$nfc_daily_r = car::recode(s2.num$nfc_daily, '1=5; 2=4; 4=2; 5=1')
s2.num$nfc_little_r = car::recode(s2.num$nfc_little, '1=5; 2=4; 4=2; 5=1')
s2.num$nfc_unexcite_r = car::recode(s2.num$nfc_unexcite, '1=5; 2=4; 4=2; 5=1')
s2.num$nfc_relief_r = car::recode(s2.num$nfc_relief, '1=5; 2=4; 4=2; 5=1')
s2.num$nfc_done_r = car::recode(s2.num$nfc_done, '1=5; 2=4; 4=2; 5=1')

s2.txt$nfc_notfun_r = car::recode(s2.txt$nfc_notfun, amount5.nfc_r.keys)
s2.txt$nfc_nochallenge_r = car::recode(s2.txt$nfc_nochallenge, amount5.nfc_r.keys)
s2.txt$nfc_avoid_r = car::recode(s2.txt$nfc_avoid, amount5.nfc_r.keys)
s2.txt$nfc_only_r = car::recode(s2.txt$nfc_only, amount5.nfc_r.keys)
s2.txt$nfc_daily_r = car::recode(s2.txt$nfc_daily, amount5.nfc_r.keys)
s2.txt$nfc_little_r = car::recode(s2.txt$nfc_little, amount5.nfc_r.keys)
s2.txt$nfc_unexcite_r = car::recode(s2.txt$nfc_unexcite, amount5.nfc_r.keys)
s2.txt$nfc_relief_r = car::recode(s2.txt$nfc_relief, amount5.nfc_r.keys)
s2.txt$nfc_done_r = car::recode(s2.txt$nfc_done, amount5.nfc_r.keys)


# check fixed reversed vars
table(s2.num$nfc_notfun_r, s2.txt$nfc_notfun_r) # Not at all (1) = 68; almost completely (5_r) = 446
table(s2.num$nfc_nochallenge_r, s2.txt$nfc_nochallenge_r) # Not at all (1) = 88; almost completely (5_r) = 372
table(s2.num$nfc_avoid_r, s2.txt$nfc_avoid_r) # Not at all (1) = ; almost completely (5_r) = 
table(s2.num$nfc_only_r, s2.txt$nfc_only_r) # Not at all (1) = ; almost completely (5_r) = 
table(s2.num$nfc_daily_r, s2.txt$nfc_daily_r) # Not at all (1) = ; almost completely (5_r) = 
table(s2.num$nfc_little_r, s2.txt$nfc_little_r) # Not at all (1) = ; almost completely (5_r) = 
table(s2.num$nfc_unexcite_r, s2.txt$nfc_unexcite_r) # Not at all (1) = ; almost completely (5_r) = 
table(s2.num$nfc_done_r, s2.txt$nfc_done_r) # Not at all (1) = ; almost completely (5_r) = 

# DROP NON-USABLE DATA ---------------------------
# drop survey previews, tests, and spam # N = 2130
table(s2.txt$finished, s2.num$finished)
s2.num <- subset(s2.num, status == 0) #freq(s2.num$status) 0=2130, 1=2, 8=51
s2.txt <- subset(s2.txt, status == "IP Address") #freq(s2.txt$status) IP Address=2130, Spam=2, Survey Preview=51

# drop non-consents # N = 1975
table(s2.txt$consent, s2.num$consent)
s2.num <- subset(s2.num, consent == 1) #freq(s2.num$consent), 1=1975, 2=141, NA=14
s2.txt <- subset(s2.txt, consent == "Yes, I fit the above criteria and consent to participate in the study.") #freq(s2.txt$consent), "Yes..." =1975, "No..."=141, NA=14

# drop non-finished # N = 1043
table(s2.txt$finished, s2.num$finished)
s2.txt <- subset(s2.txt, s2.txt$finished == "TRUE")
s2.num <- subset(s2.num, s2.num$finished == 1)

# drop non-randomized # N = 1191
s2.txt <- subset(s2.txt, progress > 13 & condition == "treat" | progress > 6 & condition == "control")
s2.num <- subset(s2.num, progress > 13 & condition == "treat" | progress > 6 & condition == "control")

# double check non-randomized
# submit article N=934 (control=481, treat=453)
# s2$pagesubmit.naive = 0  # 1=481, 0=453
# s2$pagesubmit.naive[s2$`t_naive_page submit`>1] <- 1
# 
# s2$pagesubmit.critical = 0 # 1=453, 0=481
# s2$pagesubmit.critical[s2$`t_critical_page submit`>1] <- 1
# 
# submit reflection: N=934 (control=481, treat=453)
# s2$reflsubmit.naive = 0 # 1=481, 0=453
# s2$reflsubmit.naive[s2$`t_refl_control_page submit`>1] <- 1 
# 
# s2$reflsubmit.critical = 0 # N=934 (control=481, treat=453)
# s2$reflsubmit.critical[s2$`t_refl_critical_page submit`>1] <- 1 # 1=453, 0=481

# SAVE PARTICIPANT DATA W/RENAMED COLUMNS ---------------------------
write.csv(s2.num, file = "/Users/cintiahinojosa/Box/Dissertation/data/raw/s2-raw-num.csv")
save(s2.num, file = "/Users/cintiahinojosa/Box/Dissertation/data/raw/s2-raw-num.RData")

write.csv(s2.txt, file = "/Users/cintiahinojosa/Box/Dissertation/data/raw/s2-raw-txt.csv")
save(s2.txt, file = "/Users/cintiahinojosa/Box/Dissertation/data/raw/s2-raw-txt.RData")

# SET UP WORKING DATASETS ---------------------------
# save numeric as working data file # N = 1043
s2 <- as_tibble(s2.num)
s2.num <- as_tibble(s2.num)
s2.txt <- as_tibble(s2.txt)

# save names of order variables # 86 vars
names_do_s2 <- s2 %>% dplyr::select(contains('_do_')) %>% names()

# save names of time variables # 16 vars
names_time_s2 <- s2 %>% dplyr::select(contains('t_')) %>% dplyr::select(!contains('_do_')) %>%  dplyr::select(!starts_with('rest_')) %>% names()

# save names of main variables # 110 vars
names_s2  <- names(s2[,!(names(s2) %in% c(names_do_s2, names_time_s2))])

# save working data with main variables only # 110 vars
s2  <- s2[,!(names(s2) %in% c(names_do_s2, names_time_s2))]

# SAVE WORKING DATASET ---------------------------
# repeat this command after finishing recode chunk
save(s2, file = "/Users/cintiahinojosa/Box/Dissertation/data/s2.RData")
write.csv(s2, file = "/Users/cintiahinojosa/Box/Dissertation/data/s2.csv")
```

```{r codebook-s2}
# WORKING DATASET CODEBOOK ---------------------------
sjPlot::view_df(s2.num, show.type = TRUE, show.values = TRUE, show.string.values = TRUE, show.labels = TRUE, wrap.labels = 60, show.frq = TRUE, show.prc = TRUE, use.viewer = FALSE)
```

```{r ivs-clean-s2}
# DURATION ---------------------------
# transform seconds to minutes
s2$duration <- (s2$duration/60)
summary(s2$duration)

# mark outliers
duration_q1_s2 <- quantile(s2$duration, .25) 
duration_q3_s2 <- quantile(s2$duration, .75) 
duration_iqr_s2 <- IQR(s2$duration) 

# duration_out_s2 <- boxplot.stats(s2$duration)$out
# duration_out_s2 <- which(s2$duration < duration_q1_s2 | s2$duration > duration_q3_s2)

s2$duration_under <- 0
s2$duration_under[s2$duration < 5] <- 1
s2$duration_under[s2$duration == 5] <- 0
s2$duration_under[s2$duration > 5] <- 0
freq(s2$duration_under)

# CONDITION  ---------------------------
# check and recode if needed
freq(s2$condition)
s2$condition[s2$condition == "treat"] <- "critical"
s2$condition[s2$condition == "control"] <- "naive"

# create factor variable
s2$condition.f <- factor(s2$condition, levels = c("critical", "naive"), labels = c("Critical", "Naive"), ordered = FALSE)

# create numeric variable 
s2$condition.n <- as.numeric(s2$condition.f) 
freq(s2$condition.n)

# create binary variables
s2$critical = NA
s2$critical[s2$condition == "critical"] <- 1
s2$critical[s2$condition == "naive"] <- 0
freq(s2$critical)
s2$critical.f <- factor(s2$critical, levels = 0:1, labels = c("non-critical", "critical"), ordered = FALSE)
freq(s2$critical.f)

s2$naive = NA 
s2$naive[s2$condition == "critical"] <- 0
s2$naive[s2$condition == "naive"] <- 1
freq(s2$naive)
s2$naive.f <- factor(s2$naive, levels = 0:1, labels = c("non-naive", "naive"), ordered = FALSE) 
freq(s2$naive.f)

# AGE ---------------------------
freq(s2$age)
s2$age[s2$age == "040"] <- 40 # correct participant typo
s2$age <- as.numeric(s2$age) 

# CENTER
s2 <- s2 %>%
  mutate(age.c = scale(age, center = TRUE, scale = TRUE))

# POLITICAL ---------------------------
freq(s2$political)
s2$political.f <- factor(s2$political, levels = 1:7, labels = political7.labels, ordered = TRUE) 
freq(s2$political.f)

# POLITICAL3 ---------------------------
s2$political3 = NA 
s2$political3[s2$political.f == "extremely liberal"] <- 1 # liberal
s2$political3[s2$political.f == "moderately liberal"] <- 1 # liberal
s2$political3[s2$political.f == "slightly liberal"] <- 1 # liberal
s2$political3[s2$political.f == "moderate"] <- 2 # moderate
s2$political3[s2$political.f == "slightly conservative"] <- 3 # conservative
s2$political3[s2$political.f == "moderately conservative"] <- 3 # conservative
s2$political3[s2$political.f == "extremely conservative"] <- 3 # conservative
freq(s2$political3)

s2$political3.f<- factor(s2$political3, levels = 1:3, labels = political3.labels, ordered = TRUE) 
freq(s2$political3.f)

# create binary variables
freq(s2$political3)

s2$liberal = NA
s2$liberal[s2$political3.f == "liberal"] <- 1
s2$liberal[s2$political3.f == "moderate"] <- 0
s2$liberal[s2$political3.f == "conservative"] <- 0
freq(s2$liberal)
s2$liberal.f <- factor(s2$liberal, levels = 0:1, labels = c("non-liberal", "liberal"), ordered = FALSE)
freq(s2$liberal.f)

s2$moderate = NA
s2$moderate[s2$political3.f == "liberal"] <- 0
s2$moderate[s2$political3.f == "moderate"] <- 1
s2$moderate[s2$political3.f == "conservative"] <- 0
freq(s2$moderate)
s2$moderate.f <- factor(s2$moderate, levels = 0:1, labels = c("non-moderate", "moderate"), ordered = FALSE)
freq(s2$moderate.f)

s2$conservative = NA
s2$conservative[s2$political3.f == "liberal"] <- 0
s2$conservative[s2$political3 == "moderate"] <- 0
s2$conservative[s2$political3 == "conservative"] <- 1
freq(s2$conservative)
s2$conservative.f <- factor(s2$conservative, levels = 0:1, labels = c("non-conservative", "conservative"), ordered = FALSE)
freq(s2$conservative.f)

# PARTY ---------------------------
freq(s2$party) 
freq(s2.txt$party) 
freq(s2.txt$party_other_text)
# Green
# Green party
# libertarian
# Libertarian
# Oblique
# Patriot
# Unaffiliated
s2$party.f <- factor(s2$party, levels = 1:5, labels = c("democrat", "republican", "independent", "other", "none"), ordered = FALSE)
freq(s2$party.f)

s2$democrat = NA 
s2$democrat[s2$party.f == "democrat"] <- 1
s2$democrat[s2$party.f !=  "democrat"] <- 0
freq(s2$democrat)
s2$democrat.f <- factor(s2$democrat, levels = 0:1, labels = c("non-democrat", "democrat"), ordered = FALSE) 
freq(s2$democrat.f)

s2$republican = NA 
s2$republican[s2$party.f == "republican"] <- 1
s2$republican[s2$party.f !=  "republican"] <- 0
freq(s2$republican)
s2$republican.f <- factor(s2$republican, levels = 0:1, labels = c("non-republican", "republican"), ordered = FALSE) 
freq(s2$republican.f)

s2$independent = NA
s2$independent[s2$party.f == "independent"] <- 1
s2$independent[s2$party.f !=  "independent"] <- 0
freq(s2$independent)
s2$independent.f <- factor(s2$independent, levels = 0:1, labels = c("non-independent", "independent"), ordered = FALSE) 
freq(s2$independent.f)

# GENDER ---------------------------
freq(s2$gender)
freq(s2.txt$gender) 
s2$gender.f <- factor(s2$gender, levels = 1:5, labels = gender5.labels, ordered = FALSE)
freq(s2$gender.f) 

# create binary variables
s2$female = NA 
s2$female[s2$gender.f == "female"] <- 1
s2$female[s2$gender.f != "female"] <- 0
freq(s2$female) 
s2$female.f <- factor(s2$female, levels = 0:1, labels = c("non-female", "female"), ordered = FALSE) 
freq(s2$female.f) 

s2$male = NA 
s2$male[s2$gender.f == "male"] <- 1
s2$male[s2$gender.f != "male"] <- 0
freq(s2$male) 
s2$male.f <- factor(s2$male, levels = 0:1, labels = c("non-male", "male"), ordered = FALSE)
freq(s2$male.f) 

# EDU ---------------------------
freq(s2.txt$edu)
freq(s2$edu)
unique(s2$edu_other_text)
s2$edu.f <- factor(s2$edu, levels = 1:10, labels = edu10.labels, ordered = TRUE)
freq(s2$edu.f)

# EDU3 ---------------------------
s2$edu3 = s2$edu
freq(s2$edu3)
s2$edu3[s2$edu == 1] <- 1 # no college degree
s2$edu3[s2$edu == 2] <- 1 # no college degree
s2$edu3[s2$edu == 3] <- 1 # no college degree
s2$edu3[s2$edu == 4] <- 2 # college
s2$edu3[s2$edu == 5] <- 2 # college
s2$edu3[s2$edu == 6] <- 3 # grad
s2$edu3[s2$edu == 7] <- 3 # grad
s2$edu3[s2$edu == 8] <- 3 # grad
s2$edu3[s2$edu == 9] <- 2 # college
freq(s2$edu3)

s2$edu3.f <- factor(s2$edu3, levels = 1:3, labels = edu3.labels, ordered = FALSE)
freq(s2$edu3.f)

# create binary variables
s2$nocollege = NA
s2$nocollege[s2$edu3 == 1] <- 1
s2$nocollege[s2$edu3 == 2] <- 0
s2$nocollege[s2$edu3 == 3] <- 0
freq(s2$nocollege) 
s2$nocollege.f <- factor(s2$nocollege, levels = 0:1, labels = c("college degree or higher", "no college degree"), ordered = FALSE)
freq(s2$nocollege.f)

s2$college = NA
s2$college[s2$edu3 == 1] <- 0
s2$college[s2$edu3 == 2] <- 1
s2$college[s2$edu3 == 3] <- 1
freq(s2$college)
s2$college.f <- factor(s2$college, levels = 0:1, labels = c("no college degree", "college degree or higher"), ordered = FALSE)
freq(s2$college.f)

s2$grad = NA
s2$grad[s2$edu3 == 1] <- 0
s2$grad[s2$edu3 == 2] <- 0
s2$grad[s2$edu3 == 3] <- 1
freq(s2$grad)
s2$grad.f <- factor(s2$grad, levels = 0:1, labels = c("no graduate degree", "graduate degree"), ordered = FALSE)
freq(s2$grad.f)

# INCOME ---------------------------
s2$income.f <- s2$income
freq(s2$income)
s2$income.f <- factor(s2$income, levels = 1:12, labels = income12.labels, ordered = TRUE) 
freq(s2$income.f)

# ADJ_INCOME ---------------------------
# median of income bin besides min/max; only use to calculate adjusted income
s2$income.med <- NA
s2$income.med[s2$income == 1] <- 10000
s2$income.med[s2$income == 2] <- 15000
s2$income.med[s2$income == 3] <- 25000
s2$income.med[s2$income == 4] <- 35000
s2$income.med[s2$income == 5] <- 45000 
s2$income.med[s2$income == 6] <- 55000
s2$income.med[s2$income == 7] <- 65000 
s2$income.med[s2$income == 8] <- 75000 
s2$income.med[s2$income == 9] <- 85000 
s2$income.med[s2$income == 10] <- 95000 
s2$income.med[s2$income == 11] <- 125000 
s2$income.med[s2$income == 12] <- 150000

# transform income to adjust for household size
s2$adj_income <- (s2$income.med/sqrt(s2$household))
s2$adj_income <- formattable::currency(s2$adj_income, digits = 2L)
summary(s2$adj_income)

# CENTER
s2 <- s2 %>%
  mutate(adj_income.c = scale(adj_income, center = TRUE, scale = TRUE))

# RACE STEP 1: RACE_OTHER ---------------------------
# check race_other to recode accordingly 
unique(s2$race_other_text)
# As if all of the subcategories listed under "white" are even remotely the same. What a bunch of Jackasses. I am 100% Italian-American and it is very different than the others.
# Caucasian
# Druid
# Greek
# hispanic
# Latino
# None of your business
# Prefer not to answer
# Sami
# test
# United States Citizen by Birth
# White(English)

# remove quotation marks
s2$race_other_text <- gsub("\"","", s2$race_other_text)
freq(s2$race_other_text)

# recoding:
# recode race_other to white
freq(s2$white)
s2$white[s2$race_other_text == "As if all of the subcategories listed under white are even remotely the same. What a bunch of Jackasses. I am 100% Italian-American and it is very different than the others."] <- 1 
s2$race_other[s2$race_other_text == "As if all of the subcategories listed under white are even remotely the same. What a bunch of Jackasses. I am 100% Italian-American and it is very different than the others."] <- 0 

s2$white[s2$race_other_text == "Caucasian"] <- 1 
s2$race_other[s2$race_other_text == "Caucasian"] <- 0

s2$white[s2$race_other_text == "White(English)"] <- 1 
s2$race_other[s2$race_other_text == "White(English)"] <- 0

# recode race_other to latino 
freq(s2$latino)
s2$latino[s2$race_other_text == "hispanic"] <- 1 
s2$race_other[s2$race_other_text == "hispanic"] <- 0

s2$latino[s2$race_other_text == "Latino"] <- 1 
s2$race_other[s2$race_other_text == "Latino"] <- 0

# NOT recoding: 
# "Druid", "Greek", "None of your business", "Prefer not to answer", "Sami", "United States Citizen by Birth"

# RACE STEP 2: MULTIRACIAL ---------------------------
s2$multiracial <- NA
s2$multiracial <- rowSums(s2[, c("white", "black", "latino", "native", "asian", "mideastern", "islander", "race_other")])
freq(s2$multiracial)
s2$multiracial.f <- NA
s2$multiracial.f[s2$multiracial == 1] <- 0
s2$multiracial.f[s2$multiracial >= 2] <- 1 # freq(s2$multiracial.f)
s2$multiracial <- s2$multiracial.f

# recode race_others
freq(s2$multiracial)
s2$multiracial[s2$race_other_text == "afro latinx"] <- 1
s2$multiracial[s2$race_other_text == "mixed black/white"] <- 1
s2$multiracial[s2$race_other_text == "mixed"] <- 1 

s2$multiracial.f <- factor(s2$multiracial, levels = 0:1, labels = c("monoracial", "multiracial"), ordered = FALSE)
freq(s2$multiracial.f)

# RACE STEP 4: RACE ---------------------------
# create race variable 
freq(s2.txt$race_other_text)
s2$race = NA
s2$race[s2$race_other == 1] <- "other"
s2$race[s2$islander == 1] <- "pacific islander"
s2$race[s2$mideastern == 1] <- "middle eastern"
s2$race[s2$asian == 1] <- "asian"
s2$race[s2$native == 1] <- "native american"
s2$race[s2$black == 1] <- "black"
s2$race[s2$latino == 1] <- "latino"
s2$race[s2$white == 1] <- "white"
s2$race[s2$multiracial == 1] <- "multiracial"
freq(s2$race) 

s2$race.n = NA
s2$race.n[s2$race_other == 1] <- 8
s2$race.n[s2$islander == 1] <- 7
s2$race.n[s2$mideastern == 1] <- 6
s2$race.n[s2$asian == 1] <- 5
s2$race.n[s2$native == 1] <- 4
s2$race.n[s2$black == 1] <- 3
s2$race.n[s2$latino == 1] <- 2
s2$race.n[s2$white == 1] <- 1
s2$race.n[s2$multiracial == 1] <- 9
freq(s2$race.n)

s2$race.f <- NA
s2$race.f <- factor(s2$race.n, levels = 1:9, labels = race9.labels, ordered = FALSE)
freq(s2$race.f) 
```

```{r pun-clean-s2}
# PUNITIVE
# GROUP ITEMS ---------------------------
punitive_vars_s2 <- dplyr::select(s2, pun_cops, pun_jailtime, pun_penalty, pun_prisons)
punitive_vars.names_s2 <- names(punitive_vars_s2)

# CORRELATIONS ---------------------------
# correlation matrix
punitive_cormat_s2 <- cor(punitive_vars_s2, use = "complete.obs") 
punitive_cormat_s2 <- round(punitive_cormat_s2, 3)

# correlation plot with psych package
png(filename="/Users/cintiahinojosa/Box/Dissertation/images/punitive_corplot_s2.png", height = 700, width = 1000)
psych::corPlot(punitive_vars_s2 # labels = punitive_vars.labels_s2
               , scale = TRUE, upper = FALSE, alpha = 0.5
               , main = "Correlation Matrix of Punitive Policy Support Items in Study 2") #stars = FALSE, 
dev.off()

# correlation plot with corrgram package
png(filename="/Users/cintiahinojosa/Box/Dissertation/images/punitive_corrgram_s2.png", height = 700, width = 1000)
corrgram::corrgram(punitive_vars_s2
         , main = "Correlation Matrix of Punitive Policy Support Items in Study 2 (Ordered)"
         , lower.panel = panel.cor #panel.cor, panel.pts, panel.conf
#         , upper.panel =  NULL #panel.conf #panel.shade #NULL
#         , diag.panel = panel.txt #panel.density, panel.minmax
         , text.panel = panel.txt
         , order = TRUE # "PCA" = TRUE
         , col.regions = colorRampPalette(c("red4", "grey", "darkgreen"))
           )
dev.off()

# CREATE COMPOSITE ---------------------------
freq(s2$pun_cops)
s2$punitive <- rowMeans(subset(s2, select = punitive_vars.names_s2), na.rm = TRUE)
summary(s2$punitive)
punitive_alpha_s2 <- ltm::cronbach.alpha(punitive_vars_s2)
papaja::printnum(punitive_alpha_s2$alpha) # .802

# GRAND-MEAN CENTER & STANDARDIZE ---------------------------
s2 <- s2 %>%
  mutate(punitive.c = scale(punitive, center = TRUE, scale = TRUE)
         , pun_cops.c = scale(pun_cops, center = TRUE, scale = TRUE)
         , pun_jailtime.c = scale(pun_jailtime, center = TRUE, scale = TRUE)
         , pun_penalty.c = scale(pun_penalty, center = TRUE, scale = TRUE)
         , pun_prisons.c = scale(pun_prisons, center = TRUE, scale = TRUE)
         )
summary(s2$punitive.c)
summary(s2$pun_prisons.c)

# GROUP STANDARDIZED ITEMS ---------------------------
punitive.c_vars_s2 <- dplyr::select(s2, pun_cops.c, pun_jailtime.c, pun_penalty.c, pun_prisons.c)
punitive.c_vars.names_s2 <- names(punitive.c_vars_s2)
punitive.c_alpha_s2 <- ltm::cronbach.alpha(punitive.c_vars_s2)
papaja::printnum(punitive.c_alpha_s2$alpha) # .802

# FACTOR VARS ---------------------------
s2$pun_cops.f <- factor(s2$pun_cops, levels = 1:7, labels = favor7.labels, ordered = TRUE)
s2$pun_jailtime.f <- factor(s2$pun_jailtime, levels = 1:7, labels = favor7.labels, ordered = TRUE)
s2$pun_penalty.f <- factor(s2$pun_penalty, levels = 1:7, labels = favor7.labels, ordered = TRUE)
s2$pun_prisons.f <- factor(s2$pun_prisons, levels = 1:7, labels = favor7.labels, ordered = TRUE)
punitive.f_vars_s2 <- dplyr::select(s2, pun_cops.f, pun_jailtime.f, pun_penalty.f, pun_prisons.f)
punitive.f_vars.names_s2 <- names(punitive.f_vars_s2)
```

```{r rest-clean-s2}
# RESTORATIVE
# GROUP ITEMS ---------------------------
restorative_vars_s2 <- dplyr::select(s2, rest_banbox, rest_fedaid, rest_jobs, rest_youth)
restorative_vars.names_s2 <- names(restorative_vars_s2)

# CORRELATIONS ---------------------------
# correlation matrix
restorative_cormat_s2 <- cor(restorative_vars_s2, use = "complete.obs") 
restorative_cormat_s2 <- round(restorative_cormat_s2, 3)

# correlation plot with psych package
png(filename="/Users/cintiahinojosa/Box/Dissertation/images/restorative_corplot_s2.png", height = 700, width = 1000)
psych::corPlot(restorative_vars_s2 # labels = restorative_vars.labels_s2
               , scale = TRUE, upper = FALSE, alpha = 0.5
               , main = "Correlation Matrix of Restorative Policy Support Items in Study 2") #stars = FALSE, 
dev.off()

# correlation plot with corrgram package
png(filename="/Users/cintiahinojosa/Box/Dissertation/images/restorative_corrgram_s2.png", height = 700, width = 1000)
corrgram::corrgram(restorative_vars_s2
         , main = "Correlation Matrix of Restorative Policy Support Items in Study 2 (Ordered)"
         , lower.panel = panel.cor #panel.cor, panel.pts, panel.conf
#         , upper.panel =  NULL #panel.conf #panel.shade #NULL
#         , diag.panel = panel.txt #panel.density, panel.minmax
         , text.panel = panel.txt
         , order = TRUE # "PCA" = TRUE
         , col.regions = colorRampPalette(c("red4", "grey", "darkgreen"))
           )
dev.off()

# CREATE COMPOSITE ---------------------------
freq(s2$rest_banbox)
s2$restorative <- rowMeans(subset(s2, select = restorative_vars.names_s2), na.rm = TRUE) 
summary(s2$restorative)
restorative_alpha_s2 <- ltm::cronbach.alpha(restorative_vars_s2)
papaja::printnum(restorative_alpha_s2$alpha) #

# GRAND-MEAN CENTER & STANDARDIZE ---------------------------
s2 <- s2 %>%
  mutate(restorative.c = scale(restorative, center = TRUE, scale = TRUE)
         , rest_banbox.c = scale(rest_banbox, center = TRUE, scale = TRUE)
         , rest_fedaid.c = scale(rest_fedaid, center = TRUE, scale = TRUE)
         , rest_jobs.c = scale(rest_jobs, center = TRUE, scale = TRUE)
         , rest_youth.c = scale(rest_youth, center = TRUE, scale = TRUE)
         ) 
summary(s2$restorative.c) 
summary(s2$rest_youth.c)

# GROUP STANDARDIZED ITEMS ---------------------------
restorative.c_vars_s2 <- dplyr::select(s2, rest_banbox.c, rest_fedaid.c, rest_jobs.c, rest_youth.c)
restorative.c_vars.names_s2 <- names(restorative.c_vars_s2)
restorative.c_alpha_s2 <- ltm::cronbach.alpha(restorative.c_vars_s2) 
papaja::printnum(restorative.c_alpha_s2$alpha) #

# FACTOR VARS ---------------------------
s2$rest_banbox.f <- factor(s2$rest_banbox, levels = 1:7, labels = favor7.labels, ordered = TRUE)
s2$rest_fedaid.f <- factor(s2$rest_fedaid, levels = 1:7, labels = favor7.labels, ordered = TRUE)
s2$rest_jobs.f <- factor(s2$rest_jobs, levels = 1:7, labels = favor7.labels, ordered = TRUE)
s2$rest_youth.f <- factor(s2$rest_youth, levels = 1:7, labels = favor7.labels, ordered = TRUE)
restorative.f_vars_s2 <- dplyr::select(s2, rest_banbox.f, rest_fedaid.f, rest_jobs.f, rest_youth.f)
restorative.f_vars.names_s2 <- names(restorative.f_vars_s2)
```

```{r sr-clean-s2}
# MODERN RACISM
# GROUP ITEMS ---------------------------
sr_vars_s2 <- dplyr::select(s2, sr_hard, sr_minorities, sr_demand, sr_tension, sr_complain_r, sr_discrim_r, sr_slavery_r, sr_deserve_r, sr_change, sr_deserve_r, sr_econ)
sr_vars.names_s2 <- names(sr_vars_s2)

# CORRELATIONS ---------------------------
# correlation matrix
sr_cormat_s2 <- cor(sr_vars_s2, use = "complete.obs") 
sr_cormat_s2 <- round(sr_cormat_s2, 3)

# correlation plot with psych package
png(filename="/Users/cintiahinojosa/Box/Dissertation/images/sr_corplot_s2.png", height = 700, width = 1000)
psych::corPlot(sr_vars_s2 # labels = sr_vars.labels_s2
               , scale = TRUE, upper = FALSE, alpha = 0.5
               , main = "Correlation Matrix of Modern Racism Items in Study 2") #stars = FALSE, 
dev.off()

# correlation plot with corrgram package
png(filename="/Users/cintiahinojosa/Box/Dissertation/images/sr_corrgram_s2.png", height = 700, width = 1000)
corrgram::corrgram(sr_vars_s2
         , main = "Correlation Matrix of Modern Racism Items in Study 2 (Ordered)"
         , lower.panel = panel.cor #panel.cor, panel.pts, panel.conf
#         , upper.panel =  NULL #panel.conf #panel.shade #NULL
#         , diag.panel = panel.txt #panel.density, panel.minmax
         , text.panel = panel.txt
         , order = TRUE # "PCA" = TRUE
         , col.regions = colorRampPalette(c("red4", "grey", "darkgreen"))
           )
dev.off()

# CREATE MEAN COMPOSITE ---------------------------
freq(s2$sr_discrim_r)
s2$sr <- rowMeans(subset(s2, select = sr_vars.names_s2), na.rm = TRUE)
summary(s2$sr)
sr_alpha_s2 <- ltm::cronbach.alpha(sr_vars_s2)
papaja::printnum(sr_alpha_s2$alpha) # .088

# CREATE SUMMARY COMPOSITE ---------------------------
s2$sr.s <- rowSums(subset(s2, select = sr_vars.names_s2), na.rm = TRUE)
summary(s2$sr.s)

# GRAND-MEAN CENTER & STANDARDIZE ---------------------------
s2 <- s2 %>%
  mutate(sr.c = scale(sr, center = TRUE, scale = TRUE)
         , sr.sc = scale(sr.s, center = TRUE, scale = TRUE)
         , sr_hard.c = scale(sr_hard, center = TRUE, scale = TRUE)
         , sr_minorities.c = scale(sr_minorities, center = TRUE, scale = TRUE)
         , sr_demand.c = scale(sr_demand, center = TRUE, scale = TRUE)
         , sr_tension.c = scale(sr_tension, center = TRUE, scale = TRUE)
         , sr_complain_r.c = scale(sr_complain_r, center = TRUE, scale = TRUE)
         , sr_discrim_r.c = scale(sr_discrim_r, center = TRUE, scale = TRUE)
         , sr_slavery_r.c = scale(sr_slavery_r, center = TRUE, scale = TRUE)
         , sr_change.c = scale(sr_change, center = TRUE, scale = TRUE)
         , sr_deserve_r.c = scale(sr_deserve_r, center = TRUE, scale = TRUE)
         , sr_econ.c = scale(sr_econ, center = TRUE, scale = TRUE)
  )
summary(s2$sr.c)

# GROUP STANDARDIZED ITEMS ---------------------------
sr.c_vars_s2 <- dplyr::select(s2, sr_hard.c, sr_minorities.c, sr_demand.c, sr_complain_r.c, sr_slavery_r.c, sr_deserve_r.c, sr_econ.c, sr_tension.c, sr_discrim_r.c, sr_change.c)
sr.c_vars.names_s2 <- names(sr.c_vars_s2)
sr.c_alpha_s2 <- ltm::cronbach.alpha(sr.c_vars_s2)
papaja::printnum(sr.c_alpha_s2$alpha) # .889 

# FACTOR VARS ---------------------------
s2$sr_slavery_r.f <- factor(s2$sr_slavery_r, levels = c(1:7), labels = agree7.labels, ordered = TRUE)
s2$sr_change.f <- factor(s2$sr_change, levels = c(1:5), labels = amount5.labels, ordered = TRUE)
s2$sr_discrim_r.f <- factor(s2$sr_discrim_r, levels = c(1:5), labels = amount5.labels, ordered = TRUE)
s2$sr_deserve_r.f <- factor(s2$sr_deserve_r, levels = c(1:7), labels = agree7.labels, ordered = TRUE)
s2$sr_econ.f <- factor(s2$sr_econ, levels = c(1:7), labels = agree7.labels, ordered = TRUE)
s2$sr_hard.f <- factor(s2$sr_hard, levels = c(1:7), labels = agree7.labels, ordered = TRUE)
s2$sr_minorities.f <- factor(s2$sr_minorities, levels = c(1:7), labels = agree7.labels, ordered = TRUE)
s2$sr_demand.f <- factor(s2$sr_demand, levels = c(1:7), labels = agree7.labels, ordered = TRUE)
s2$sr_complain_r.f <- factor(s2$sr_complain_r, levels = c(1:7), labels = agree7.labels, ordered = TRUE)
s2$sr_tension.f <- factor(s2$sr_tension, levels = c(1:5), labels = amount5.labels, ordered = TRUE)

# RENAMED VARS ---------------------------
# RIGHT ORDER
# sr_hard + sr_minorities + sr_demand + sr_tension + sr_complain_r + sr_discrim_r + sr_slavery_r + sr_deserve_r + sr_change + sr_deserve_r + sr_econ
# sr_hard, sr_minorities, sr_demand, sr_tension, sr_complain_r, sr_discrim_r, sr_slavery_r, sr_deserve_r, sr_change, sr_deserve_r, sr_econ

# s1$isr1.hard <- s1$sr_hard
# s1$isr2.minorities <- s1$sr_minorities
# s1$isr3.demand <- s1$sr_demand
# s1$isr4.tension <- s1$sr_tension
# s1$isr5.complain <- s1$sr_complain_r
# s1$esr6.discrim <- s1$sr_discrim_r
# s1$esr7.slavery <- s1$sr_slavery_r
# s1$esr8.change <- s1$sr_change
# s1$esr9.deserve <- s1$sr_deserve_r
# s1$esr10.econ <- s1$sr_econ
# 
# s1$isr1.hard.c <- s1$sr_hard.c
# s1$isr2.minorities.c <- s1$sr_minorities.c
# s1$isr3.demand.c <- s1$sr_demand.c
# s1$isr4.tension.c <- s1$sr_tension.c
# s1$isr5.complain.c <- s1$sr_complain_r.c
# s1$esr6.discrim.c <- s1$sr_discrim_r.c
# s1$esr7.slavery.c <- s1$sr_slavery_r.c
# s1$esr8.change.c <- s1$sr_change.c
# s1$esr9.deserve.c <- s1$sr_deserve_r.c
# s1$esr10.econ.c <- s1$sr_econ.c
```

```{r sre-clean-s2}
# EXTERNAL MODERN RACISM
# GROUP ITEMS ---------------------------
sre_vars_s2 <- dplyr::select(s2, c(sr_slavery_r, sr_change, sr_discrim_r, sr_deserve_r, sr_econ))
sre_vars.names_s2 <- names(sre_vars_s2)

# CORRELATIONS ---------------------------
# correlation matrix
sre_cormat_s2 <- cor(sre_vars_s2, use = "complete.obs") 
sre_cormat_s2 <- round(sre_cormat_s2, 3)

# correlation plot with psych package
png(filename="/Users/cintiahinojosa/Box/Dissertation/images/sre_corplot_s2.png", height = 700, width = 1000)
psych::corPlot(sre_vars_s2 # labels = sre_vars.labels_s2
               , scale = TRUE, upper = FALSE, alpha = 0.5
               , main = "Correlation Matrix of External Modern Racism Items in Study 2") #stars = FALSE, 
dev.off()

# correlation plot with corrgram package
png(filename="/Users/cintiahinojosa/Box/Dissertation/images/sre_corrgram_s2.png", height = 700, width = 1000)
corrgram::corrgram(sre_vars_s2
         , main = "Correlation Matrix of External Modern Racism Items in Study 2 (Ordered)"
         , lower.panel = panel.cor #panel.cor, panel.pts, panel.conf
#         , upper.panel =  NULL #panel.conf #panel.shade #NULL
#         , diag.panel = panel.txt #panel.density, panel.minmax
         , text.panel = panel.txt
         , order = TRUE # "PCA" = TRUE
         , col.regions = colorRampPalette(c("red4", "grey", "darkgreen"))
           )
dev.off()

# CREATE MEAN COMPOSITE ---------------------------
freq(s2$sr_discrim_r)
s2$sre <- rowMeans(subset(s2, select = sre_vars.names_s2), na.rm = TRUE)
summary(s2$sre)
sre_alpha_s2 <- ltm::cronbach.alpha(sre_vars_s2)
papaja::printnum(sre_alpha_s2$alpha) # .788

# CREATE SUMMARY COMPOSITE ---------------------------
s2$sre.s <- rowSums(subset(s2, select = sre_vars.names_s2), na.rm = TRUE)
summary(s2$sre.s)

# GRAND-MEAN CENTER & STANDARDIZE ---------------------------
s2 <- s2 %>%
  mutate(sre.c = scale(sre, center = TRUE, scale = TRUE)
    , sre.sc = scale(sre.s, center = TRUE, scale = TRUE)
    )
summary(s2$sre.c)

# GROUP STANDARDIZED ITEMS ---------------------------
sre.c_vars_s2 <- dplyr::select(s2, sr_slavery_r.c, sr_change.c, sr_discrim_r.c, sr_deserve_r.c, sr_econ.c)
sre.c_vars.names_s2 <- names(sre.c_vars_s2)
sre.c_alpha_s2 <- ltm::cronbach.alpha(sre.c_vars_s2)
papaja::printnum(sre.c_alpha_s2$alpha) # .791
```

```{r sri-clean-s2}
# INTERNAL MODERN RACISM
# GROUP ITEMS ---------------------------
sri_vars_s2 <- dplyr::select(s2, c(sr_hard, sr_minorities, sr_demand, sr_complain_r, sr_tension))
sri_vars.names_s2 <- names(sri_vars_s2)

# CORRELATIONS
# correlation matrix
sri_cormat_s2 <- cor(sri_vars_s2, use = "complete.obs") 
sri_cormat_s2 <- round(sri_cormat_s2, 3)

# correlation plot with psych package
png(filename="/Users/cintiahinojosa/Box/Dissertation/images/sri_corplot_s2.png", height = 700, width = 1000)
psych::corPlot(sri_vars_s2 # labels = sri_vars.labels_s2
               , scale = TRUE, upper = FALSE, alpha = 0.5
               , main = "Correlation Matrix of Internal Modern Racism Items in Study 2") #stars = FALSE, 
dev.off()

# correlation plot with corrgram package
png(filename="/Users/cintiahinojosa/Box/Dissertation/images/sri_corrgram_s2.png", height = 700, width = 1000)
corrgram::corrgram(sri_vars_s2
         , main = "Correlation Matrix of Internal Modern Racism Items in Study 2 (Ordered)"
         , lower.panel = panel.cor #panel.cor, panel.pts, panel.conf
#         , upper.panel =  NULL #panel.conf #panel.shade #NULL
#         , diag.panel = panel.txt #panel.density, panel.minmax
         , text.panel = panel.txt
         , order = TRUE # "PCA" = TRUE
         , col.regions = colorRampPalette(c("red4", "grey", "darkgreen"))
           )
dev.off()

# CREATE MEAN COMPOSITE ---------------------------
freq(s2$sr_discrim_r)
s2$sri <- rowMeans(subset(s2, select = sri_vars.names_s2), na.rm = TRUE)
summary(s2$sri)
sri_alpha_s2 <- ltm::cronbach.alpha(sri_vars_s2) 
papaja::printnum(sri_alpha_s2$alpha) # 

# CREATE SUMMARY COMPOSITE ---------------------------
s2$sri.s <- rowSums(subset(s2, select = sri_vars.names_s2), na.rm = TRUE)
summary(s2$sri.s)

# GRAND-MEAN CENTER & STANDARDIZE ---------------------------
s2 <- s2 %>%
  mutate(sri.c = scale(sri, center = TRUE, scale = TRUE)
    , sri.sc = scale(sri.s, center = TRUE, scale = TRUE)
    )
summary(s2$sri.c)

# GROUP STANDARDIZED ITEMS ---------------------------
sri.c_vars_s2 <- dplyr::select(s2, sr_hard.c, sr_minorities.c, sr_demand.c, sr_complain_r.c, sr_tension.c)
sri.c_vars.names_s2 <- names(sri.c_vars_s2)
sri.c_alpha_s2 <- ltm::cronbach.alpha(sri.c_vars_s2)
papaja::printnum(sri.c_alpha_s2$alpha) #
```

```{r gun4-clean-s2}
# URBAN GUN VIOLENCE STEREOTYPES
# GROUP ITEMS ---------------------------
gunbeliefs4_vars_s2 <- dplyr::select(s2, c(gun_street, gun_parent, gun_punish, gun_work))
gunbeliefs4_vars.names_s2 <- names(gunbeliefs4_vars_s2)

# CORRELATIONS
# correlation matrix
gunbeliefs4_cormat_s2 <- cor(gunbeliefs4_vars_s2, use = "complete.obs") 
gunbeliefs4_cormat_s2 <- round(gunbeliefs4_cormat_s2, 3)

# correlation plot with psych package
png(filename="/Users/cintiahinojosa/Box/Dissertation/images/gunbeliefs4_corplot_s2.png", height = 700, width = 1000)
psych::corPlot(gunbeliefs4_vars_s2 # labels = gunbeliefs4_vars.labels_s2
               , scale = TRUE, upper = FALSE, alpha = 0.5
               , main = "Correlation Matrix of Urban Gun Violence Attitudes in Study 2") #stars = FALSE, 
dev.off()

# correlation plot with corrgram package
png(filename="/Users/cintiahinojosa/Box/Dissertation/images/gunbeliefs4_corrgram_s2.png", height = 700, width = 1000)
corrgram::corrgram(gunbeliefs4_vars_s2
         , main = "Correlation Matrix of Urban Gun Violence Attitudes in Study 2 (Ordered)"
         , lower.panel = panel.cor #panel.cor, panel.pts, panel.conf
#         , upper.panel =  NULL #panel.conf #panel.shade #NULL
#         , diag.panel = panel.txt #panel.density, panel.minmax
         , text.panel = panel.txt
         , order = TRUE # "PCA" = TRUE
         , col.regions = colorRampPalette(c("red4", "grey", "darkgreen"))
           )
dev.off()

# CREATE COMPOSITE ---------------------------
freq(s2$gun_street)
s2$gunbeliefs4 <- rowMeans(subset(s2, select = gunbeliefs4_vars.names_s2), na.rm = TRUE)
summary(s2$gunbeliefs4)
gunbeliefs4_alpha_s2 <- ltm::cronbach.alpha(gunbeliefs4_vars_s2) 
papaja::printnum(gunbeliefs4_alpha_s2$alpha) # 

# GRAND-MEAN CENTER & STANDARDIZE ---------------------------
s2 <- s2 %>%
  mutate(gunbeliefs4.c = scale(gunbeliefs4, center = TRUE, scale = TRUE)
         , gun_street.c = scale(gun_street, center = TRUE, scale = TRUE)
         , gun_parent.c = scale(gun_parent, center = TRUE, scale = TRUE)
         , gun_punish.c = scale(gun_punish, center = TRUE, scale = TRUE)
         , gun_work.c = scale(gun_work, center = TRUE, scale = TRUE)
         )
summary(s2$gunbeliefs4.c)
summary(s2$gun_street.c)

# GROUP STANDARDIZED ITEMS ---------------------------
gunbeliefs4.c_vars_s2 <- dplyr::select(s2, gun_street.c, gun_parent.c, gun_punish.c, gun_work.c)
gunbeliefs4.c_vars.names_s2 <- names(gunbeliefs4.c_vars_s2)
gunbeliefs4.c_alpha_s2 <- ltm::cronbach.alpha(gunbeliefs4.c_vars_s2)
papaja::printnum(gunbeliefs4.c_alpha_s2$alpha) #
```

```{r gun-clean-s2}
# URBAN GUN VIOLENCE STEREOTYPES
# GROUP ITEMS ---------------------------
gunbeliefs_vars_s2 <- dplyr::select(s2, c(gun_street, gun_parent, gun_punish))
gunbeliefs_vars.names_s2 <- names(gunbeliefs_vars_s2)

# CORRELATIONS
# correlation matrix
gunbeliefs_cormat_s2 <- cor(gunbeliefs_vars_s2, use = "complete.obs") 
gunbeliefs_cormat_s2 <- round(gunbeliefs_cormat_s2, 3)

# correlation plot with psych package
png(filename="/Users/cintiahinojosa/Box/Dissertation/images/gunbeliefs_corplot_s2.png", height = 700, width = 1000)
psych::corPlot(gunbeliefs_vars_s2 # labels = gunbeliefs_vars.labels_s2
               , scale = TRUE, upper = FALSE, alpha = 0.5
               , main = "Correlation Matrix of Urban Gun Violence Attitudes in Study 2") #stars = FALSE, 
dev.off()

# correlation plot with corrgram package
png(filename="/Users/cintiahinojosa/Box/Dissertation/images/gunbeliefs_corrgram_s2.png", height = 700, width = 1000)
corrgram::corrgram(gunbeliefs_vars_s2
         , main = "Correlation Matrix of Urban Gun Violence Attitudes in Study 2 (Ordered)"
         , lower.panel = panel.cor #panel.cor, panel.pts, panel.conf
#         , upper.panel =  NULL #panel.conf #panel.shade #NULL
#         , diag.panel = panel.txt #panel.density, panel.minmax
         , text.panel = panel.txt
         , order = TRUE # "PCA" = TRUE
         , col.regions = colorRampPalette(c("red4", "grey", "darkgreen"))
           )
dev.off()

# CREATE COMPOSITE ---------------------------
freq(s2$gun_street)
s2$gunbeliefs <- rowMeans(subset(s2, select = gunbeliefs_vars.names_s2), na.rm = TRUE)
summary(s2$gunbeliefs)
gunbeliefs_alpha_s2 <- ltm::cronbach.alpha(gunbeliefs_vars_s2) 
papaja::printnum(gunbeliefs_alpha_s2$alpha) # 

# GRAND-MEAN CENTER & STANDARDIZE ---------------------------
s2 <- s2 %>%
  mutate(gunbeliefs.c = scale(gunbeliefs, center = TRUE, scale = TRUE))
summary(s2$gunbeliefs.c)

# GROUP STANDARDIZED ITEMS ---------------------------
gunbeliefs.c_vars_s2 <- dplyr::select(s2, gun_street.c, gun_parent.c, gun_punish.c)
gunbeliefs.c_vars.names_s2 <- names(gunbeliefs.c_vars_s2)
gunbeliefs.c_alpha_s2 <- ltm::cronbach.alpha(gunbeliefs.c_vars_s2)
papaja::printnum(gunbeliefs.c_alpha_s2$alpha) #
```

```{r ineq-clean-s2}
# PERCEIVED INEQUALITY
# GROUP ITEMS ---------------------------
# inequality
inequality_vars_s2 <- dplyr::select(s2, c(ineq_edurace, ineq_edupoor, ineq_edufem, ineq_jobrace, ineq_jobpoor, ineq_jobfem,ineq_chancerace, ineq_chancepoor, ineq_chancefem))
inequality_vars.names_s2 <- names(inequality_vars_s2)

# inequality_edu
inequality.edu_vars_s2 <- dplyr::select(s2, c(ineq_edurace, ineq_edupoor, ineq_edufem, ineq_chancefem))
inequality.edu_vars.names_s2 <- names(inequality.edu_vars_s2)

# inequality_job
inequality.job_vars_s2 <- dplyr::select(s2, c(ineq_jobrace, ineq_jobpoor, ineq_jobfem))
inequality.job_vars.names_s2 <- names(inequality.job_vars_s2)

# inequality_chance
inequality.chance_vars_s2 <- dplyr::select(s2, c(ineq_chancerace, ineq_chancepoor, ineq_chancefem))
inequality.chance_vars.names_s2 <- names(inequality.chance_vars_s2)

# inequality_race
inequality.race_vars_s2 <- dplyr::select(s2, c(ineq_edurace, ineq_jobrace, ineq_chancerace))
inequality.race_vars.names_s2 <- names(inequality.race_vars_s2)

# inequality_poor
inequality.poor_vars_s2 <- dplyr::select(s2, c(ineq_edupoor, ineq_jobpoor, ineq_chancepoor))
inequality.poor_vars.names_s2 <- names(inequality.poor_vars_s2)

# inequality_fem
inequality.fem_vars_s2 <- dplyr::select(s2, c(ineq_edufem, ineq_jobfem, ineq_chancefem))
inequality.fem_vars.names_s2 <- names(inequality.fem_vars_s2)

# CORRELATIONS ---------------------------
# correlation matrix
inequality_cormat_s2 <- cor(inequality_vars_s2, use = "complete.obs") 
inequality_cormat_s2 <- round(inequality_cormat_s2, 3)

# correlation plot with psych package
png(filename="/Users/cintiahinojosa/Box/Dissertation/images/inequality_corplot_s2.png", height = 700, width = 1000)
psych::corPlot(inequality_vars_s2 # labels = inequality_vars.labels_s2
               , scale = TRUE, upper = FALSE, alpha = 0.5
               , main = "Correlation Matrix of Perceived Inequality in Study 2") #stars = FALSE, 
dev.off()

# correlation plot with corrgram package
png(filename="/Users/cintiahinojosa/Box/Dissertation/images/inequality_corrgram_s2.png", height = 700, width = 1000)
corrgram::corrgram(inequality_vars_s2
         , main = "Correlation Matrix of Perceived Inequality in Study 2 (Ordered)"
         , lower.panel = panel.cor #panel.cor, panel.pts, panel.conf
#         , upper.panel =  NULL #panel.conf #panel.shade #NULL
#         , diag.panel = panel.txt #panel.density, panel.minmax
         , text.panel = panel.txt
         , order = TRUE # "PCA" = TRUE
         , col.regions = colorRampPalette(c("red4", "grey", "darkgreen"))
           )
dev.off()

# CREATE COMPOSITE ---------------------------
freq(s2$ineq_edurace)
# inequality
s2$inequality <- rowMeans(subset(s2, select = inequality_vars.names_s2), na.rm = TRUE)
summary(s2$inequality)
inequality_alpha_s2 <- ltm::cronbach.alpha(inequality_vars_s2) 
papaja::printnum(inequality_alpha_s2$alpha) # 

# inequality_edu
s2$inequality_edu <- rowMeans(subset(s2, select = inequality.edu_vars.names_s2), na.rm = TRUE)
summary(s2$inequality_edu)
inequality.edu_alpha_s2 <- ltm::cronbach.alpha(inequality.edu_vars_s2) 
papaja::printnum(inequality.edu_alpha_s2$alpha) # 

# inequality_job
s2$inequality_job <- rowMeans(subset(s2, select = inequality.job_vars.names_s2), na.rm = TRUE)
summary(s2$inequality_job)
inequality.job_alpha_s2 <- ltm::cronbach.alpha(inequality.job_vars_s2) 
papaja::printnum(inequality.job_alpha_s2$alpha) # 

# inequality_chance
s2$inequality_chance <- rowMeans(subset(s2, select = inequality.chance_vars.names_s2), na.rm = TRUE)
summary(s2$inequality_chance)
inequality.chance_alpha_s2 <- ltm::cronbach.alpha(inequality.chance_vars_s2) 
papaja::printnum(inequality.chance_alpha_s2$alpha) # 

# inequality_race
s2$inequality_race <- rowMeans(subset(s2, select = inequality.race_vars.names_s2), na.rm = TRUE)
summary(s2$inequality_race)
inequality.race_alpha_s2 <- ltm::cronbach.alpha(inequality.race_vars_s2) 
papaja::printnum(inequality.race_alpha_s2$alpha) # 

# inequality_poor
s2$inequality_poor <- rowMeans(subset(s2, select = inequality.poor_vars.names_s2), na.rm = TRUE)
summary(s2$inequality_poor)
inequality.poor_alpha_s2 <- ltm::cronbach.alpha(inequality.poor_vars_s2) 
papaja::printnum(inequality.poor_alpha_s2$alpha) # 

# inequality_fem
s2$inequality_fem <- rowMeans(subset(s2, select = inequality.fem_vars.names_s2), na.rm = TRUE)
summary(s2$inequality_fem)
inequality.fem_alpha_s2 <- ltm::cronbach.alpha(inequality.fem_vars_s2) 
papaja::printnum(inequality.fem_alpha_s2$alpha) # 

# GRAND-MEAN CENTER & STANDARDIZE ---------------------------
s2 <- s2 %>%
  mutate(inequality.c = scale(inequality, center = TRUE, scale = TRUE)
         , ineq_edurace.c = scale(ineq_edurace, center = TRUE, scale = TRUE)
         , ineq_edupoor.c = scale(ineq_edupoor, center = TRUE, scale = TRUE)
         , ineq_edufem.c = scale(ineq_edufem, center = TRUE, scale = TRUE)
         , ineq_jobrace.c = scale(ineq_jobrace, center = TRUE, scale = TRUE)
         , ineq_jobpoor.c = scale(ineq_jobpoor, center = TRUE, scale = TRUE)
         , ineq_jobfem.c = scale(ineq_jobfem, center = TRUE, scale = TRUE)
         , ineq_chancerace.c = scale(ineq_chancerace, center = TRUE, scale = TRUE)
         , ineq_chancepoor.c = scale(ineq_chancepoor, center = TRUE, scale = TRUE)
         , ineq_chancefem.c = scale(ineq_chancefem, center = TRUE, scale = TRUE)
         , inequality_edu.c = scale(inequality_edu, center = TRUE, scale = TRUE)
         , inequality_job.c = scale(inequality_job, center = TRUE, scale = TRUE)
         , inequality_chance.c = scale(inequality_chance, center = TRUE, scale = TRUE)
         , inequality_race.c = scale(inequality_race, center = TRUE, scale = TRUE)
         , inequality_poor.c = scale(inequality_poor, center = TRUE, scale = TRUE)
         , inequality_fem.c = scale(inequality_fem, center = TRUE, scale = TRUE)
         )
summary(s2$inequality.c)
summary(s2$ineq_edurace.c)

# GROUP STANDARDIZED ITEMS ---------------------------
inequality.c_vars_s2 <- dplyr::select(s2, ineq_edurace.c, ineq_edupoor.c, ineq_edufem.c, ineq_jobrace.c, ineq_jobpoor.c, ineq_jobfem.c,ineq_chancerace.c, ineq_chancepoor.c, ineq_chancefem.c)
inequality.c_vars.names_s2 <- names(inequality.c_vars_s2)
inequality.c_alpha_s2 <- ltm::cronbach.alpha(inequality.c_vars_s2)
papaja::printnum(inequality.c_alpha_s2$alpha) #

# FACTOR ---------------------------
s2$ineq_edurace.f <- factor(s2$ineq_edurace, levels = c(1:7), labels = agree7.labels, ordered = TRUE)
s2$ineq_edupoor.f <- factor(s2$ineq_edupoor, levels = c(1:7), labels = agree7.labels, ordered = TRUE)
s2$ineq_edufem.f <- factor(s2$ineq_edufem, levels = c(1:7), labels = agree7.labels, ordered = TRUE)
s2$ineq_jobrace.f <- factor(s2$ineq_jobrace, levels = c(1:7), labels = agree7.labels, ordered = TRUE)
s2$ineq_jobfem.f <- factor(s2$ineq_jobfem, levels = c(1:7), labels = agree7.labels, ordered = TRUE)
s2$ineq_jobpoor.f <- factor(s2$ineq_jobpoor, levels = c(1:7), labels = agree7.labels, ordered = TRUE)
s2$ineq_chancerace.f <- factor(s2$ineq_chancerace, levels = c(1:7), labels = agree7.labels, ordered = TRUE)
s2$ineq_chancefem.f <- factor(s2$ineq_chancefem, levels = c(1:7), labels = agree7.labels, ordered = TRUE)
s2$ineq_chancepoor.f <- factor(s2$ineq_chancepoor, levels = c(1:7), labels = agree7.labels, ordered = TRUE)
```

```{r egal-clean-s2}
# EGALITARIANISM
# GROUP ITEMS ---------------------------
egalitarian_vars_s2 <- dplyr::select(s2, egal_good, egal_hierarchy, egal_ideal, egal_lessprobs, egal_chance)
egalitarian_vars.names_s2 <- names(egalitarian_vars_s2)

# CORRELATIONS ---------------------------
# correlation matrix
egalitarian_cormat_s2 <- cor(egalitarian_vars_s2, use = "complete.obs") 
egalitarian_cormat_s2 <- round(egalitarian_cormat_s2, 3)

# correlation plot with psych package
png(filename="/Users/cintiahinojosa/Box/Dissertation/images/egalitarian_corplot_s2.png", height = 700, width = 1000)
psych::corPlot(egalitarian_vars_s2 # labels = egalitarian_vars.labels_s2
               , scale = TRUE, upper = FALSE, alpha = 0.5
               , main = "Correlation Matrix of Egalitarianism Items in Study 2") #stars = FALSE, 
dev.off()

# correlation plot with corrgram package
png(filename="/Users/cintiahinojosa/Box/Dissertation/images/egalitarian_corrgram_s2.png", height = 700, width = 1000)
corrgram::corrgram(egalitarian_vars_s2
         , main = "Correlation Matrix of Egalitarianism Items in Study 2 (Ordered)"
         , lower.panel = panel.cor #panel.cor, panel.pts, panel.conf
#         , upper.panel =  NULL #panel.conf #panel.shade #NULL
#         , diag.panel = panel.txt #panel.density, panel.minmax
         , text.panel = panel.txt
         , order = TRUE # "PCA" = TRUE
         , col.regions = colorRampPalette(c("red4", "grey", "darkgreen"))
           )
dev.off()

# CREATE COMPOSITE ---------------------------
freq(s2$egal_good)
s2$egalitarian <- rowMeans(subset(s2, select = egalitarian_vars.names_s2), na.rm = TRUE)
summary(s2$egalitarian)
egalitarian_alpha_s2 <- ltm::cronbach.alpha(egalitarian_vars_s2)
papaja::printnum(egalitarian_alpha_s2$alpha) # .80

# GRAND-MEAN CENTER & STANDARDIZE ---------------------------
s2 <- s2 %>%
  mutate(egalitarian.c = scale(egalitarian, center = TRUE, scale = TRUE)
         , egal_good.c = scale(egal_good, center = TRUE, scale = TRUE)
         , egal_hierarchy.c = scale(egal_hierarchy, center = TRUE, scale = TRUE)
         , egal_ideal.c = scale(egal_ideal, center = TRUE, scale = TRUE)
         , egal_lessprobs.c = scale(egal_lessprobs, center = TRUE, scale = TRUE)
         , egal_chance.c = scale(egal_chance, center = TRUE, scale = TRUE)
         )
summary(s2$egalitarian.c)
summary(s2$egal_good.c)

# GROUP STANDARDIZED ITEMS ---------------------------
egalitarian.c_vars_s2 <- dplyr::select(s2, egal_good.c, egal_hierarchy.c, egal_ideal.c, egal_lessprobs.c, egal_chance.c)
egalitarian.c_vars.names_s2 <- names(egalitarian.c_vars_s2)
egalitarian.c_alpha_s2 <- ltm::cronbach.alpha(egalitarian.c_vars_s2)
papaja::printnum(egalitarian.c_alpha_s2$alpha) # .82
```

```{r nfc-clean-s2}
# NEED FOR COGNITION
# GROUP ITEMS ---------------------------
# nfc_simple, nfc_resp, nfc_notfun_r, nfc_nochallenge_r, nfc_avoid_r, nfc_satisfy, nfc_only_r, nfc_daily_r, nfc_little_r, nfc_rely, nfc_solutions, nfc_excite_r, nfc_puzzles,  nfc_abstract, nfc_difficult, nfc_relief_r, nfc_done_r, nfc_deliberate
nfc_vars_s2 <- dplyr::select(s2, nfc_simple, nfc_resp, nfc_notfun_r, nfc_nochallenge_r, nfc_avoid_r, nfc_satisfy, nfc_only_r, nfc_daily_r, nfc_little_r, nfc_rely , nfc_solutions, nfc_unexcite_r, nfc_puzzles, nfc_abstract, nfc_difficult, nfc_relief_r, nfc_done_r, nfc_deliberate)
nfc_vars.names_s2 <- names(nfc_vars_s2)

# CORRELATIONS ---------------------------
# correlation matrix
nfc_cormat_s2 <- cor(nfc_vars_s2, use = "complete.obs") 
nfc_cormat_s2 <- round(nfc_cormat_s2, 3)

# correlation plot with psych package
png(filename="/Users/cintiahinojosa/Box/Dissertation/images/nfc_corplot_s2.png", height = 700, width = 1000)
psych::corPlot(nfc_vars_s2 # labels = nfc_vars.labels_s2
               , scale = TRUE, upper = FALSE, alpha = 0.5
               , main = "Correlation Matrix of Punitive Policy Support Items in Study 2") #stars = FALSE, 
dev.off()

# correlation plot with corrgram package
png(filename="/Users/cintiahinojosa/Box/Dissertation/images/nfc_corrgram_s2.png", height = 700, width = 1000)
corrgram::corrgram(nfc_vars_s2
         , main = "Correlation Matrix of Punitive Policy Support Items in Study 2 (Ordered)"
         , lower.panel = panel.cor #panel.cor, panel.pts, panel.conf
#         , upper.panel =  NULL #panel.conf #panel.shade #NULL
#         , diag.panel = panel.txt #panel.density, panel.minmax
         , text.panel = panel.txt
         , order = TRUE # "PCA" = TRUE
         , col.regions = colorRampPalette(c("red4", "grey", "darkgreen"))
           )
dev.off()

# CREATE COMPOSITE ---------------------------
freq(s2$nfc_simple)
s2$nfc <- rowMeans(subset(s2, select = nfc_vars.names_s2), na.rm = TRUE)
summary(s2$nfc)
nfc_alpha_s2 <- ltm::cronbach.alpha(nfc_vars_s2)
papaja::printnum(nfc_alpha_s2$alpha) # 0.84

# GRAND-MEAN CENTER & STANDARDIZE ---------------------------
s2 <- s2 %>%
  mutate(nfc.c = scale(nfc, center = TRUE, scale = TRUE)
         , nfc_simple.c = scale(nfc_simple, center = TRUE, scale = TRUE)
         , nfc_resp.c = scale(nfc_resp, center = TRUE, scale = TRUE)
         , nfc_notfun_r.c = scale(nfc_notfun_r, center = TRUE, scale = TRUE)
         , nfc_nochallenge_r.c = scale(nfc_nochallenge_r, center = TRUE, scale = TRUE)
         , nfc_avoid_r.c = scale(nfc_avoid_r, center = TRUE, scale = TRUE)
         , nfc_satisfy.c = scale(nfc_satisfy, center = TRUE, scale = TRUE)
         , nfc_only_r.c = scale(nfc_only_r, center = TRUE, scale = TRUE)
         , nfc_daily_r.c = scale(nfc_daily_r, center = TRUE, scale = TRUE)
         , nfc_little_r.c = scale(nfc_little_r, center = TRUE, scale = TRUE)
         , nfc_rely.c = scale(nfc_rely, center = TRUE, scale = TRUE)
         , nfc_solutions.c = scale(nfc_solutions, center = TRUE, scale = TRUE)
         , nfc_unexcite_r.c = scale(nfc_unexcite_r, center = TRUE, scale = TRUE)
         , nfc_puzzles.c = scale(nfc_puzzles, center = TRUE, scale = TRUE)
         , nfc_abstract.c = scale(nfc_abstract, center = TRUE, scale = TRUE)
         , nfc_difficult.c = scale(nfc_difficult, center = TRUE, scale = TRUE)
         , nfc_relief_r.c = scale(nfc_relief_r, center = TRUE, scale = TRUE)
         , nfc_done_r.c = scale(nfc_done_r, center = TRUE, scale = TRUE)
         , nfc_deliberate.c = scale(nfc_deliberate, center = TRUE, scale = TRUE)
         , nfc_notfun.c = scale(nfc_notfun, center = TRUE, scale = TRUE)
         , nfc_nochallenge.c = scale(nfc_nochallenge, center = TRUE, scale = TRUE)
         , nfc_avoid.c = scale(nfc_avoid, center = TRUE, scale = TRUE)
         , nfc_only.c = scale(nfc_only, center = TRUE, scale = TRUE)
         , nfc_daily.c = scale(nfc_daily, center = TRUE, scale = TRUE)
         , nfc_little.c = scale(nfc_little, center = TRUE, scale = TRUE)
         , nfc_unexcite.c = scale(nfc_unexcite, center = TRUE, scale = TRUE)
         , nfc_relief.c = scale(nfc_relief, center = TRUE, scale = TRUE)
         , nfc_done.c = scale(nfc_done, center = TRUE, scale = TRUE)
         )
summary(s2$nfc.c)
summary(s2$nfc_done.c)
summary(s2$nfc_done_r.c)

# GROUP STANDARDIZED ITEMS ---------------------------
nfc.c_vars_s2 <- dplyr::select(s2, nfc_simple.c, nfc_resp.c, nfc_notfun_r.c, nfc_nochallenge_r.c, nfc_avoid_r.c, nfc_satisfy.c, nfc_only_r.c, nfc_daily_r.c, nfc_little_r.c, nfc_rely.c, nfc_solutions.c, nfc_unexcite_r.c, nfc_puzzles.c, nfc_abstract.c, nfc_difficult.c, nfc_relief_r.c, nfc_done_r.c, nfc_deliberate.c)
nfc.c_vars.names_s2 <- names(nfc.c_vars_s2)
nfc.c_alpha_s2 <- ltm::cronbach.alpha(nfc.c_vars_s2)
papaja::printnum(nfc.c_alpha_s2$alpha) # .87

# FACTOR VARS ---------------------------
s2$nfc_simple.f <- factor(s2$nfc_simple, levels =1:5, labels = amount5.nfc.labels, ordered = FALSE)
s2$nfc_resp.f <- factor(s2$nfc_resp, levels =1:5, labels = amount5.nfc.labels, ordered = FALSE)
s2$nfc_notfun_r.f <- factor(s2$nfc_notfun_r, levels =1:5, labels = amount5.nfc.labels, ordered = FALSE)
s2$nfc_nochallenge_r.f <- factor(s2$nfc_nochallenge_r, levels =1:5, labels = amount5.nfc.labels, ordered = FALSE)
s2$nfc_avoid_r.f <- factor(s2$nfc_avoid_r, levels =1:5, labels = amount5.nfc.labels, ordered = FALSE)
s2$nfc_satisfy.f <- factor(s2$nfc_satisfy, levels =1:5, labels = amount5.nfc.labels, ordered = FALSE)
s2$nfc_only_r.f <- factor(s2$nfc_only_r, levels =1:5, labels = amount5.nfc.labels, ordered = FALSE)
s2$nfc_daily_r.f <- factor(s2$nfc_daily_r, levels =1:5, labels = amount5.nfc.labels, ordered = FALSE)
s2$nfc_little_r.f <- factor(s2$nfc_little_r, levels =1:5, labels = amount5.nfc.labels, ordered = FALSE)
s2$nfc_rely.f <- factor(s2$nfc_rely , levels =1:5, labels = amount5.nfc.labels, ordered = FALSE)
s2$nfc_solutions.f <- factor(s2$nfc_solutions, levels =1:5, labels = amount5.nfc.labels, ordered = FALSE)
s2$nfc_unexcite_r.f <- factor(s2$nfc_unexcite_r, levels =1:5, labels = amount5.nfc.labels, ordered = FALSE)
s2$nfc_puzzles.f <- factor(s2$nfc_puzzles, levels =1:5, labels = amount5.nfc.labels, ordered = FALSE)
s2$nfc_abstract.f <- factor(s2$nfc_abstract, levels =1:5, labels = amount5.nfc.labels, ordered = FALSE)
s2$nfc_difficult.f <- factor(s2$nfc_difficult, levels =1:5, labels = amount5.nfc.labels, ordered = FALSE)
s2$nfc_relief_r.f <- factor(s2$nfc_relief_r, levels =1:5, labels = amount5.nfc.labels, ordered = FALSE)
s2$nfc_done_r.f <- factor(s2$nfc_done_r, levels =1:5, labels = amount5.nfc.labels, ordered = FALSE)
s2$nfc_deliberate.f <- factor(s2$nfc_deliberate, levels =1:5, labels = amount5.nfc.labels, ordered = FALSE)

```

```{r police-clean-s2}
# ATTITUDES TOWARDS POLICE EXPERTS
# GROUP ITEMS ---------------------------
# police_trust
police_vars_s2 <- dplyr::select(s2, police_trust, police_qualify)
police_vars.names_s2 <- names(police_vars_s2)

# CORRELATIONS ---------------------------
# correlation matrix
police_cormat_s2 <- cor(police_vars_s2, use = "complete.obs") 
police_cormat_s2 <- round(police_cormat_s2, 3)

# correlation plot with psych package
png(filename="/Users/cintiahinojosa/Box/Dissertation/images/police_corplot_s2.png", height = 700, width = 1000)
psych::corPlot(police_vars_s2 # labels = police_vars.labels_s2
               , scale = TRUE, upper = FALSE, alpha = 0.5
               , main = "Correlation Matrix of Attittudes Towards Police Items in Study 2") #stars = FALSE, 
dev.off()

# correlation plot with corrgram package
png(filename="/Users/cintiahinojosa/Box/Dissertation/images/police_corrgram_s2.png", height = 700, width = 1000)
corrgram::corrgram(police_vars_s2
         , main = "Correlation Matrix of Attittudes Towards Police Items in Study 2 (Ordered)"
         , lower.panel = panel.cor #panel.cor, panel.pts, panel.conf
#         , upper.panel =  NULL #panel.conf #panel.shade #NULL
#         , diag.panel = panel.txt #panel.density, panel.minmax
         , text.panel = panel.txt
         , order = TRUE # "PCA" = TRUE
         , col.regions = colorRampPalette(c("red4", "grey", "darkgreen"))
           )
dev.off()

# CREATE COMPOSITE ---------------------------
freq(s2$police_trust)
s2$police <- rowMeans(subset(s2, select = police_vars.names_s2), na.rm = TRUE)
summary(s2$police)
police_alpha_s2 <- ltm::cronbach.alpha(police_vars_s2)
papaja::printnum(police_alpha_s2$alpha) # 

# GRAND-MEAN CENTER & STANDARDIZE ---------------------------
s2 <- s2 %>%
  mutate(police.c = scale(police, center = TRUE, scale = TRUE)
         , police_trust.c = scale(police_trust, center = TRUE, scale = TRUE)
         , police_qualify.c = scale(police_qualify, center = TRUE, scale = TRUE)
         )
summary(s2$police.c)
summary(s2$police_trust.c)

# GROUP STANDARDIZED ITEMS ---------------------------
police.c_vars_s2 <- dplyr::select(s2, police_trust.c, police_qualify.c)
police.c_vars.names_s2 <- names(police.c_vars_s2)
police.c_alpha_s2 <- ltm::cronbach.alpha(police.c_vars_s2)
papaja::printnum(police.c_alpha_s2$alpha) # .88

# FACTOR ---------------------------
s2$police_trust.f <- factor(s2$police_trust, levels = c(1:7), labels = trust7.labels, ordered = TRUE)
s2$police_qualify.f <- factor(s2$police_qualify, levels = c(1:7), labels = qualify7.labels, ordered = TRUE)
```

```{r policy-clean-s2}
# ATTITUDES TOWARDS POLICE EXPERTS
# GROUP ITEMS ---------------------------
# policy_trust
policy_vars_s2 <- dplyr::select(s2, policy_trust, policy_qualify)
policy_vars.names_s2 <- names(policy_vars_s2)

# CORRELATIONS ---------------------------
# correlation matrix
policy_cormat_s2 <- cor(policy_vars_s2, use = "complete.obs") 
policy_cormat_s2 <- round(policy_cormat_s2, 3)

# correlation plot with psych package
png(filename="/Users/cintiahinojosa/Box/Dissertation/images/policy_corplot_s2.png", height = 700, width = 1000)
psych::corPlot(policy_vars_s2 # labels = policy_vars.labels_s2
               , scale = TRUE, upper = FALSE, alpha = 0.5
               , main = "Correlation Matrix of Attittudes Towards Policy Researchers Items in Study 2") #stars = FALSE, 
dev.off()

# correlation plot with corrgram package
png(filename="/Users/cintiahinojosa/Box/Dissertation/images/policy_corrgram_s2.png", height = 700, width = 1000)
corrgram::corrgram(policy_vars_s2
         , main = "Correlation Matrix of Attittudes Towards Policy Researchers Items in Study 2 (Ordered)"
         , lower.panel = panel.cor #panel.cor, panel.pts, panel.conf
#         , upper.panel =  NULL #panel.conf #panel.shade #NULL
#         , diag.panel = panel.txt #panel.density, panel.minmax
         , text.panel = panel.txt
         , order = TRUE # "PCA" = TRUE
         , col.regions = colorRampPalette(c("red4", "grey", "darkgreen"))
           )
dev.off()

# CREATE COMPOSITE ---------------------------
freq(s2$policy_trust)
s2$policy <- rowMeans(subset(s2, select = policy_vars.names_s2), na.rm = TRUE)
summary(s2$policy)
policy_alpha_s2 <- ltm::cronbach.alpha(policy_vars_s2)
papaja::printnum(policy_alpha_s2$alpha) # 

# GRAND-MEAN CENTER & STANDARDIZE ---------------------------
s2 <- s2 %>%
  mutate(policy.c = scale(policy, center = TRUE, scale = TRUE)
         , policy_trust.c = scale(policy_trust, center = TRUE, scale = TRUE)
         , policy_qualify.c = scale(policy_qualify, center = TRUE, scale = TRUE)
         )
summary(s2$policy.c)
summary(s2$policy_trust.c)


# GROUP STANDARDIZED ITEMS ---------------------------
policy.c_vars_s2 <- dplyr::select(s2, policy_trust.c, policy_qualify.c)
policy.c_vars.names_s2 <- names(policy.c_vars_s2)
policy.c_alpha_s2 <- ltm::cronbach.alpha(policy.c_vars_s2)
papaja::printnum(policy.c_alpha_s2$alpha) # .89

# FACTOR ---------------------------
s2$policy_trust.f <- factor(s2$policy_trust, levels = c(1:7), labels = trust7.labels, ordered = TRUE)
s2$policy_qualify.f <- factor(s2$policy_qualify, levels = c(1:7), labels = qualify7.labels, ordered = TRUE)
```
```{r expert-clean-s2}
# ATTITUDES TOWARDS POLICE EXPERTS
# GROUP ITEMS ---------------------------
expert_vars_s2 <- dplyr::select(s2, police, police_trust, police_qualify, policy, policy_trust, policy_qualify)
expert_vars.names_s2 <- names(expert_vars_s2)

# CORRELATIONS ---------------------------
# correlation matrix
expert_cormat_s2 <- cor(expert_vars_s2, use = "complete.obs") 
expert_cormat_s2 <- round(expert_cormat_s2, 3)

# correlation plot with psych package
png(filename="/Users/cintiahinojosa/Box/Dissertation/images/expert_corplot_s2.png", height = 700, width = 1000)
psych::corPlot(expert_vars_s2 # labels = expert_vars.labels_s2
               , scale = TRUE, upper = FALSE, alpha = 0.5
               , main = "Correlation Matrix of Attittudes Towards Experts Items in Study 2") #stars = FALSE, 
dev.off()

# correlation plot with corrgram package
png(filename="/Users/cintiahinojosa/Box/Dissertation/images/expert_corrgram_s2.png", height = 700, width = 1000)
corrgram::corrgram(expert_vars_s2
         , main = "Correlation Matrix of Attittudes Towards Experts Items in Study 2 (Ordered)"
         , lower.panel = panel.cor #panel.cor, panel.pts, panel.conf
#         , upper.panel =  NULL #panel.conf #panel.shade #NULL
#         , diag.panel = panel.txt #panel.density, panel.minmax
         , text.panel = panel.txt
         , order = TRUE # "PCA" = TRUE
         , col.regions = colorRampPalette(c("red4", "grey", "darkgreen"))
           )
dev.off()
```

```{r labels-s2}
# IV LABELS ---------------------------
s2 = expss::apply_labels(s2
     , condition = "Condition"
     , condition.n = "Condition"
     , condition.f = "Condition"
     , critical = "Critical"
     , naive = "Naive"
     , condition.f = "Condition"
     , race = "Racial/ethnic Identity"
     , race.n = "Racial/ethnic identity"
     , race.f = "Racial/ethnic identity"
     , race_multi = "Racial/ethnic identity"
     , race_multi.n = "Multi racial/ethnic"
     , race_multi.f = "Multi racial/ethnic"
     , age = "Age"
     , age.c = "Age"
     , race.f = "Racial/ethnic Identity"
     , gender = "Gender"
     , female = "Female"
     , male = "Male"
     , nonbinary = "Non-binary"
     , gender.n = "Gender"
     , gender.f = "Gender"
     , nonbinary.f = "Non-binary"
     , edu.f = "Education"
     , edu.n = "Education"
     , edu3 = "Education"
     , edu3.n = "Education"
     , edu3.f = "Education"
     , edu_other = "Education"
     , nocollege = "No college degree"
     , nocollege.f = "No college degree"
     , college = "College degree"
     , college.f = "College degree"
     , grad = "Graduate degree"
     , grad.f = "Graduate degree"
     , political = "Political orientation"
     , political.n = "Political orientation"
     , political.f = "Political orientation"
     , political3 = "Political orientation"
     , political3.n = "Political orientation"
     , political3.f = "Political orientation"
     , party = "Political party"
     , party.f = "Political party"
     , party_other_text = "Political party (other)"
     , edu = "Education"
     , edu3 = "Education"
     , edu3.f = "Education"
     , edu_other_text = "Education (Other)"
     , duration = "Study duration (mins)"
     , income.f = "Income"
     , adj_income = "Adj. Income"
     , adj_income.c = "Adj. Income"
)

# DV LABELS ---------------------------
s2 = expss::apply_labels(s2
     , punitive = "Punitive Policy Support"
     , pun_cops = "More police on the streets"
     , pun_jailtime = "Longer jail terms for those convicted of violent crimes"
     , pun_prisons = "More prisons and fewer opportunities for parole"
     , pun_penalty = "Increase criminal penalties for non-violent crimes"
     , punitive.c = "Punitive Policy Support"
     , pun_cops.c = "More police on the streets"
     , pun_jailtime.c = "Longer jail terms for those convicted of violent crimes"
     , pun_penalty.c = "Increase criminal penalties for non-violent crimes"
     , pun_jailtime.f = "Longer jail terms for those convicted of violent crimes"
     , pun_prisons.c = "More prisons and fewer opportunities for parole"
     , pun_cops.f = "More police on the streets"
     , pun_prisons.f = "More prisons and fewer opportunities for parole"
     , pun_penalty.f = "Increase criminal penalties for non-violent crimes"
     , restorative = "Restorative Policy Support"
     , rest_youth = "More community programs for young people"
     , rest_jobs = "Job programs for people in the inner-cities"
     , rest_banbox = "Remove criminal-history questions from employment applications"
     , rest_fedaid = "More federal assistance to the poor"
     , restorative.c = "Restorative Policy Support"
     , rest_youth.c = "More community programs for young people"
     , rest_jobs.c = "Job programs for people in the inner-cities"
     , rest_banbox.c = "Remove criminal-history questions from employment applications"
     , rest_fedaid.c = "More federal assistance to the poor"
     , rest_youth.f = "More community programs for young people"
     , rest_jobs.f = "Job programs for people in the inner-cities"
     , rest_banbox.f = "Remove criminal-history questions from employment applications"
     , rest_fedaid.f = "More federal assistance to the poor"
     , sr.c = "Symbolic Racism"
     , sri.c = "Internal Symbolic Racism"
     , sre.c = "External Symbolic Racism"
     , sr.s = "Symbolic Racism"
     , sri.s = "Internal Symbolic Racism"
     , sre.s = "External Symbolic Racism"
     , sr_hard = "It's really a matter of some people not trying hard enough; if Black people would only try harder, they could be just as well off as whites."
     , sr_minorities = "Irish, Italian, Jewish, and many other minorities overcame
    prejudice and worked their way up. Black people should do the same."
     , sr_demand = "Black people are demanding too much from the rest of society."
     , sr_complain_r = "Black people generally do not complain as much as they should about their situation in society. (R)"
     , sr_slavery_r = "Generations of slavery and discrimination have created conditions that make it difficult for Black people to work their way out of the lower class. (R)"
     , sr_deserve_r = "Over the past few years, Black people have gotten less than they deserve. (R)"
     , sr_econ = "Over the past few years, Black people have gotten more economically than they deserve."
     , sr_tension = "How much of the racial tension that exists in the United States today do you think Black people are responsible for creating?"
     , sr_discrim_r = "How much discrimination against Black people do you feel there is in the United States today, limiting their chances to get ahead? (R)"
     , sr_change = "Has there been a lot of real change in the position of Black people in the past few years?"
     , sr_hard.c = "It's really a matter of some people not trying hard enough; if Black people would only try harder, they could be just as well off as whites."
     , sr_minorities.c = "Irish, Italian, Jewish, and many other minorities overcame
    prejudice and worked their way up. Black people should do the same."
     , sr_demand.c = "Black people are demanding too much from the rest of society."
     , sr_complain_r.c = "Black people generally do not complain as much as they should about their situation in society. (R)"
     , sr_slavery_r.c = "Generations of slavery and discrimination have created conditions that make it difficult for Black people to work their way out of the lower class. (R)"
     , sr_deserve_r.c = "Over the past few years, Black people have gotten less than they deserve. (R)"
     , sr_econ.c = "Over the past few years, Black people have gotten more economically than they deserve."
     , sr_tension.c = "How much of the racial tension that exists in the United States today do you think Black people are responsible for creating?"
     , sr_discrim_r.c = "How much discrimination against Black people do you feel there is in the United States today, limiting their chances to get ahead? (R)"
     , sr_change.c = "Has there been a lot of real change in the position of Black people in the past few years?"
     , sr_hard.f = "It's really a matter of some people not trying hard enough; if Black people would only try harder, they could be just as well off as whites."
     , sr_minorities.f = "Irish, Italian, Jewish, and many other minorities overcame
    prejudice and worked their way up. Black people should do the same."
     , sr_demand.f = "Black people are demanding too much from the rest of society."
     , sr_complain_r.f = "Black people generally do not complain as much as they should about their situation in society. (R)"
     , sr_slavery_r.f = "Generations of slavery and discrimination have created conditions that make it difficult for Black people to work their way out of the lower class. (R)"
     , sr_deserve_r.f = "Over the past few years, Black people have gotten less than they deserve. (R)"
     , sr_econ.f = "Over the past few years, Black people have gotten more economically than they deserve."
     , sr_tension.f = "How much of the racial tension that exists in the United States today do you think Black people are responsible for creating?"
     , sr_discrim_r.f = "How much discrimination against Black people do you feel there is in the United States today, limiting their chances to get ahead? (R)"
     , sr_change.f = "Has there been a lot of real change in the position of Black people in the past few years?"
     , gunbeliefs4 = "Stereotypes about Urban Gun Violence"
     , gunbeliefs = "Stereotypes about Urban Gun Violence"
     , gunbeliefs4.c = "Stereotypes about Urban Gun Violence"
     , gunbeliefs.c = "Stereotypes about Urban Gun Violence"
     , gun_parent = "We wouldn’t have so much gun violence in poor inner-city neighborhoods if the kids doing the shooting had parents who took responsibility for raising them"
     , gun_street = "Gun violence in poor inner-city neighborhoods won’t improve unless we get the criminals who are doing the shooting off the streets for good"
     , gun_work = "If we could get violent criminals off the streets of poor inner-city neighborhoods, the decent, hard-working people in those neighborhoods could lift themselves out of poverty"
     , gun_punish = "If the people doing the shooting in poor inner-city neighborhoods knew they would be caught and severely punished, we’d see a lot less gun violence in those neighborhoods"
     , gun_parent.c = "Lack of parent responsibility"
     , gun_street.c = "Get criminals off the streets for good"
     , gun_work.c = "Decent people can lift themselves out of poverty \n if criminals were off the streets"
     , gun_punish.c = "Criminals need to know they would be caught \n and severely punished"
     , inequality = "Perceived inequality"
     , inequality_edu = "Perceived inequality of educational opportunities"
     , inequality_job = "Perceived inequality of job opportunities"
     , inequality_chance = "Perceived inequality of opportunities to get ahead"
     , inequality_race = "Perceived inequality disadvantaging certain races"
     , inequality_poor = "Perceived inequality disadvantaging the poor"
     , inequality_fem = "Perceived inequality disadvantaging women"
     , ineq_edurace = "Certain racial or ethnic groups have fewer chances to get a good high school education."
     , ineq_edupoor = "Poor children have fewer chances to get a good high school education."
     , ineq_edufem = "Women have fewer chances to get a good high school education."
     , ineq_jobrace = "Certain racial or ethnic groups have fewer chances to get good jobs"
     , ineq_jobfem = "Women have fewer chances to get good jobs."
     , ineq_jobpoor = "Poor people have fewer chances to get good jobs"
     , ineq_chancerace = "Certain racial or ethnic groups have fewer chances to get ahead."
     , ineq_chancefem = "Women have fewer chances to get ahead."
     , ineq_chancepoor = "Poor people have fewer chances to get ahead."
     , ineq_edurace.f = "Certain racial or ethnic groups have fewer chances to get a good high school education."
     , ineq_edupoor.f = "Poor children have fewer chances to get a good high school education."
     , ineq_edufem.f = "Women have fewer chances to get a good high school education."
     , ineq_jobrace.f = "Certain racial or ethnic groups have fewer chances to get good jobs"
     , ineq_jobfem.f = "Women have fewer chances to get good jobs."
     , ineq_jobpoor.f = "Poor people have fewer chances to get good jobs"
     , ineq_chancerace.f = "Certain racial or ethnic groups have fewer chances to get ahead."
     , ineq_chancefem.f = "Women have fewer chances to get ahead."
     , ineq_chancepoor.f = "Poor people have fewer chances to get ahead."
     , ineq_edurace.f = "Certain racial or ethnic groups have fewer chances to get a good high school education."
     , ineq_edupoor.c = "Poor children have fewer chances to get a good high school education."
     , ineq_edufem.c = "Women have fewer chances to get a good high school education."
     , ineq_jobrace.c = "Certain racial or ethnic groups have fewer chances to get good jobs"
     , ineq_jobfem.c = "Women have fewer chances to get good jobs."
     , ineq_jobpoor.c = "Poor people have fewer chances to get good jobs"
     , ineq_chancerace.c = "Certain racial or ethnic groups have fewer chances to get ahead."
     , ineq_chancefem.c = "Women have fewer chances to get ahead."
     , ineq_chancepoor.c = "Poor people have fewer chances to get ahead."
     , egalitarian = "Egalitarianism"
     , egal_hierarchy = "It is a good thing that certain groups are at the top and other groups are at the bottom."
     , egal_good = "It would be good if groups could be equal."
     , egal_ideal = "Group equality should be our ideal."
     , egal_chance = "All groups should be given an equal chance in life."
     , egal_lessprobs = "We would have fewer problems if we treated people more equally."
     , egalitarian.c = "Egalitarianism"
     , egal_hierarchy.c = "It is a good thing that certain groups are at the top and other groups are at the bottom."
     , egal_good.c = "It would be good if groups could be equal."
     , egal_ideal.c = "Group equality should be our ideal."
     , egal_chance.c = "All groups should be given an equal chance in life."
     , egal_lessprobs.c = "We would have fewer problems if we treated people more equally."
    , police = "Attitudes towards police officials"
    , police_trust = "When it comes to deciding how to address gun violence, how TRUSTWORTHY are police officials?"
    , police_qualify = "When it comes to deciding how to address gun violence, how QUALIFIED are police officials?"
    , policy = "Attitudes towards policy officials"
    , policy_trust = "When it comes to deciding how to address gun violence, how TRUSTWORTHY are policy researchers?"
    , policy_qualify = "When it comes to deciding how to address gun violence, how QUALIFIED are policy researchers?"
    , police.c = "Attitudes towards police officials"
    , police_trust.c = "When it comes to deciding how to address gun violence, how TRUSTWORTHY are police officials?"
    , police_qualify.c = "When it comes to deciding how to address gun violence, how QUALIFIED are police officials?"
    , policy.c = "Attitudes towards policy officials"
    , policy_trust.c = "When it comes to deciding how to address gun violence, how TRUSTWORTHY are policy researchers?"
    , policy_qualify.c = "When it comes to deciding how to address gun violence, how QUALIFIED are policy researchers?"
    , police.f = "Attitudes towards police officials"
    , police_trust.f = "When it comes to deciding how to address gun violence, how TRUSTWORTHY are police officials?"
    , police_qualify.f = "When it comes to deciding how to address gun violence, how QUALIFIED are police officials?"
    , policy.f = "Attitudes towards policy officials"
    , policy_trust.f = "When it comes to deciding how to address gun violence, how TRUSTWORTHY are policy researchers?"
    , policy_qualify.f = "When it comes to deciding how to address gun violence, how QUALIFIED are policy researchers?"
     , nfc_simple = "I prefer complex to simple problems."
     , nfc_resp = "I like to have the responsibility of handling a situation that requires a lot of thinking."
     , nfc_notfun = "(R)Thinking is not my idea of fun."
     , nfc_nochallenge = "(R)I would rather do something that requires little thought than something that is sure to challenge my thinking abilities."
     , nfc_avoid = "(R)I try to anticipate and avoid situations where there is a likely chance that I will have to think in depth about something."
     , nfc_satisfy = "I find satisfaction in deliberating hard for long hours."
     , nfc_only = "(R)I only think as hard as I have to."
     , nfc_daily = "(R)I prefer to think about small daily projects to long-term ones."
     , nfc_little = "(R)I like tasks that require little thought once I’ve learned them."
     , nfc_rely = "The idea of relying on thought to make my way to the top appeals to me."
     , nfc_solutions = "I really enjoy a task that involves coming up with new solutions to problems."
     , nfc_unexcite = "(R) Learning new ways to think doesn’t excite me."
     , nfc_puzzles = "I prefer my life to be filled with puzzles that I must solve."
     , nfc_abstract = "The notion of thinking abstractly is appealing to me."
     , nfc_difficult = "I would prefer a task that is intellectual, difficult, and important to one that is somewhat important but does not require much thought."
     , nfc_relief = "(R)I feel relief rather than satisfaction after completing a task that required a lot of mental effort."
     , nfc_done = "(R)It’s enough for me that something gets the job done; I don’t care how or why it works."
     , nfc_deliberate = "I usually end up deliberating about issues even when they do not affect me personally."
     , nfc_simple.c = "I prefer complex to simple problems."
     , nfc_resp.c = "I like to have the responsibility of handling a situation that requires a lot of thinking."
     , nfc_notfun.c = "(R)Thinking is not my idea of fun."
     , nfc_nochallenge.c = "(R)I would rather do something that requires little thought than something that is sure to challenge my thinking abilities."
     , nfc_avoid.c = "(R)I try to anticipate and avoid situations where there is a likely chance that I will have to think in depth about something."
     , nfc_satisfy.c = "I find satisfaction in deliberating hard for long hours."
     , nfc_only.c = "(R)I only think as hard as I have to."
     , nfc_daily.c = "(R)I prefer to think about small daily projects to long-term ones."
     , nfc_little.c = "(R)I like tasks that require little thought once I’ve learned them."
     , nfc_rely.c = "The idea of relying on thought to make my way to the top appeals to me."
     , nfc_solutions.c = "I really enjoy a task that involves coming up with new solutions to problems."
     , nfc_unexcite.c = "(R) Learning new ways to think doesn’t excite me."
     , nfc_puzzles.c = "I prefer my life to be filled with puzzles that I must solve."
     , nfc_abstract.c = "The notion of thinking abstractly is appealing to me."
     , nfc_difficult.c = "I would prefer a task that is intellectual, difficult, and important to one that is somewhat important but does not require much thought."
     , nfc_relief.c = "(R)I feel relief rather than satisfaction after completing a task that required a lot of mental effort."
     , nfc_done.c = "(R)It’s enough for me that something gets the job done; I don’t care how or why it works."
     , nfc_deliberate.c = "I usually end up deliberating about issues even when they do not affect me personally."
     , nfc_simple.f = "I prefer complex to simple problems."
     , nfc_resp.f = "I like to have the responsibility of handling a situation that requires a lot of thinking."
     , nfc_notfun.f = "(R)Thinking is not my idea of fun."
     , nfc_nochallenge.f = "(R)I would rather do something that requires little thought than something that is sure to challenge my thinking abilities."
     , nfc_avoid.f = "(R)I try to anticipate and avoid situations where there is a likely chance that I will have to think in depth about something."
     , nfc_satisfy.f = "I find satisfaction in deliberating hard for long hours."
     , nfc_only.f = "(R)I only think as hard as I have to."
     , nfc_daily.f = "(R)I prefer to think about small daily projects to long-term ones."
     , nfc_little.f = "(R)I like tasks that require little thought once I’ve learned them."
     , nfc_rely.f = "The idea of relying on thought to make my way to the top appeals to me."
     , nfc_solutions.f = "I really enjoy a task that involves coming up with new solutions to problems."
     , nfc_unexcite.f = "(R) Learning new ways to think doesn’t excite me."
     , nfc_puzzles.f = "I prefer my life to be filled with puzzles that I must solve."
     , nfc_abstract.f = "The notion of thinking abstractly is appealing to me."
     , nfc_difficult.f = "I would prefer a task that is intellectual, difficult, and important to one that is somewhat important but does not require much thought."
     , nfc_relief.f = "(R)I feel relief rather than satisfaction after completing a task that required a lot of mental effort."
     , nfc_done.f = "(R)It’s enough for me that something gets the job done; I don’t care how or why it works."
     , nfc_deliberate.f = "I usually end up deliberating about issues even when they do not affect me personally."
    ) # police_trust, police_qualify, policy_trust, policy_qualify, nfc
     # , isr1.hard = "(Int1) not trying hard enough"
     # , isr2.minorities = "(Int2) other minorities got over it" 
     # , isr3.demand = "(Int3) too demanding"
     # , isr4.tension = "(Int4) to blame for tension"
     # , isr5.complain = "(Int5) don't complain enough (R)"
     # , esr6.discrim = "(Ext6) discrimination today (R)"
     # , esr7.slavery = "(Ext7) slavery impacts today (R)"
     # , esr8.change = "(Ext8) recent change in position"
     # , esr9.deserve = "(Ext9) gotten less than deserved (R)"
     # , esr10.econ = "(Ext10) gotten more than deserved"
```

```{r fun-group-s2, eval = TRUE}
# GROUPED TABLE WITH P-VALUES
##################################
# create condition variable that has empty stratum
s2$condition.n <- as.numeric(s2$condition.f)
s2$group = NA
s2$group <- factor(s2$condition.n, levels = c(1,2,3), labels = c("Critical", "Naive", "P-value"))

# function
rndr <- function(x, name, ...) {
    if (length(x) == 0) {
        y <- s2[[name]]
        s <- rep("", length(render.default(x = y, name = name, ...)))
        if (is.numeric(y)) {
            p <- t.test(y ~ s2$group)$p.value
        } else {
            p <- chisq.test(table(y, droplevels(s2$group)))$p.value
        }
        s[2] <- sub("<", "&lt;", format.pval(p, digits = 3, eps = 0.001))
        s
    } else {
        render.default(x = x, name = name, ...)
    }
}

rndr.strat <- function(label, n, ...) {
    ifelse(n == 0, label, render.strat.default(label, n, ...))
}


# naive & critical #
s2$condition.ncrit = NA
s2$condition.ncrit[s2$condition == "naive"] <- "naive"
s2$condition.ncrit[s2$condition == "critical"] <- "critical"
s2$condition.ncrit <- as.factor(s2$condition.ncrit)

# create condition variable that has empty stratum
s2$group.ncrit    <- factor(as.numeric(s2$condition.ncrit), levels = c(1,2,3), labels = c("Critical", "Naive", "P-value"))

# function
rndr.ncrit <- function(x, name, ...) {
    if (length(x) == 0) {
        y <- s2[[name]]
        s <- rep("", length(render.default(x = y, name = name, ...)))
        if (is.numeric(y)) {
            p <- t.test(y ~ s2$group.ncrit)$p.value
        } else {
            p <- chisq.test(table(y, droplevels(s2$group.ncrit)))$p.value
        }
        s[2] <- sub("<", "&lt;", format.pval(p, digits = 3, eps = 0.001))
        s
    } else {
        render.default(x = x, name = name, ...)
    }
}

rndr.ncrit.strat <- function(label, n, ...) {
    ifelse(n == 0, label, render.strat.default(label, n, ...))
}
```

```{r groups-s2}
# SAVE VARIABLE GROUPS ---------------------------
demo_vars_s2 <- dplyr::select(s2, condition, gender, race.f, political.f, age, edu3.f, adj_income, duration)
race_vars_s2 <- dplyr::select(s2, c(white, black, latino, native, asian, mideastern, islander, race_other, multiracial))
main_vars_s2 <- dplyr::select(s2, punitive, restorative, sr.c)
expl_vars_s2 <- dplyr::select(s2, inequality, egalitarian, nfc)
```

```{r values-s2}
# save values for in-line reporting #
# IVs  ---------------------------
male_perc_s2 = papaja::printnum(100*(sum(s2$male)/nrow(s2)), digits = 0)
female_perc_s2 = papaja::printnum(100*(sum(s2$female)/nrow(s2)), digits = 0)

white_perc_s2 = papaja::printnum(100*(sum(s2$white)/nrow(s2)), digits = 0)
black_perc_s2 = papaja::printnum(100*(sum(s2$black)/nrow(s2)), digits = 0)
latino_perc_s2 = papaja::printnum(100*(sum(s2$latino)/nrow(s2)), digits = 0)
asian_perc_s2 = papaja::printnum(100*(sum(s2$asian)/nrow(s2)), digits = 0)
native_perc_s2 = papaja::printnum(100*(sum(s2$native)/nrow(s2)), digits = 0)
mideastern_perc_s2 = papaja::printnum(100*(sum(s2$mideastern)/nrow(s2)), digits = 0)

income_med_s2 <- papaja::printnum(median(s2$adj_income))
income_m_s2 <- papaja::printnum(mean(s2$adj_income))
income_sd_s2 <- papaja::printnum(psych::SD(s2$adj_income))

# OUTLIERS  ---------------------------
# mark duration quantiles for outliers
duration_q1_s2 <- quantile(s2$duration, .25) 
duration_q3_s2 <- quantile(s2$duration, .75) 
duration_iqr_s2 <- IQR(s2$duration) 

# duration_out_s2 <- boxplot.stats(s2$duration)$out
# duration_out_s2 <- which(s2$duration < duration_q1_s2 | s2$duration > duration_q3_s2)

# DURATION ---------------------------
duration_m_s2 <- papaja::printnum(mean(s2$duration))
duration_sd_s2 <- papaja::printnum(psych::SD(s2$duration))

duration_m_s2.naive <- papaja::printnum(mean(s2[s2$condition == "naive", "duration"]))
duration_sd_s2.naive <- papaja::printnum(psych::SD(s2[s2$condition == "naive", "duration"]))

duration_m_s2.critical <- papaja::printnum(mean(s2[s2$condition == "critical", "duration"]))
duration_sd_s2.critical <- papaja::printnum(psych::SD(s2[s2$condition == "critical", "duration"]))

# PUNITIVE ---------------------------
pun_m_s2 <- papaja::printnum(mean(s2$punitive))
pun_sd_s2 <- papaja::printnum(psych::SD(s2$punitive))

pun_m_s2.critical <- papaja::printnum(mean(s2[s2$condition == "critical", "punitive"]))
pun_sd_s2.critical <- papaja::printnum(psych::SD(s2[s2$condition == "critical", "punitive"]))

pun_m_s2.naive <- papaja::printnum(mean(s2[s2$condition == "naive", "punitive"]))
pun_sd_s2.naive <- papaja::printnum(psych::SD(s2[s2$condition == "naive", "punitive"]))
pun_skew_s2 <- papaja::printnum(moments::skewness(s2$punitive, na.rm = TRUE))
pun_skew_s2 <- papaja::printnum(moments::skewness(s2$punitive, na.rm = TRUE))

# RESTORATIVE ---------------------------
rest_m_s2 <- papaja::printnum(mean(s2$restorative))
rest_sd_s2 <- papaja::printnum(psych::SD(s2$restorative))

rest_m_s2.critical <- papaja::printnum(mean(s2[s2$condition == "critical", "restorative"]))
rest_sd_s2.critical <- papaja::printnum(psych::SD(s2[s2$condition == "critical", "restorative"]))

rest_m_s2.naive <- papaja::printnum(mean(s2[s2$condition == "naive", "restorative"]))
rest_sd_s2.naive <- papaja::printnum(psych::SD(s2[s2$condition == "naive", "restorative"]))
rest_skew_s2 <- papaja::printnum(moments::skewness(s2$restorative, na.rm = TRUE))

# MODERN RACISM ---------------------------
sr_m_s2 <- papaja::printnum(mean(s2$sr))
sr_sd_s2 <- papaja::printnum(psych::SD(s2$sr))

sr_m_s2.critical <- papaja::printnum(mean(s2[s2$condition == "critical", "sr"]))
sr_sd_s2.critical <- papaja::printnum(psych::SD(s2[s2$condition == "critical", "sr"]))

sr_m_s2.naive <- papaja::printnum(mean(s2[s2$condition == "naive", "sr"]))
sr_sd_s2.naive <- papaja::printnum(psych::SD(s2[s2$condition == "naive", "sr"]))
```

```{r dvs-reshape-s2}
# DEPENDENT VARIABLES ---------------------------
# select id, dvs and condition
dvs_s2 <- dplyr::select(s2
, id, startdate
, punitive, names(punitive_vars_s2), names(punitive.f_vars_s2)
, punitive.c, names(punitive.c_vars_s2)
, restorative, names(restorative_vars_s2), names(restorative.f_vars_s2)
, restorative.c, names(restorative.c_vars_s2)
, sr, sre, sri, names(sr_vars_s2)
, sr.c, sre.c, sri.c, names(sr.c_vars_s2)
, gunbeliefs4, gunbeliefs, names(gunbeliefs4_vars_s2)
, gunbeliefs4.c, gunbeliefs.c, names(gunbeliefs4.c_vars_s2)
, inequality, names(inequality_vars_s2)
, inequality.c, names(inequality.c_vars_s2)
, inequality_edu, inequality_job, inequality_chance, inequality_race, inequality_poor, inequality_fem
, inequality_edu.c, inequality_job.c, inequality_chance.c, inequality_race.c, inequality_poor.c, inequality_fem
, egalitarian, names(egalitarian_vars_s2)
, egalitarian.c, names(egalitarian.c_vars_s2)
, nfc, names(nfc_vars_s2)
, nfc.c, names(nfc.c_vars_s2)
, comment
, condition#, condition.f #, condition.n, critical, naive
)

# remove labels
dvs_s2 <-   sjlabelled::unlabel(dvs_s2)

# separate dv scores by condition
# names(dvs_s2)
dvs_s2.wide <- tidyr::pivot_wider(dvs_s2,
                            names_from = condition,
                            names_sep = "__",
                            values_from = punitive:comment)

# reshape to long
# names(dvs_s2.wide)
dvs_s2.long <- tidyr::pivot_longer(dvs_s2.wide,
                                   cols = punitive__critical:comment__naive,
                                   names_sep = "__",
                                   names_to = c("dv", "condition"),
                                   values_to = "score",
                                   values_transform = list(score = as.numeric)
                                   ) 

# order by start date
dvs_s2.long <- dvs_s2.long[order(dvs_s2.long$startdate),]

# reshape to wide
dvs_s2.wide <- tidyr::pivot_wider(dvs_s2.long, names_from = "dv", values_from = "score")

# PREVIEW ---------------------------
# codebook
#sjPlot::view_df(dvs_s2.wide, show.type = TRUE, show.values = TRUE, show.string.values = TRUE, show.labels = TRUE, wrap.labels = 40, show.frq = TRUE, show.prc = TRUE, use.viewer = FALSE) 

# preview
dvs_s2.wide %>% glimpse() %>% head(.,20)
dvs_s2.long %>% glimpse() %>% head(.,20)
```

```{r ivs-reshape-s2}
# INDEPENDENT VARIABLES ---------------------------
# select id, ivs and condition
ivs_s2 <-   dplyr::select(s2
, id, startdate
, duration
, political, political3, liberal, moderate, conservative
, political.f, political3.f, liberal.f, moderate.f, conservative.f
, party, democrat, independent, republican
, party.f, democrat.f, independent.f, republican.f
, gender, female, male
, gender.f, female.f, male.f
, race, white:race_other, multiracial
, race.f, multiracial.f # , race.n
, age, age.c
, edu, edu3, nocollege, college, grad
, edu.f, edu3.f, nocollege.f, college.f, grad.f
, adj_income, adj_income.c, income.f, income.med, household # , vote
, condition#, condition.f, condition.n, critical, naive
)

# remove labels
ivs_s2 <-   sjlabelled::unlabel(ivs_s2)

# separate iv scores by condition
names(ivs_s2)
ivs_s2.wide <- tidyr::pivot_wider(ivs_s2,
                            names_from = condition,
                            names_sep = "__",
                            values_from = duration:household)

# reshape to long
names(ivs_s2.wide)
ivs_s2.long <- tidyr::pivot_longer(ivs_s2.wide,
                                   cols = duration__critical:household__naive,
                                   names_sep = "__",
                                   names_to = c("iv", "condition"),
                                   values_to = "score",
                                   values_transform = list(score = as.numeric)
                                   ) 

# order by start date
ivs_s2.long <- ivs_s2.long[order(ivs_s2.long$startdate),]

# reshape to wide
ivs_s2.wide <- tidyr::pivot_wider(ivs_s2.long, names_from = "iv", values_from = "score")

# PREVIEW ---------------------------
# codebook
#sjPlot::view_df(ivs_s2.wide, show.type = TRUE, show.values = TRUE, show.string.values = TRUE, show.labels = TRUE, wrap.labels = 40, show.frq = TRUE, show.prc = TRUE, use.viewer = FALSE) 

# preview
ivs_s2.wide %>% glimpse() %>% head(.,20)
ivs_s2.long %>% glimpse() %>% head(.,20)

```

```{r reshape-s2}
# ALL MAIN VARS ---------------------------
# select id, ivs and condition
s2.wide <- dplyr::select(s2
, id, startdate
, punitive, names(punitive_vars_s2), names(punitive.f_vars_s2)
, punitive.c, names(punitive.c_vars_s2)
, restorative, names(restorative_vars_s2), names(restorative.f_vars_s2)
, restorative.c, names(restorative.c_vars_s2)
, sr, sre, sri, names(sr_vars_s2)
, sr.c, sre.c, sri.c, names(sr.c_vars_s2)
, gunbeliefs4, gunbeliefs, names(gunbeliefs4_vars_s2)
, gunbeliefs4.c, gunbeliefs.c, names(gunbeliefs4.c_vars_s2)
, inequality, names(inequality_vars_s2)
, inequality.c, names(inequality.c_vars_s2)
, inequality_edu, inequality_job, inequality_chance, inequality_race, inequality_poor, inequality_fem
, inequality_edu.c, inequality_job.c, inequality_chance.c, inequality_race.c, inequality_poor.c, inequality_fem
, comment
, duration
, political, political3, liberal, moderate, conservative
, political.f, political3.f, liberal.f, moderate.f, conservative.f
, party, democrat, independent, republican
, party.f, democrat.f, independent.f, republican.f
, gender, female, male
, gender.f, female.f, male.f
, race, white:race_other, multiracial
, race.f, multiracial.f # , race.n
, age, age.c
, edu, edu3, nocollege, college, grad
, edu.f, edu3.f, nocollege.f, college.f, grad.f
, adj_income, adj_income.c, income.f, income.med, household # , vote
, condition#, condition.f, condition.n, critical, naive
)

# remove labels
s2.wide <-   sjlabelled::unlabel(s2.wide)

# separate dv scores by condition
# names(s2.wide)
s2.wide <- tidyr::pivot_wider(s2.wide,
                            names_from = condition,
                            names_sep = "__",
                            values_from = punitive:household)

# reshape to long
# names(s2.wide)
s2.long <- tidyr::pivot_longer(s2.wide,
                                   cols = punitive__critical:household__naive,
                                   names_sep = "__",
                                   names_to = c("variable", "condition"),
                                   values_to = "score",
                                   values_transform = list(score = as.numeric)
                                   ) 

# order by start date
s2.long <- s2.long[order(s2.long$startdate),]

# reshape to wide
s2.wide <- tidyr::pivot_wider(s2.long, names_from = "variable", values_from = "score")

# PREVIEW ---------------------------
# codebook
#sjPlot::view_df(s2.wide, show.type = TRUE, show.values = TRUE, show.string.values = TRUE, show.labels = TRUE, wrap.labels = 40, show.frq = TRUE, show.prc = TRUE, use.viewer = FALSE) 

# preview
s2.wide %>% glimpse() %>% head(.,20)
s2.long %>% glimpse() %>% head(.,20)
```

```{r codebook-clean-s2, eval = TRUE}
# CODEBOOK ---------------------------
sjPlot::view_df(s2, show.type = TRUE, show.values = TRUE, show.string.values = TRUE, show.labels = TRUE, wrap.labels = 40, show.frq = TRUE, show.prc = TRUE, use.viewer = FALSE)

sjPlot::view_df(s2.wide, show.type = TRUE, show.values = TRUE, show.string.values = TRUE, show.labels = TRUE, wrap.labels = 40, show.frq = TRUE, show.prc = TRUE, use.viewer = FALSE)
```

```{r save-s2}
# SAVE WORKSPACE ---------------------------
save.image(file = "/Users/cintiahinojosa/Box/Dissertation/data/dissertation-workspace.RData")
# save.image(file = "/Users/cintiahinojosa/Box/Dissertation/data/clean-s2.RData")

# SAVE CLEANED DATA ---------------------------
save(s2, file = "/Users/cintiahinojosa/Box/Dissertation/data/s2.RData")
write.csv(s2, file = "/Users/cintiahinojosa/Box/Dissertation/data/s2.csv")
#foreign::write.dta(s2, "/Users/cintiahinojosa/Box/Dissertation/data/s2.dta")
#sjlabelled::write_spss(s2, "/Users/cintiahinojosa/Box/Dissertation/data/s2.sav")

# long
save(s2.long, file = "/Users/cintiahinojosa/Box/Dissertation/data/s2.long.RData")
write.csv(s2.long, file = "/Users/cintiahinojosa/Box/Dissertation/data/s2.long.csv")

# wide
save(s2.wide, file = "/Users/cintiahinojosa/Box/Dissertation/data/s2.wide.RData")
write.csv(s2.wide, file = "/Users/cintiahinojosa/Box/Dissertation/data/s2.wide.csv")
```


## Other

```{r critcon-clean-s2-old, eval = FALSE}
# CRITICAL CONSCIOUSNESS COMPOSITE
s2$critcon <- rowMeans(subset(s2, select = c(ineq_edurace.n, ineq_edupoor.n, ineq_edufem.n, ineq_jobrace.n, ineq_jobpoor.n, ineq_jobfem.n ,ineq_chancerace.n, ineq_chancepoor.n, ineq_chancefem.n, egal_good, egal_hierarchy, egal_ideal, egal_lessprobs, egal_chance)), na.rm = TRUE)
```

```{r outliers-s2, eval = FALSE}
# DURATION OUTLIERS ---------------------------
# save dataset with drops if duration < 5 mins
#s2.num.pass <- subset(s2.num, s2.num$duration > 5)
#s2.txt.pass <- subset(s2.txt, s2.txt$duration > 5)
```

```{r subset-s2, eval = FALSE}
# CONDITIONS ---------------------------
s2.critical <- subset(s2, condition == "critical")
s2.naive <- subset(s2, condition == "naive")

# RACE ---------------------------
s2.black <- subset(s2, black == 1)
s2.latino <- subset(s2, latino == 1)
s2.white <- subset(s2, white == 1)
```

```{r demo_means_s2, eval = FALSE}
male_perc_s2 = papaja::printnum(100*(sum(s2$male.n)/nrow(s2)), digits = 0)
female_perc_s2 = papaja::printnum(100*(sum(s2$female.n)/nrow(s2)), digits = 0)

white_perc_s2 = papaja::printnum(100*(sum(s2$white.n)/nrow(s2)), digits = 0)
black_perc_s2 = papaja::printnum(100*(sum(s2$black.n)/nrow(s2)), digits = 0)
latino_perc_s2 = papaja::printnum(100*(sum(s2$latino.n)/nrow(s2)), digits = 0)
asian_perc_s2 = papaja::printnum(100*(sum(s2$asian.n)/nrow(s2)), digits = 0)
native_perc_s2 = papaja::printnum(100*(sum(s2$native.n)/nrow(s2)), digits = 0)
mideastern_perc_s2 = papaja::printnum(100*(sum(s2$mideastern.n)/nrow(s2)), digits = 0)

income_med_s2 <- papaja::printnum(median(s2$adj_income))
income_m_s2 <- papaja::printnum(mean(s2$adj_income))
income_sd_s2 <- papaja::printnum(psych::SD(s2$adj_income))
```

```{r duration_test_s2, eval = FALSE}
duration_ttest_s2 <- papaja::apa_print(t.test(duration ~ condition.f, data = s2))

duration_anova_s2 <- aov(duration ~ condition.f, data = s2)
duration_anova.apa_s2 <- papaja::apa_print(duration_anova_s2)

duration_lm_s2 <- lm(duration ~ condition.f, data = s2)
duration_lm.est_s2 <- flexplot::estimates(duration_lm_s2) #duration_lm.est_s2$difference.matrix 
```

